$axure.loadCurrentPage({
  "url":"第一次登陆主页.html",
  "generationDate":new Date(1470576988512.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6a4c79b02a6b4a2388a3722ff2f593aa",
    "type":"Axure:Page",
    "name":"第一次登陆主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"870dce6908c34b9d8b3652d1a44d45ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":870},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"613fadb222984d71a6ad945d8799c392",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":870},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/第一次登陆主页/u0.png"}},
{
          "id":"7d0529b07bf343398f3c178c16833f47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":240},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f239364023a433f84fbd15529842846",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":240},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品列表",
                      "target":{
                        "targetType":"page",
                        "url":"产品列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u14.png"}},
{
          "id":"fed08060b4944ddf85c80a742ceff557",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":430,
              "y":210},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa312d2405454ba9b0c08da92f8f1a97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":430,
                  "y":210},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u16.png"}},
{
          "id":"108585e0b2214dc58ef620187e5f4680",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":445,
              "y":210},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3714de806e9b4d41b424815ec4b0cb0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":445,
                  "y":210},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u18.png"}},
{
          "id":"2b9ad86d1ec444d2bd7c72f26e259d06",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":460,
              "y":210},
            "size":{
              "width":10,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f63166f13e194cc79fe9170687720de3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":460,
                  "y":210},
                "size":{
                  "width":10,
                  "height":10},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u18.png"}},
{
          "id":"e17a95aab7c3497d9381ddd083fd9414",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":810},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2741a307bcbc491492a07d0e0d3e8fe0",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"63f0d7885de7435cb5527707126fd9ad",
                  "label":"",
                  "parentDynamicPanel":"e17a95aab7c3497d9381ddd083fd9414",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "masterId":"bd69c12d7cdd46d7b44b52fbbf59fcbd"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"7c976bb0f82441778193622c59e986af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":10,
              "y":680},
            "size":{
              "width":120,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58c0204cf9954b8c8f0d6ac90e6b2b5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":10,
                  "y":680},
                "size":{
                  "width":120,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品详细",
                      "target":{
                        "targetType":"page",
                        "url":"产品详细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u22.png"}},
{
          "id":"d8bb0cf4b9bb44b7a1b4efe150070474",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"fc4962b9f95d49aca7f012dccbebf100",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f4f1d21226ff47abbb70e682c5b031d3",
                  "label":"",
                  "parentDynamicPanel":"d8bb0cf4b9bb44b7a1b4efe150070474",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2f7e4a7566d84b61b32849239e7223c1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d8bb0cf4b9bb44b7a1b4efe150070474",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"68c1b06243b3455eb3eb2cd1d789be63",
                  "label":"",
                  "parentDynamicPanel":"d8bb0cf4b9bb44b7a1b4efe150070474",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":460,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"394071e1d88e44fc9b310931387d2e75"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"a4a58855e5574443926ac5c7e89d3d45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":130,
              "y":680},
            "size":{
              "width":120,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7425514ceee14557b8d462720da301c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":130,
                  "y":680},
                "size":{
                  "width":120,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品详细",
                      "target":{
                        "targetType":"page",
                        "url":"产品详细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u22.png"}},
{
          "id":"50f819b6f5954402a312a449006f46a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":250,
              "y":680},
            "size":{
              "width":120,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07ae5672786b45bbb4287fc64faa5c5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":250,
                  "y":680},
                "size":{
                  "width":120,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品详细",
                      "target":{
                        "targetType":"page",
                        "url":"产品详细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u22.png"}},
{
          "id":"554f539ac3f4401c8612a5741712d63e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":370,
              "y":680},
            "size":{
              "width":120,
              "height":120},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a42670d8ee404c78a59b826d3f3cb529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":370,
                  "y":680},
                "size":{
                  "width":120,
                  "height":120},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品详细",
                      "target":{
                        "targetType":"page",
                        "url":"产品详细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u22.png"}},
{
          "id":"93cad69683a24b05a89b9831dd997f32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":10,
              "y":460},
            "size":{
              "width":300,
              "height":160},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4627ee06547b4f119a0470d78953e763",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":10,
                  "y":460},
                "size":{
                  "width":300,
                  "height":160},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品详细",
                      "target":{
                        "targetType":"page",
                        "url":"产品详细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u44.png"}},
{
          "id":"36c676fe731648f3a6df698a1fc87325",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":310,
              "y":460},
            "size":{
              "width":180,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ff86e2472b04b5a9059d79363377be8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":310,
                  "y":460},
                "size":{
                  "width":180,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品详细",
                      "target":{
                        "targetType":"page",
                        "url":"产品详细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u46.png"}},
{
          "id":"fb922a10a2884a72befd8d934fcc5039",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":310,
              "y":540},
            "size":{
              "width":180,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef54fdbf844642758f8cf77b1a2459f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":310,
                  "y":540},
                "size":{
                  "width":180,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品详细",
                      "target":{
                        "targetType":"page",
                        "url":"产品详细.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u46.png"}},
{
          "id":"334820ee5bd84eecb95102d4c5e95e0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":410},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"674dcae41e054573bb77c8454174e735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":410},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"ea24e97a10854781931996a5e41acbd6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":20,
              "y":420},
            "size":{
              "width":200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77889d89331147f0881b086a331dfb2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":20,
                  "y":420},
                "size":{
                  "width":200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8289e06082004c46a0e5c2fc66e8b671",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":630},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b3de90fe3b640c383a999dcf0905866",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":630},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"037a85f485c949ef9c7238a0809456d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "location":{
              "x":20,
              "y":640},
            "size":{
              "width":200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69856389fbfa4ecd8a77909adf63617d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "location":{
                  "x":20,
                  "y":640},
                "size":{
                  "width":200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a61ab9a2d2b048aba236af380dcfdce6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":250},
            "size":{
              "width":480,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad983f1c14b04c9f93e91fcffe8a2c7b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":250},
                "size":{
                  "width":480,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u58.png"}},
{
          "id":"5ab0d594e35040628e4ceec5f64e0077",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":360},
            "size":{
              "width":100,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda0c05cda534d808d89af8c28b63ea3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":360},
                "size":{
                  "width":100,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3090d1ec24d847a79b650b453d5fbdb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":30,
              "y":270},
            "size":{
              "width":80,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"528d495501a14e5eac5215ca351c778c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":30,
                  "y":270},
                "size":{
                  "width":80,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u62.png"}},
{
          "id":"d4aa6ca27196432bbbb98247589a8ac3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":140,
              "y":360},
            "size":{
              "width":100,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01d9695d69634a7780c03c79e6e4d2b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":140,
                  "y":360},
                "size":{
                  "width":100,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb0536a7dba44cf3a803e815eaf751c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":150,
              "y":270},
            "size":{
              "width":80,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6f66ec547574517a477e31e4c6a9e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":150,
                  "y":270},
                "size":{
                  "width":80,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u62.png"}},
{
          "id":"1a08b85cf96c4870ab3f6ce254b556d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":260,
              "y":360},
            "size":{
              "width":100,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886bbbc33f824361a69b7a02552a7fe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":360},
                "size":{
                  "width":100,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"832b95d2ba704a849ff7a2e7e094910e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":270,
              "y":270},
            "size":{
              "width":80,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e613d673358549548bef7b76db86c095",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":270,
                  "y":270},
                "size":{
                  "width":80,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u62.png"}},
{
          "id":"0e16438edef84820835a9ef824202b0f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":380,
              "y":360},
            "size":{
              "width":100,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4aae83bfaf345d38a83e2c9b19799cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":380,
                  "y":360},
                "size":{
                  "width":100,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3ab45d1cbb904b63b65278dd69a84faa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":390,
              "y":270},
            "size":{
              "width":80,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d1eabfeee8e4e78ba49fb7574bdac78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":390,
                  "y":270},
                "size":{
                  "width":80,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品服务（分类）",
                      "target":{
                        "targetType":"page",
                        "url":"产品服务（分类）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u62.png"}},
{
          "id":"c60dd4e00fe248e4b4e414ec29acce52",
          "label":"系统定位",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"351ab0f80fa74768b5480aa75a536d86",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"25b65fd05143459385b2e3a93ab9be15",
                  "label":"",
                  "parentDynamicPanel":"c60dd4e00fe248e4b4e414ec29acce52",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "fill":{
                      "fillType":"solid",
                      "color":0x7F000000},
                    "size":{
                      "width":480,
                      "height":870},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x7F000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cda61c5d560e4a998a77229a9690ec98",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c60dd4e00fe248e4b4e414ec29acce52",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "fill":{
                          "fillType":"solid",
                          "color":0x7F000000},
                        "size":{
                          "width":480,
                          "height":870},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x7F000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/第一次登陆主页/u79.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1747d07b855b48bdab1d4c19328ef0b7",
          "label":"位置提示",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":670},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ca608a9cd015459b840b29bbb22c31c4",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1f65d1c6219b4889b4809883d69cc4b8",
                  "label":"",
                  "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "size":{
                      "width":480,
                      "height":200},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6662f1bfda3644e095c998667bbbb88d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "size":{
                          "width":480,
                          "height":200},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/第一次登陆主页/u82.png"}},
{
                  "id":"674d38d29af1462e99a437f98db95253",
                  "label":"",
                  "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "location":{
                      "x":40,
                      "y":110},
                    "size":{
                      "width":400,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"30"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1c368974418420793f941fc1d68b489",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "location":{
                          "x":40,
                          "y":110},
                        "size":{
                          "width":400,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"30"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/第一次登陆主页/u84.png"}},
{
                  "id":"b4cb0f6a95c84bda8d297d6a2b2aacde",
                  "label":"",
                  "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":235,
                      "y":110},
                    "size":{
                      "width":10,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/第一次登陆主页/u86_line.png"}},
{
                  "id":"b3b02a3f3b774f9a8e66d4d8b3566b76",
                  "label":"",
                  "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":60,
                      "y":124},
                    "size":{
                      "width":165,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"29d6d39ff2eb4300b6960b35cc9adbd3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":60,
                          "y":124},
                        "size":{
                          "width":165,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 系统定位",
                              "objectsToFades":[{
                                  "objectPath":["c60dd4e00fe248e4b4e414ec29acce52"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 位置提示",
                              "objectsToFades":[{
                                  "objectPath":["1747d07b855b48bdab1d4c19328ef0b7"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"45f91bc248ff404cb05335a16abc2a19",
                  "label":"",
                  "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":255,
                      "y":123},
                    "size":{
                      "width":165,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1fdc65aa95148cb8c121be910465e9c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":255,
                          "y":123},
                        "size":{
                          "width":165,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 定位",
                              "target":{
                                "targetType":"page",
                                "url":"定位.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"781f05cb7ece4bcf85ba3491a792e62f",
                  "label":"",
                  "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":40,
                      "y":29},
                    "size":{
                      "width":400,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3efcb3f930684036b25f2671f789c96a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":40,
                          "y":29},
                        "size":{
                          "width":400,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"696c867a9b3f4919bec169f7b9409f16",
                  "label":"",
                  "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":40,
                      "y":70},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6906624d942740c8a29a600eeffee633",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1747d07b855b48bdab1d4c19328ef0b7",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":40,
                          "y":70},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "bd69c12d7cdd46d7b44b52fbbf59fcbd":{
      "packageId":"bd69c12d7cdd46d7b44b52fbbf59fcbd",
      "type":"Axure:Master",
      "name":"底部菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"6b310f0e678d48b181949d89b0277be7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d28d8d8c55ed447eadfd69e7a6782e22",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"078f939cda994065a7d80d7a3f8327aa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":96,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c6c09e7e0684ef9a0f20d7159a8da17",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":96,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品服务（分类）",
                        "target":{
                          "targetType":"page",
                          "url":"产品服务（分类）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"56399286ce8943e98036cdddf0c0027f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":192,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"206a19eb311f41b2a8d8a4fa60795674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":192,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物清单",
                        "target":{
                          "targetType":"page",
                          "url":"购物清单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"122a1594a7a24844882178dd2d2a300b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":288,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ee0334c4e084108b37ffbd6009f2fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":288,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 会员中心",
                        "target":{
                          "targetType":"page",
                          "url":"会员中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"8fb898143df2461fa5f60a2d6f71065e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":384,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5b8fcdc760b548a29e70e88b8be2d8e4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":384,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"253a47ab0b284e3f98b0e6d849641899",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":364,
                "y":0},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF0000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8bd318c93aa14e188f863643487752d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":364,
                    "y":0},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u88.png"}}]}},
    "394071e1d88e44fc9b310931387d2e75":{
      "packageId":"394071e1d88e44fc9b310931387d2e75",
      "type":"Axure:Master",
      "name":"搜索",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f5e075e6b0c24551a3d2f27b548547fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":100,
                "y":0},
              "size":{
                "width":40,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e89f87283be34826b9370e9126a4599c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":100,
                    "y":0},
                  "size":{
                    "width":40,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u28.png"}},
{
            "id":"1b26c5d35c984f4fa388018f1868d0d3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":110,
                "y":5},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"38ab782b63834a108f4fb89061ef1465",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":110,
                    "y":5},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 搜索",
                        "target":{
                          "targetType":"page",
                          "url":"搜索.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u30.png"}},
{
            "id":"406cc4bbea764710a287d4923294d571",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "size":{
                "width":30,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"de28fc7bce484ddcae9214751084ab26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u32.png"}},
{
            "id":"c731a6f6d5144c75a64db63c3a6dd892",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":40,
                "y":5},
              "size":{
                "width":50,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"83c9629b25b04e7e8f45d4da6c1e1138",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":40,
                    "y":5},
                  "size":{
                    "width":50,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 定位",
                        "target":{
                          "targetType":"page",
                          "url":"定位.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"15d3b2509dbd4086bd8f71497eaa8120",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":140,
                "y":0},
              "size":{
                "width":320,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3228d0d8a30e498abe7309865cccba46",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":140,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 搜索",
                        "target":{
                          "targetType":"page",
                          "url":"搜索.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u36.png"}}]}}},
  "objectPaths":{
    "870dce6908c34b9d8b3652d1a44d45ea":{
      "scriptId":"u0"},
    "613fadb222984d71a6ad945d8799c392":{
      "scriptId":"u1"},
    "7d0529b07bf343398f3c178c16833f47":{
      "scriptId":"u2"},
    "2f239364023a433f84fbd15529842846":{
      "scriptId":"u3"},
    "fed08060b4944ddf85c80a742ceff557":{
      "scriptId":"u4"},
    "fa312d2405454ba9b0c08da92f8f1a97":{
      "scriptId":"u5"},
    "108585e0b2214dc58ef620187e5f4680":{
      "scriptId":"u6"},
    "3714de806e9b4d41b424815ec4b0cb0d":{
      "scriptId":"u7"},
    "2b9ad86d1ec444d2bd7c72f26e259d06":{
      "scriptId":"u8"},
    "f63166f13e194cc79fe9170687720de3":{
      "scriptId":"u9"},
    "e17a95aab7c3497d9381ddd083fd9414":{
      "scriptId":"u10"},
    "63f0d7885de7435cb5527707126fd9ad":{
      "scriptId":"u11",
      "6b310f0e678d48b181949d89b0277be7":{
        "scriptId":"u12"},
      "d28d8d8c55ed447eadfd69e7a6782e22":{
        "scriptId":"u13"},
      "078f939cda994065a7d80d7a3f8327aa":{
        "scriptId":"u14"},
      "7c6c09e7e0684ef9a0f20d7159a8da17":{
        "scriptId":"u15"},
      "56399286ce8943e98036cdddf0c0027f":{
        "scriptId":"u16"},
      "206a19eb311f41b2a8d8a4fa60795674":{
        "scriptId":"u17"},
      "122a1594a7a24844882178dd2d2a300b":{
        "scriptId":"u18"},
      "3ee0334c4e084108b37ffbd6009f2fea":{
        "scriptId":"u19"},
      "8fb898143df2461fa5f60a2d6f71065e":{
        "scriptId":"u20"},
      "5b8fcdc760b548a29e70e88b8be2d8e4":{
        "scriptId":"u21"},
      "253a47ab0b284e3f98b0e6d849641899":{
        "scriptId":"u22"},
      "8bd318c93aa14e188f863643487752d9":{
        "scriptId":"u23"}},
    "7c976bb0f82441778193622c59e986af":{
      "scriptId":"u24"},
    "58c0204cf9954b8c8f0d6ac90e6b2b5c":{
      "scriptId":"u25"},
    "d8bb0cf4b9bb44b7a1b4efe150070474":{
      "scriptId":"u26"},
    "f4f1d21226ff47abbb70e682c5b031d3":{
      "scriptId":"u27"},
    "2f7e4a7566d84b61b32849239e7223c1":{
      "scriptId":"u28"},
    "68c1b06243b3455eb3eb2cd1d789be63":{
      "scriptId":"u29",
      "f5e075e6b0c24551a3d2f27b548547fc":{
        "scriptId":"u30"},
      "e89f87283be34826b9370e9126a4599c":{
        "scriptId":"u31"},
      "1b26c5d35c984f4fa388018f1868d0d3":{
        "scriptId":"u32"},
      "38ab782b63834a108f4fb89061ef1465":{
        "scriptId":"u33"},
      "406cc4bbea764710a287d4923294d571":{
        "scriptId":"u34"},
      "de28fc7bce484ddcae9214751084ab26":{
        "scriptId":"u35"},
      "c731a6f6d5144c75a64db63c3a6dd892":{
        "scriptId":"u36"},
      "83c9629b25b04e7e8f45d4da6c1e1138":{
        "scriptId":"u37"},
      "15d3b2509dbd4086bd8f71497eaa8120":{
        "scriptId":"u38"},
      "3228d0d8a30e498abe7309865cccba46":{
        "scriptId":"u39"}},
    "a4a58855e5574443926ac5c7e89d3d45":{
      "scriptId":"u40"},
    "7425514ceee14557b8d462720da301c4":{
      "scriptId":"u41"},
    "50f819b6f5954402a312a449006f46a6":{
      "scriptId":"u42"},
    "07ae5672786b45bbb4287fc64faa5c5c":{
      "scriptId":"u43"},
    "554f539ac3f4401c8612a5741712d63e":{
      "scriptId":"u44"},
    "a42670d8ee404c78a59b826d3f3cb529":{
      "scriptId":"u45"},
    "93cad69683a24b05a89b9831dd997f32":{
      "scriptId":"u46"},
    "4627ee06547b4f119a0470d78953e763":{
      "scriptId":"u47"},
    "36c676fe731648f3a6df698a1fc87325":{
      "scriptId":"u48"},
    "0ff86e2472b04b5a9059d79363377be8":{
      "scriptId":"u49"},
    "fb922a10a2884a72befd8d934fcc5039":{
      "scriptId":"u50"},
    "ef54fdbf844642758f8cf77b1a2459f1":{
      "scriptId":"u51"},
    "334820ee5bd84eecb95102d4c5e95e0f":{
      "scriptId":"u52"},
    "674dcae41e054573bb77c8454174e735":{
      "scriptId":"u53"},
    "ea24e97a10854781931996a5e41acbd6":{
      "scriptId":"u54"},
    "77889d89331147f0881b086a331dfb2d":{
      "scriptId":"u55"},
    "8289e06082004c46a0e5c2fc66e8b671":{
      "scriptId":"u56"},
    "6b3de90fe3b640c383a999dcf0905866":{
      "scriptId":"u57"},
    "037a85f485c949ef9c7238a0809456d0":{
      "scriptId":"u58"},
    "69856389fbfa4ecd8a77909adf63617d":{
      "scriptId":"u59"},
    "a61ab9a2d2b048aba236af380dcfdce6":{
      "scriptId":"u60"},
    "ad983f1c14b04c9f93e91fcffe8a2c7b":{
      "scriptId":"u61"},
    "5ab0d594e35040628e4ceec5f64e0077":{
      "scriptId":"u62"},
    "fda0c05cda534d808d89af8c28b63ea3":{
      "scriptId":"u63"},
    "3090d1ec24d847a79b650b453d5fbdb5":{
      "scriptId":"u64"},
    "528d495501a14e5eac5215ca351c778c":{
      "scriptId":"u65"},
    "d4aa6ca27196432bbbb98247589a8ac3":{
      "scriptId":"u66"},
    "01d9695d69634a7780c03c79e6e4d2b4":{
      "scriptId":"u67"},
    "bb0536a7dba44cf3a803e815eaf751c3":{
      "scriptId":"u68"},
    "e6f66ec547574517a477e31e4c6a9e40":{
      "scriptId":"u69"},
    "1a08b85cf96c4870ab3f6ce254b556d7":{
      "scriptId":"u70"},
    "886bbbc33f824361a69b7a02552a7fe0":{
      "scriptId":"u71"},
    "832b95d2ba704a849ff7a2e7e094910e":{
      "scriptId":"u72"},
    "e613d673358549548bef7b76db86c095":{
      "scriptId":"u73"},
    "0e16438edef84820835a9ef824202b0f":{
      "scriptId":"u74"},
    "f4aae83bfaf345d38a83e2c9b19799cd":{
      "scriptId":"u75"},
    "3ab45d1cbb904b63b65278dd69a84faa":{
      "scriptId":"u76"},
    "2d1eabfeee8e4e78ba49fb7574bdac78":{
      "scriptId":"u77"},
    "c60dd4e00fe248e4b4e414ec29acce52":{
      "scriptId":"u78"},
    "25b65fd05143459385b2e3a93ab9be15":{
      "scriptId":"u79"},
    "cda61c5d560e4a998a77229a9690ec98":{
      "scriptId":"u80"},
    "1747d07b855b48bdab1d4c19328ef0b7":{
      "scriptId":"u81"},
    "1f65d1c6219b4889b4809883d69cc4b8":{
      "scriptId":"u82"},
    "6662f1bfda3644e095c998667bbbb88d":{
      "scriptId":"u83"},
    "674d38d29af1462e99a437f98db95253":{
      "scriptId":"u84"},
    "b1c368974418420793f941fc1d68b489":{
      "scriptId":"u85"},
    "b4cb0f6a95c84bda8d297d6a2b2aacde":{
      "scriptId":"u86"},
    "b3b02a3f3b774f9a8e66d4d8b3566b76":{
      "scriptId":"u87"},
    "29d6d39ff2eb4300b6960b35cc9adbd3":{
      "scriptId":"u88"},
    "45f91bc248ff404cb05335a16abc2a19":{
      "scriptId":"u89"},
    "f1fdc65aa95148cb8c121be910465e9c":{
      "scriptId":"u90"},
    "781f05cb7ece4bcf85ba3491a792e62f":{
      "scriptId":"u91"},
    "3efcb3f930684036b25f2671f789c96a":{
      "scriptId":"u92"},
    "696c867a9b3f4919bec169f7b9409f16":{
      "scriptId":"u93"},
    "6906624d942740c8a29a600eeffee633":{
      "scriptId":"u94"}}});