$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1470576744440.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"3f41103d0e3d42e0beba017e6ef0d95e",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89874964bb5c4d1ab813422d91fd2a62",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":145},
            "size":{
              "width":479,
              "height":278}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6beffe4f8ec4f74b7298c6b0eecd9e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":145},
                "size":{
                  "width":479,
                  "height":278}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "89874964bb5c4d1ab813422d91fd2a62":{
      "scriptId":"u0"},
    "a6beffe4f8ec4f74b7298c6b0eecd9e4":{
      "scriptId":"u1"}}});