$axure.loadCurrentPage({
  "url":"编辑购物车.html",
  "generationDate":new Date(1470576991626.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"68006b6d3cc84c46a5e7cdf9b6cc4119",
    "type":"Axure:Page",
    "name":"编辑购物车",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fc845670791b4cc18a587ba81bc57ffb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":1085},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36d06792a41b4973989db180a4c20479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":1085},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物清单/u0.png"}},
{
          "id":"0ff24f1594094ac5b2fe8d82c27b26f4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":335}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"88bcfef7889d46dda581b2f781ada994",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":335}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"1263f55633944b2da52a0cc23c358f1c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":295},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u42_line.png"}},
{
          "id":"83abc5ae663d4405b24c2470796cc2ca",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":295},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u42_line.png"}},
{
          "id":"4b3b302850e94df1abbc052d3c8fbfae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":290},
            "size":{
              "width":120,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d8b61c0e43f4ad5b023fabae0215b8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":290},
                "size":{
                  "width":120,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef429f85eba741828f7638696027b891",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":645}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"6bc6e8fb323b44c4a528d531e396f440",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":645}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"68bb10c4871d40b8b35e85d9e3eb8166",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":970},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u70_line.png"}},
{
          "id":"16b2d9b5419d4022845acc793a6dbe80",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":970},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u70_line.png"}},
{
          "id":"bb1b2028b5fc4462850237fce029e893",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":20,
              "y":965},
            "size":{
              "width":460,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44c9fd9f97a34b90a9e7ffc8261d1c60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":20,
                  "y":965},
                "size":{
                  "width":460,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4daf25c7314b42e9bbe7a3cd5efe68de",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"47acccc1dfef41689db501d105ee8318"},
{
          "id":"6bc36430a290464b88d517cdd374c511",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":170},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"227cc505ad4b468da7a52bfe87ff3b67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":170},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u353.png"}},
{
          "id":"9dd8bf5f72044573b83a50b718037514",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1522164d9222454fa80a4eeae74da5be",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8952dc21868e402390582f056cc00b97",
                  "label":"",
                  "parentDynamicPanel":"9dd8bf5f72044573b83a50b718037514",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5d4b0c34bb446e8999dd22e758f44d3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9dd8bf5f72044573b83a50b718037514",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"c634bf50e58745e5b22cd6da379a1c29",
                  "label":"",
                  "parentDynamicPanel":"9dd8bf5f72044573b83a50b718037514",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9ff8b35cbf394dcbadd1f67480fee2c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9dd8bf5f72044573b83a50b718037514",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e9f0a5202314433b98f230578a40808a",
                  "label":"",
                  "parentDynamicPanel":"9dd8bf5f72044573b83a50b718037514",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
                  "id":"3afeb2cad6a54def9cf5b86704e2df8d",
                  "label":"",
                  "parentDynamicPanel":"9dd8bf5f72044573b83a50b718037514",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":410,
                      "y":15},
                    "size":{
                      "width":50,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"11ad42f594ff4f1fa570dd21c979e8ee",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9dd8bf5f72044573b83a50b718037514",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":410,
                          "y":15},
                        "size":{
                          "width":50,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 购物清单",
                              "target":{
                                "targetType":"page",
                                "url":"购物清单.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"78735f0ffe40471f946bfef966548167",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":60,
              "y":180},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2bc6a3a5a6a48cb9007d62f351b9c3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":60,
                  "y":180},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物清单/u71.png"}},
{
          "id":"159f8f2774bb462698cafb15afe71f6f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"22px",
            "location":{
              "x":150,
              "y":180},
            "size":{
              "width":330,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cda335aae0af4c81a831b3bd1fd2c5b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"22px",
                "location":{
                  "x":150,
                  "y":180},
                "size":{
                  "width":330,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ad3dcb35d974466b4b5094d3773cd56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":150,
              "y":234},
            "size":{
              "width":130,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f80b9bf622b44d3da1fc2e02073df463",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":150,
                  "y":234},
                "size":{
                  "width":130,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb6a7c9a6c6e44d0b3eeccde70112059",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":208},
            "size":{
              "width":30,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f18487ac403c450ea0fe3933c813aa19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":208},
                "size":{
                  "width":30,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d35997c8df6444798739d011374862fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":330,
              "y":229},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28619127eb2242d2b6c95f60bde6245b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":330,
                  "y":229},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u361.png"}},
{
          "id":"451b3c9cf8ab41b289f5d5be27e8fcf2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":365,
              "y":230},
            "size":{
              "width":50,
              "height":28}},
          "adaptiveStyles":{
},
          "placeholderText":"1"},
{
          "id":"e2d26c78cd304ab7916fb6b77d71d481",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "lineSpacing":"22px",
            "location":{
              "x":338,
              "y":234},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6045b590934469bb2a16998692a6b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "lineSpacing":"22px",
                "location":{
                  "x":338,
                  "y":234},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"056db576535e4376928456d7e17572de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"22px",
            "location":{
              "x":423,
              "y":234},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64d6dc7aa05f48249579f1fc44cd69b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"22px",
                "location":{
                  "x":423,
                  "y":234},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a3befdf669d34d418218c35278290bbd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":360,
              "y":230},
            "size":{
              "width":10,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u368_line.png"}},
{
          "id":"0ac5186f901544efae835669b1f5164c",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":230},
            "size":{
              "width":10,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF666666}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u369_line.png"}},
{
          "id":"07a1bcb4c5b641f590ac59bbf320cd67",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":1025},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"bbdde45b49f749acbef958f6bee05d21",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"555054efd750433c8dafc3ad316454a3",
                  "label":"",
                  "parentDynamicPanel":"07a1bcb4c5b641f590ac59bbf320cd67",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "size":{
                      "width":480,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d65446f5f57f4711b9d1ea6a0171e430",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"07a1bcb4c5b641f590ac59bbf320cd67",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "size":{
                          "width":480,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u465.png"}},
{
                  "id":"bfc4f877b26c4928b2fbeb2134e4214f",
                  "label":"",
                  "parentDynamicPanel":"07a1bcb4c5b641f590ac59bbf320cd67",
                  "panelIndex":0,
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":20,
                      "y":22},
                    "size":{
                      "width":100,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88b575f6d7fa4d53a326027e5147a878",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"07a1bcb4c5b641f590ac59bbf320cd67",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":20,
                          "y":22},
                        "size":{
                          "width":100,
                          "height":16}},
                      "adaptiveStyles":{
}}]},
{
                  "id":"5c46bf8e78b84d57b6fbf911b3f55abc",
                  "label":"",
                  "parentDynamicPanel":"07a1bcb4c5b641f590ac59bbf320cd67",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "location":{
                      "x":340,
                      "y":0},
                    "size":{
                      "width":140,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF990000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51f0cbdbcc1c424493849b77e444533d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"07a1bcb4c5b641f590ac59bbf320cd67",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "location":{
                          "x":340,
                          "y":0},
                        "size":{
                          "width":140,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF990000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 默认页",
                              "target":{
                                "targetType":"page",
                                "url":"默认页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/购物清单/u115.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "e233cf1f8b7a43da9b4130a7ee7963e4":{
      "packageId":"e233cf1f8b7a43da9b4130a7ee7963e4",
      "type":"Axure:Master",
      "name":"产品模块",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"19aa459432d34ba1a480d27dff6a8b55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "size":{
                "width":225,
                "height":300},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8eb084c43534ec9ad5dd7379a6b8d21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "size":{
                    "width":225,
                    "height":300},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u211.png",
              "normal~":"images/手机外观效果/u211.png",
              "normal~":"images/手机外观效果/u211.png",
              "normal~":"images/手机外观效果/u211.png"}},
{
            "id":"c58403d5ffe84b3cafc0a406f2422a7e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":10,
                "y":200},
              "size":{
                "width":205,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"268120e9977b4ecba9091eee1afda6e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":10,
                    "y":200},
                  "size":{
                    "width":205,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品详细",
                        "target":{
                          "targetType":"page",
                          "url":"产品详细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7f9a58d68d2345c0855a95d54de98bcf",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":30,
                "y":30},
              "size":{
                "width":160,
                "height":160}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a10cce0c0bca467eb3e1f3638b8bb751",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":30,
                    "y":30},
                  "size":{
                    "width":160,
                    "height":160}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品详细",
                        "target":{
                          "targetType":"page",
                          "url":"产品详细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u215.png",
              "normal~":"images/手机外观效果/u215.png",
              "normal~":"images/手机外观效果/u215.png",
              "normal~":"images/手机外观效果/u215.png"}},
{
            "id":"13ba846806714f0a8e7f25e6b65061bb",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":240},
              "size":{
                "width":205,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png"}},
{
            "id":"bae5226a8e014bed98634919b29d554c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF990000,
                "opacity":1},
              "location":{
                "x":10,
                "y":255},
              "size":{
                "width":205,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ca0a7d7619c645f19eb35bf7dd9dd523",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF990000,
                    "opacity":1},
                  "location":{
                    "x":10,
                    "y":255},
                  "size":{
                    "width":205,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f7783e454f946e191c3fb64dff07c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":10,
                "y":280},
              "size":{
                "width":205,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f6e93e335bd4f91bbee592acd212a8b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":10,
                    "y":280},
                  "size":{
                    "width":205,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}},
    "47acccc1dfef41689db501d105ee8318":{
      "packageId":"47acccc1dfef41689db501d105ee8318",
      "type":"Axure:Master",
      "name":"购物车清单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"d7c9eaad367241ba86c60fa66b39275d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "size":{
                "width":480,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f05a197eb384d23a955223b6e59c15d",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "size":{
                    "width":480,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u353.png"}},
{
            "id":"f696bea9656344d8b7a87b59d62d8eb9",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":50,
                "y":10},
              "size":{
                "width":80,
                "height":80}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"df4fb48d738f41f6ab7da0d4e5c3bb2c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":50,
                    "y":10},
                  "size":{
                    "width":80,
                    "height":80}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/购物清单/u71.png"}},
{
            "id":"4f87b320e4cd46bf9731515ac5bff3a1",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "lineSpacing":"22px",
              "location":{
                "x":140,
                "y":10},
              "size":{
                "width":330,
                "height":44}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f11d06652c6b4017bda0f019dd626401",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "lineSpacing":"22px",
                  "location":{
                    "x":140,
                    "y":10},
                  "size":{
                    "width":330,
                    "height":44}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"2d5511c7beb741209eb315a659061f59",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFF0000,
                "opacity":1},
              "location":{
                "x":140,
                "y":64},
              "size":{
                "width":130,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"2d957695f2d44df89bd43336bd6a6ed5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1},
                  "location":{
                    "x":140,
                    "y":64},
                  "size":{
                    "width":130,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"d74dd000974148bebef7761d47deeb65",
            "label":"",
            "type":"checkbox",
            "styleType":"checkbox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":20,
                "y":38},
              "size":{
                "width":30,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3c69bfad107c4230a56fb13c6e5af383",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":20,
                    "y":38},
                  "size":{
                    "width":30,
                    "height":16}},
                "adaptiveStyles":{
}}]},
{
            "id":"c211ea5f74394416ae0fb1f4941f690c",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":320,
                "y":59},
              "size":{
                "width":120,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC},
              "cornerRadiusTopLeft":"2"},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"0d3bbefd5f7c4804850e18b46f2722c5",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":320,
                    "y":59},
                  "size":{
                    "width":120,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC},
                  "cornerRadiusTopLeft":"2"},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u361.png"}},
{
            "id":"c228d43c5f9c4c419f65d3ef8e2d8bf2",
            "label":"",
            "type":"textBox",
            "styleType":"textBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "horizontalAlignment":"center",
              "location":{
                "x":355,
                "y":60},
              "size":{
                "width":50,
                "height":28}},
            "adaptiveStyles":{
},
            "placeholderText":"1"},
{
            "id":"dab8de35b5814c6db2af839546b64961",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC,
                "opacity":1},
              "lineSpacing":"22px",
              "location":{
                "x":328,
                "y":64},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"810711648c184511a988773617754d6e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC,
                    "opacity":1},
                  "lineSpacing":"22px",
                  "location":{
                    "x":328,
                    "y":64},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0a4879fe856e4265ae8eb9872d4fc6cb",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "horizontalAlignment":"center",
              "verticalAlignment":"middle",
              "lineSpacing":"22px",
              "location":{
                "x":413,
                "y":64},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c52250a51d8c45cdb712ec612f7fe2a4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "horizontalAlignment":"center",
                  "verticalAlignment":"middle",
                  "lineSpacing":"22px",
                  "location":{
                    "x":413,
                    "y":64},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"99be841d066641a3af2aa68f174ee6a9",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":350,
                "y":60},
              "size":{
                "width":10,
                "height":28},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u368_line.png"}},
{
            "id":"28f01348b45c470593dc3bf7398f6063",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "location":{
                "x":400,
                "y":60},
              "size":{
                "width":10,
                "height":28},
              "borderFill":{
                "fillType":"solid",
                "color":0xFF666666}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u369_line.png"}}]}},
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "fc845670791b4cc18a587ba81bc57ffb":{
      "scriptId":"u0"},
    "36d06792a41b4973989db180a4c20479":{
      "scriptId":"u1"},
    "0ff24f1594094ac5b2fe8d82c27b26f4":{
      "scriptId":"u2",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u3"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u4"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u5"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u6"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u7"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u8"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u9"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u10"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u11"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u12"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u13"}},
    "88bcfef7889d46dda581b2f781ada994":{
      "scriptId":"u14",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u15"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u16"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u17"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u18"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u19"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u20"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u21"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u22"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u23"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u24"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u25"}},
    "1263f55633944b2da52a0cc23c358f1c":{
      "scriptId":"u26"},
    "83abc5ae663d4405b24c2470796cc2ca":{
      "scriptId":"u27"},
    "4b3b302850e94df1abbc052d3c8fbfae":{
      "scriptId":"u28"},
    "3d8b61c0e43f4ad5b023fabae0215b8e":{
      "scriptId":"u29"},
    "ef429f85eba741828f7638696027b891":{
      "scriptId":"u30",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u31"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u32"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u33"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u34"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u35"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u36"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u37"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u38"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u39"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u40"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u41"}},
    "6bc6e8fb323b44c4a528d531e396f440":{
      "scriptId":"u42",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u43"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u44"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u45"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u46"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u47"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u48"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u49"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u50"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u51"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u52"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u53"}},
    "68bb10c4871d40b8b35e85d9e3eb8166":{
      "scriptId":"u54"},
    "16b2d9b5419d4022845acc793a6dbe80":{
      "scriptId":"u55"},
    "bb1b2028b5fc4462850237fce029e893":{
      "scriptId":"u56"},
    "44c9fd9f97a34b90a9e7ffc8261d1c60":{
      "scriptId":"u57"},
    "4daf25c7314b42e9bbe7a3cd5efe68de":{
      "scriptId":"u58",
      "d7c9eaad367241ba86c60fa66b39275d":{
        "scriptId":"u59"},
      "8f05a197eb384d23a955223b6e59c15d":{
        "scriptId":"u60"},
      "f696bea9656344d8b7a87b59d62d8eb9":{
        "scriptId":"u61"},
      "df4fb48d738f41f6ab7da0d4e5c3bb2c":{
        "scriptId":"u62"},
      "4f87b320e4cd46bf9731515ac5bff3a1":{
        "scriptId":"u63"},
      "f11d06652c6b4017bda0f019dd626401":{
        "scriptId":"u64"},
      "2d5511c7beb741209eb315a659061f59":{
        "scriptId":"u65"},
      "2d957695f2d44df89bd43336bd6a6ed5":{
        "scriptId":"u66"},
      "d74dd000974148bebef7761d47deeb65":{
        "scriptId":"u67"},
      "3c69bfad107c4230a56fb13c6e5af383":{
        "scriptId":"u68"},
      "c211ea5f74394416ae0fb1f4941f690c":{
        "scriptId":"u69"},
      "0d3bbefd5f7c4804850e18b46f2722c5":{
        "scriptId":"u70"},
      "c228d43c5f9c4c419f65d3ef8e2d8bf2":{
        "scriptId":"u71"},
      "dab8de35b5814c6db2af839546b64961":{
        "scriptId":"u72"},
      "810711648c184511a988773617754d6e":{
        "scriptId":"u73"},
      "0a4879fe856e4265ae8eb9872d4fc6cb":{
        "scriptId":"u74"},
      "c52250a51d8c45cdb712ec612f7fe2a4":{
        "scriptId":"u75"},
      "99be841d066641a3af2aa68f174ee6a9":{
        "scriptId":"u76"},
      "28f01348b45c470593dc3bf7398f6063":{
        "scriptId":"u77"}},
    "6bc36430a290464b88d517cdd374c511":{
      "scriptId":"u78"},
    "227cc505ad4b468da7a52bfe87ff3b67":{
      "scriptId":"u79"},
    "9dd8bf5f72044573b83a50b718037514":{
      "scriptId":"u80"},
    "8952dc21868e402390582f056cc00b97":{
      "scriptId":"u81"},
    "e5d4b0c34bb446e8999dd22e758f44d3":{
      "scriptId":"u82"},
    "c634bf50e58745e5b22cd6da379a1c29":{
      "scriptId":"u83"},
    "9ff8b35cbf394dcbadd1f67480fee2c2":{
      "scriptId":"u84"},
    "e9f0a5202314433b98f230578a40808a":{
      "scriptId":"u85",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u86"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u87"}},
    "3afeb2cad6a54def9cf5b86704e2df8d":{
      "scriptId":"u88"},
    "11ad42f594ff4f1fa570dd21c979e8ee":{
      "scriptId":"u89"},
    "78735f0ffe40471f946bfef966548167":{
      "scriptId":"u90"},
    "a2bc6a3a5a6a48cb9007d62f351b9c3b":{
      "scriptId":"u91"},
    "159f8f2774bb462698cafb15afe71f6f":{
      "scriptId":"u92"},
    "cda335aae0af4c81a831b3bd1fd2c5b0":{
      "scriptId":"u93"},
    "0ad3dcb35d974466b4b5094d3773cd56":{
      "scriptId":"u94"},
    "f80b9bf622b44d3da1fc2e02073df463":{
      "scriptId":"u95"},
    "bb6a7c9a6c6e44d0b3eeccde70112059":{
      "scriptId":"u96"},
    "f18487ac403c450ea0fe3933c813aa19":{
      "scriptId":"u97"},
    "d35997c8df6444798739d011374862fd":{
      "scriptId":"u98"},
    "28619127eb2242d2b6c95f60bde6245b":{
      "scriptId":"u99"},
    "451b3c9cf8ab41b289f5d5be27e8fcf2":{
      "scriptId":"u100"},
    "e2d26c78cd304ab7916fb6b77d71d481":{
      "scriptId":"u101"},
    "c6045b590934469bb2a16998692a6b05":{
      "scriptId":"u102"},
    "056db576535e4376928456d7e17572de":{
      "scriptId":"u103"},
    "64d6dc7aa05f48249579f1fc44cd69b2":{
      "scriptId":"u104"},
    "a3befdf669d34d418218c35278290bbd":{
      "scriptId":"u105"},
    "0ac5186f901544efae835669b1f5164c":{
      "scriptId":"u106"},
    "07a1bcb4c5b641f590ac59bbf320cd67":{
      "scriptId":"u107"},
    "555054efd750433c8dafc3ad316454a3":{
      "scriptId":"u108"},
    "d65446f5f57f4711b9d1ea6a0171e430":{
      "scriptId":"u109"},
    "bfc4f877b26c4928b2fbeb2134e4214f":{
      "scriptId":"u110"},
    "88b575f6d7fa4d53a326027e5147a878":{
      "scriptId":"u111"},
    "5c46bf8e78b84d57b6fbf911b3f55abc":{
      "scriptId":"u112"},
    "51f0cbdbcc1c424493849b77e444533d":{
      "scriptId":"u113"}}});