$axure.loadCurrentPage({
  "url":"我的工作.html",
  "generationDate":new Date(1470577060832.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1b742bcd171b43b5b165d4e690ae0ac8",
    "type":"Axure:Page",
    "name":"我的工作",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"70c3bc5464fb445ab0da80faa1939fd1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f75a8ff5f2e42debc4e839435dc190e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的业务/u0.png"}},
{
          "id":"35ae188814fd4150b59337695077ad11",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd14d27fa1a41c39a860f37a21d2fa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/重置密码/u6.png"}},
{
          "id":"c3e841ec0a1443ed9efc91d5fc3a1537",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"c2054eec24dc42eda2dd276e2d2e4a49",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"69aae4bffdd24bf38514380a35d05c3d",
                  "label":"",
                  "parentDynamicPanel":"c3e841ec0a1443ed9efc91d5fc3a1537",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c22aa0128fb84034bca8af0764104f92",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c3e841ec0a1443ed9efc91d5fc3a1537",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录页/u2.png"}},
{
                  "id":"e02468e9509c46f488bc7a6500ace199",
                  "label":"",
                  "parentDynamicPanel":"c3e841ec0a1443ed9efc91d5fc3a1537",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
                  "id":"259a666cce5d4b52867de0c6c0439f8b",
                  "label":"",
                  "parentDynamicPanel":"c3e841ec0a1443ed9efc91d5fc3a1537",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ddd9b6903bc64e8eb859911f63a4d51d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c3e841ec0a1443ed9efc91d5fc3a1537",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"573dc243e79947dfa263415a8295b7a9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":110},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c09313d701dc41a085347c036d00e793",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":110},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/重置密码/u6.png"}},
{
          "id":"e722d7546ded46878bc17e9478c28254",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":123},
            "size":{
              "width":315,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11432584f40f42d484fa106583ed6a92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":20,
                  "y":123},
                "size":{
                  "width":315,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a397adb18918487281cb51a7a17ae6fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":160},
            "size":{
              "width":480,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e63b64f9212242a498e57f85eea478d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":160},
                "size":{
                  "width":480,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作/u16.png"}},
{
          "id":"7374fdeb462a4f0bb693f5a96719be2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b27ee86654434dacb1affdcbae41074c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":240},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u6.png"}},
{
          "id":"79251de7470f4453be2332ca0bef6760",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":275},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页/u10_line.png"}},
{
          "id":"90d91b1adc6645f094099f0bd8cb8b63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":390,
              "y":125},
            "size":{
              "width":90,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca91ca8831c54140b5c29f8d7f212e09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":125},
                "size":{
                  "width":90,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82865fd591db4e3da6e3cf6baf491f74",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8ff685ee7a146f69b4f7898d9045f2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作/u23.png"}},
{
          "id":"32287efb850b44388e6b3a83cb8eee20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"22px",
            "location":{
              "x":90,
              "y":170},
            "size":{
              "width":260,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d41c234b1d3240308d985be072238a9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"22px",
                "location":{
                  "x":90,
                  "y":170},
                "size":{
                  "width":260,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"467460523698476e9fb80b0c1716e24c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":350,
              "y":170},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b53919595be4828a8bd710f668e719e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":350,
                  "y":170},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f584ac917af249b68a36f01124cb5ec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":250,
              "y":250},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f130b7c69c8f43a0ba34a7df4c846aa5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":250,
                  "y":250},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c246fa1633444fdb615cc7fedb79557",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":360,
              "y":290},
            "size":{
              "width":120,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50edc60efb794422a8a1ebb2dbefedf3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":360,
                  "y":290},
                "size":{
                  "width":120,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作/u31.png"}},
{
          "id":"744d6b7b2d074befa66f3ade5edbaaf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":350},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35170320eecf4726b57f425dcb9d2bdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":350},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/重置密码/u6.png"}},
{
          "id":"8482959f94af481fb28a442aaecaa78a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":20,
              "y":363},
            "size":{
              "width":315,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee9b22f33e448ddafc7d37299b69de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":20,
                  "y":363},
                "size":{
                  "width":315,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c83a9a4d16144358b97bf3e5c993c34",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":50}},
          "adaptiveStyles":{
},
          "masterId":"ffb7a7aa106b458084f1b76b36ed1b1e"},
{
          "id":"d0ebdf85e18140daa3433aea184bdcf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":400},
            "size":{
              "width":480,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f48cf90158094b318de8c2813608e504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":400},
                "size":{
                  "width":480,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作/u16.png"}},
{
          "id":"983ef2787e9b4996a8ce50544c5fd79c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":480},
            "size":{
              "width":480,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bf773733a1d489994d94549d21efd6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":480},
                "size":{
                  "width":480,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作/u46.png"}},
{
          "id":"019fa201ffd741998721e0c9c3041149",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":390,
              "y":365},
            "size":{
              "width":90,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a438ab4083041468b1a4704fb504c0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":390,
                  "y":365},
                "size":{
                  "width":90,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c424f9bcb09404dbeed521436a34f58",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":410},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0db42dc8e3484973a1877be599c73c52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":410},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的工作/u23.png"}},
{
          "id":"d4f40641e7b843cfaa9c7cb5124d2ae3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"22px",
            "location":{
              "x":90,
              "y":410},
            "size":{
              "width":260,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"049213eff7174244889eab81b83d747f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"22px",
                "location":{
                  "x":90,
                  "y":410},
                "size":{
                  "width":260,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69074d8485b9489f89b6d2679a79013f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":350,
              "y":410},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e12e1e36c854a2caf4bdfbe5d564a31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":350,
                  "y":410},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab246039038e45959bf41b77c56a2c8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":250,
              "y":490},
            "size":{
              "width":230,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a47d33ee7ed3437fac0f1d26009538d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":250,
                  "y":490},
                "size":{
                  "width":230,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "ffb7a7aa106b458084f1b76b36ed1b1e":{
      "packageId":"ffb7a7aa106b458084f1b76b36ed1b1e",
      "type":"Axure:Master",
      "name":"我的工作菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f761af36da1e40d0ac96e69511da1bb6",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":320,
                "y":0},
              "size":{
                "width":160,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f4b307af55d94800ac24142db35e18fd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":320,
                    "y":0},
                  "size":{
                    "width":160,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的工作-已完成",
                        "target":{
                          "targetType":"page",
                          "url":"我的工作-已完成.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"a88b441ce1244acbb797e37b9c72ac33",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "paddingTop":"0",
              "paddingBottom":"0",
              "location":{
                "x":160,
                "y":0},
              "size":{
                "width":160,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f9df1fa539b4121808a94ed4fa11f50",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "location":{
                    "x":160,
                    "y":0},
                  "size":{
                    "width":160,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的工作-待完成",
                        "target":{
                          "targetType":"page",
                          "url":"我的工作-待完成.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}},
{
            "id":"1dc2b56e8b504348af0fde2ef23fd56d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF666666,
                "opacity":1},
              "stateStyles":{
                "mouseOver":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "fill":{
                "fillType":"solid",
                "color":0xFFFFFF},
              "paddingTop":"0",
              "paddingBottom":"0",
              "size":{
                "width":160,
                "height":50},
              "borderWidth":"-1",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ceb87ca9d36e4fd48a885fef6177efab",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF666666,
                    "opacity":1},
                  "stateStyles":{
                    "mouseOver":{
                      "fontName":"'Applied Font Regular', 'Applied Font'",
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFFFF},
                  "paddingTop":"0",
                  "paddingBottom":"0",
                  "size":{
                    "width":160,
                    "height":50},
                  "borderWidth":"-1",
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的工作",
                        "target":{
                          "targetType":"page",
                          "url":"我的工作.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "70c3bc5464fb445ab0da80faa1939fd1":{
      "scriptId":"u0"},
    "8f75a8ff5f2e42debc4e839435dc190e":{
      "scriptId":"u1"},
    "35ae188814fd4150b59337695077ad11":{
      "scriptId":"u2"},
    "0fd14d27fa1a41c39a860f37a21d2fa4":{
      "scriptId":"u3"},
    "c3e841ec0a1443ed9efc91d5fc3a1537":{
      "scriptId":"u4"},
    "69aae4bffdd24bf38514380a35d05c3d":{
      "scriptId":"u5"},
    "c22aa0128fb84034bca8af0764104f92":{
      "scriptId":"u6"},
    "e02468e9509c46f488bc7a6500ace199":{
      "scriptId":"u7",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u8"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u9"}},
    "259a666cce5d4b52867de0c6c0439f8b":{
      "scriptId":"u10"},
    "ddd9b6903bc64e8eb859911f63a4d51d":{
      "scriptId":"u11"},
    "573dc243e79947dfa263415a8295b7a9":{
      "scriptId":"u12"},
    "c09313d701dc41a085347c036d00e793":{
      "scriptId":"u13"},
    "e722d7546ded46878bc17e9478c28254":{
      "scriptId":"u14"},
    "11432584f40f42d484fa106583ed6a92":{
      "scriptId":"u15"},
    "a397adb18918487281cb51a7a17ae6fc":{
      "scriptId":"u16"},
    "e63b64f9212242a498e57f85eea478d9":{
      "scriptId":"u17"},
    "7374fdeb462a4f0bb693f5a96719be2f":{
      "scriptId":"u18"},
    "b27ee86654434dacb1affdcbae41074c":{
      "scriptId":"u19"},
    "79251de7470f4453be2332ca0bef6760":{
      "scriptId":"u20"},
    "90d91b1adc6645f094099f0bd8cb8b63":{
      "scriptId":"u21"},
    "ca91ca8831c54140b5c29f8d7f212e09":{
      "scriptId":"u22"},
    "82865fd591db4e3da6e3cf6baf491f74":{
      "scriptId":"u23"},
    "c8ff685ee7a146f69b4f7898d9045f2a":{
      "scriptId":"u24"},
    "32287efb850b44388e6b3a83cb8eee20":{
      "scriptId":"u25"},
    "d41c234b1d3240308d985be072238a9e":{
      "scriptId":"u26"},
    "467460523698476e9fb80b0c1716e24c":{
      "scriptId":"u27"},
    "8b53919595be4828a8bd710f668e719e":{
      "scriptId":"u28"},
    "f584ac917af249b68a36f01124cb5ec7":{
      "scriptId":"u29"},
    "f130b7c69c8f43a0ba34a7df4c846aa5":{
      "scriptId":"u30"},
    "0c246fa1633444fdb615cc7fedb79557":{
      "scriptId":"u31"},
    "50edc60efb794422a8a1ebb2dbefedf3":{
      "scriptId":"u32"},
    "744d6b7b2d074befa66f3ade5edbaaf0":{
      "scriptId":"u33"},
    "35170320eecf4726b57f425dcb9d2bdf":{
      "scriptId":"u34"},
    "8482959f94af481fb28a442aaecaa78a":{
      "scriptId":"u35"},
    "5ee9b22f33e448ddafc7d37299b69de4":{
      "scriptId":"u36"},
    "0c83a9a4d16144358b97bf3e5c993c34":{
      "scriptId":"u37",
      "f761af36da1e40d0ac96e69511da1bb6":{
        "scriptId":"u38"},
      "f4b307af55d94800ac24142db35e18fd":{
        "scriptId":"u39"},
      "a88b441ce1244acbb797e37b9c72ac33":{
        "scriptId":"u40"},
      "8f9df1fa539b4121808a94ed4fa11f50":{
        "scriptId":"u41"},
      "1dc2b56e8b504348af0fde2ef23fd56d":{
        "scriptId":"u42"},
      "ceb87ca9d36e4fd48a885fef6177efab":{
        "scriptId":"u43"}},
    "d0ebdf85e18140daa3433aea184bdcf8":{
      "scriptId":"u44"},
    "f48cf90158094b318de8c2813608e504":{
      "scriptId":"u45"},
    "983ef2787e9b4996a8ce50544c5fd79c":{
      "scriptId":"u46"},
    "6bf773733a1d489994d94549d21efd6d":{
      "scriptId":"u47"},
    "019fa201ffd741998721e0c9c3041149":{
      "scriptId":"u48"},
    "5a438ab4083041468b1a4704fb504c0c":{
      "scriptId":"u49"},
    "0c424f9bcb09404dbeed521436a34f58":{
      "scriptId":"u50"},
    "0db42dc8e3484973a1877be599c73c52":{
      "scriptId":"u51"},
    "d4f40641e7b843cfaa9c7cb5124d2ae3":{
      "scriptId":"u52"},
    "049213eff7174244889eab81b83d747f":{
      "scriptId":"u53"},
    "69074d8485b9489f89b6d2679a79013f":{
      "scriptId":"u54"},
    "3e12e1e36c854a2caf4bdfbe5d564a31":{
      "scriptId":"u55"},
    "ab246039038e45959bf41b77c56a2c8f":{
      "scriptId":"u56"},
    "a47d33ee7ed3437fac0f1d26009538d0":{
      "scriptId":"u57"}}});