$axure.loadCurrentPage({
  "url":"填写订单.html",
  "generationDate":new Date(1470576991785.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"727f63f84e0646d9bf0c02fd75c1cf01",
    "type":"Axure:Page",
    "name":"填写订单",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"92c7de2b3633430f925bcd9bbbf5b111",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14f8bd92dd684271a29770a87e80da39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"568f9a8e236a465198e4eb3593dcc6b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":170},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c279b795d76e4e26822d2fc250952b90",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":170},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u353.png"}},
{
          "id":"8a9f6812b20647db96b1e576d6a90f38",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"62360d73acb548a7b77f8aacc1d06165",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1c7bc728bf1a4163acc0ac37c438ff2a",
                  "label":"",
                  "parentDynamicPanel":"8a9f6812b20647db96b1e576d6a90f38",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7ea218dd9929452d8fe64f0d23a3eaf4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a9f6812b20647db96b1e576d6a90f38",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"b6290b817f3f444a84b27f01086cf397",
                  "label":"",
                  "parentDynamicPanel":"8a9f6812b20647db96b1e576d6a90f38",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbf0d64a60d04d12819585eb2a43b963",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8a9f6812b20647db96b1e576d6a90f38",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"65bcdc04baa549368e3701d7b78d1e81",
                  "label":"",
                  "parentDynamicPanel":"8a9f6812b20647db96b1e576d6a90f38",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"18fc7102ae4444ed9db23e79aca527be",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":180},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"786d99e00a6441c4b1c3116351dd5634",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":180},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物清单/u71.png"}},
{
          "id":"bc473c685e2f4d6c9f3e552476290d1f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"22px",
            "location":{
              "x":110,
              "y":180},
            "size":{
              "width":260,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e93c30ee5c14fc69b5ab16e453cdc50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"22px",
                "location":{
                  "x":110,
                  "y":180},
                "size":{
                  "width":260,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d48db8ee3a94db8a3cda2977e575192",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":480,
              "height":100},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC99},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd2157b83e17459ca319d633eff72c3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":480,
                  "height":100},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC99},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写订单/u16.png"}},
{
          "id":"206108346c8c43cabf05100f49976960",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "lineSpacing":"30px",
            "location":{
              "x":30,
              "y":70},
            "size":{
              "width":270,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"172ffaf7d4e74518b9905b5baa73b7d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "lineSpacing":"30px",
                "location":{
                  "x":30,
                  "y":70},
                "size":{
                  "width":270,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"051f6d0a1a5b4d7e8ac64748fa28d9cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":300,
              "y":70},
            "size":{
              "width":150,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a09c843f0204bc7a975503ef267b18f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":300,
                  "y":70},
                "size":{
                  "width":150,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a4fafa42e8e44d2b5855b613969d59f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":430,
              "y":100},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3199f597c67c42bdad9cc1bfc50de6a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":430,
                  "y":100},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 选择地址",
                      "target":{
                        "targetType":"page",
                        "url":"选择地址.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ccd0139ee088404eaaf232b8e6ef14cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "location":{
              "x":350,
              "y":185},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1ffd4198c0148e1a777987aa1777915",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "location":{
                  "x":350,
                  "y":185},
                "size":{
                  "width":130,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"583884f200154313a420b3f92bd1d052",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":280},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d88b1269bcf491fb0dbe999b5c0eeb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":280},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"5135506732684319b8e3137123880f43",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":290},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f47bbb40e864486b4702567dbd60a09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":290},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5588c418fcd54d969c1ec27157c976b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":310,
              "y":290},
            "size":{
              "width":170,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38bcc6ef8f3a4f9b8219dbbd6681a50c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":310,
                  "y":290},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3cfb53043ae34b4ab8a3c9e6a8185095",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":340},
            "size":{
              "width":480,
              "height":80},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1638735e7c1547aa953893eca718331e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":340},
                "size":{
                  "width":480,
                  "height":80},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u439.png"}},
{
          "id":"ca45527032c04f709a8580635a83f504",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":350},
            "size":{
              "width":460,
              "height":60}},
          "adaptiveStyles":{
},
          "placeholderText":"给商家留言，限45字"},
{
          "id":"1d45efa07db44f449665620f3d1781bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":430},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8bc0a6020af4a22896b6ed126c7943d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":430},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"130baaa643c84ab0b948e66b1f39a24f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":440},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d74c1da4064f4d8aa602303d4f8993b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":440},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02581b7b82814d27a6ff4d2ce89aa3e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":370,
              "y":435},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ce37b1a3fc24704ae8194c3529de92e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":370,
                  "y":435},
                "size":{
                  "width":110,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fff1cf4c9e7940a1a88aa3ffb77e2031",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":480},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e09c3ca53ba644fd8510dba7b7170f1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":480},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"687659350d904eb59ee37e396cad81fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":490},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991d9ad384804c2d9c833d39bb646d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":490},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6bc6ca3ba12248a58efb9209cf431b96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"20px",
            "location":{
              "x":370,
              "y":485},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35297b87483341bdbae1a190223122aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"20px",
                "location":{
                  "x":370,
                  "y":485},
                "size":{
                  "width":110,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd70991721454d1a8f30825d38238c7b",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":540},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d7915427add74aadbea7ec758988f1a4",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d944b8f386384f799bebbfa652a41b02",
                  "label":"",
                  "parentDynamicPanel":"cd70991721454d1a8f30825d38238c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "size":{
                      "width":480,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d7745ec36a3476f8935824d6d57b309",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cd70991721454d1a8f30825d38238c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "size":{
                          "width":480,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u465.png"}},
{
                  "id":"aafffee62f4c4515824d7cb326b4797a",
                  "label":"",
                  "parentDynamicPanel":"cd70991721454d1a8f30825d38238c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "verticalAlignment":"middle",
                    "lineSpacing":"30px",
                    "location":{
                      "x":10,
                      "y":5},
                    "size":{
                      "width":260,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b9b48908247d4fb8a54da3c00af32851",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cd70991721454d1a8f30825d38238c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "verticalAlignment":"middle",
                        "lineSpacing":"30px",
                        "location":{
                          "x":10,
                          "y":5},
                        "size":{
                          "width":260,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f2a34f06a6ef4cfd86bcfd681e0392a0",
                  "label":"",
                  "parentDynamicPanel":"cd70991721454d1a8f30825d38238c7b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "location":{
                      "x":350,
                      "y":0},
                    "size":{
                      "width":130,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF990000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57db18b829df4b76a261e28e301cd78d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"cd70991721454d1a8f30825d38238c7b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "location":{
                          "x":350,
                          "y":0},
                        "size":{
                          "width":130,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF990000}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 在线支付",
                              "target":{
                                "targetType":"page",
                                "url":"在线支付.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/填写订单/u52.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "92c7de2b3633430f925bcd9bbbf5b111":{
      "scriptId":"u0"},
    "14f8bd92dd684271a29770a87e80da39":{
      "scriptId":"u1"},
    "568f9a8e236a465198e4eb3593dcc6b5":{
      "scriptId":"u2"},
    "c279b795d76e4e26822d2fc250952b90":{
      "scriptId":"u3"},
    "8a9f6812b20647db96b1e576d6a90f38":{
      "scriptId":"u4"},
    "1c7bc728bf1a4163acc0ac37c438ff2a":{
      "scriptId":"u5"},
    "7ea218dd9929452d8fe64f0d23a3eaf4":{
      "scriptId":"u6"},
    "b6290b817f3f444a84b27f01086cf397":{
      "scriptId":"u7"},
    "dbf0d64a60d04d12819585eb2a43b963":{
      "scriptId":"u8"},
    "65bcdc04baa549368e3701d7b78d1e81":{
      "scriptId":"u9",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u10"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u11"}},
    "18fc7102ae4444ed9db23e79aca527be":{
      "scriptId":"u12"},
    "786d99e00a6441c4b1c3116351dd5634":{
      "scriptId":"u13"},
    "bc473c685e2f4d6c9f3e552476290d1f":{
      "scriptId":"u14"},
    "4e93c30ee5c14fc69b5ab16e453cdc50":{
      "scriptId":"u15"},
    "8d48db8ee3a94db8a3cda2977e575192":{
      "scriptId":"u16"},
    "fd2157b83e17459ca319d633eff72c3f":{
      "scriptId":"u17"},
    "206108346c8c43cabf05100f49976960":{
      "scriptId":"u18"},
    "172ffaf7d4e74518b9905b5baa73b7d9":{
      "scriptId":"u19"},
    "051f6d0a1a5b4d7e8ac64748fa28d9cb":{
      "scriptId":"u20"},
    "4a09c843f0204bc7a975503ef267b18f":{
      "scriptId":"u21"},
    "2a4fafa42e8e44d2b5855b613969d59f":{
      "scriptId":"u22"},
    "3199f597c67c42bdad9cc1bfc50de6a9":{
      "scriptId":"u23"},
    "ccd0139ee088404eaaf232b8e6ef14cb":{
      "scriptId":"u24"},
    "e1ffd4198c0148e1a777987aa1777915":{
      "scriptId":"u25"},
    "583884f200154313a420b3f92bd1d052":{
      "scriptId":"u26"},
    "5d88b1269bcf491fb0dbe999b5c0eeb8":{
      "scriptId":"u27"},
    "5135506732684319b8e3137123880f43":{
      "scriptId":"u28"},
    "9f47bbb40e864486b4702567dbd60a09":{
      "scriptId":"u29"},
    "5588c418fcd54d969c1ec27157c976b9":{
      "scriptId":"u30"},
    "38bcc6ef8f3a4f9b8219dbbd6681a50c":{
      "scriptId":"u31"},
    "3cfb53043ae34b4ab8a3c9e6a8185095":{
      "scriptId":"u32"},
    "1638735e7c1547aa953893eca718331e":{
      "scriptId":"u33"},
    "ca45527032c04f709a8580635a83f504":{
      "scriptId":"u34"},
    "1d45efa07db44f449665620f3d1781bf":{
      "scriptId":"u35"},
    "b8bc0a6020af4a22896b6ed126c7943d":{
      "scriptId":"u36"},
    "130baaa643c84ab0b948e66b1f39a24f":{
      "scriptId":"u37"},
    "d74c1da4064f4d8aa602303d4f8993b8":{
      "scriptId":"u38"},
    "02581b7b82814d27a6ff4d2ce89aa3e3":{
      "scriptId":"u39"},
    "9ce37b1a3fc24704ae8194c3529de92e":{
      "scriptId":"u40"},
    "fff1cf4c9e7940a1a88aa3ffb77e2031":{
      "scriptId":"u41"},
    "e09c3ca53ba644fd8510dba7b7170f1b":{
      "scriptId":"u42"},
    "687659350d904eb59ee37e396cad81fa":{
      "scriptId":"u43"},
    "991d9ad384804c2d9c833d39bb646d2c":{
      "scriptId":"u44"},
    "6bc6ca3ba12248a58efb9209cf431b96":{
      "scriptId":"u45"},
    "35297b87483341bdbae1a190223122aa":{
      "scriptId":"u46"},
    "cd70991721454d1a8f30825d38238c7b":{
      "scriptId":"u47"},
    "d944b8f386384f799bebbfa652a41b02":{
      "scriptId":"u48"},
    "2d7745ec36a3476f8935824d6d57b309":{
      "scriptId":"u49"},
    "aafffee62f4c4515824d7cb326b4797a":{
      "scriptId":"u50"},
    "b9b48908247d4fb8a54da3c00af32851":{
      "scriptId":"u51"},
    "f2a34f06a6ef4cfd86bcfd681e0392a0":{
      "scriptId":"u52"},
    "57db18b829df4b76a261e28e301cd78d":{
      "scriptId":"u53"}}});