$axure.loadCurrentPage({
  "url":"产品服务（分类）.html",
  "generationDate":new Date(1470576988981.78),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f3425c2df01645eeb9fbd89db7167bb0",
    "type":"Axure:Page",
    "name":"产品服务（分类）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8a81f8ddabeb4e188a39e1a4ffb790c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cac7d3f21ac4089a21efa80a806ff7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u2.png"}},
{
          "id":"dbe5358ae1674a69b737f4b3d3d6b093",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"8817742c245a41acb003791a7ce95f80",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":50,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"957f7ead0b6d4b21b5dc68c47e71b3e1",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0896d259c34d4e328fc6bb9ae4c51528",
                  "label":"",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":119,
                      "height":750},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe0c41d595c347b5be1c137cc3daa782",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":119,
                          "height":750},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u100.png"}},
{
                  "id":"eef5e0ce510446139512022daa37deb2",
                  "label":"",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":1,
                      "y":0},
                    "size":{
                      "width":119,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ac412246c3874e61a23d627408034c78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":1,
                          "y":0},
                        "size":{
                          "width":119,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u102.png"}},
{
                  "id":"f524e287f24e4fc282f34b31f5391f96",
                  "label":"",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":1,
                      "y":80},
                    "size":{
                      "width":119,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"caecef178c47480d9b40c0834af92cea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":1,
                          "y":80},
                        "size":{
                          "width":119,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u102.png"}},
{
                  "id":"0dd738eb87004a52a0579eb401c068bc",
                  "label":"",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":1,
                      "y":160},
                    "size":{
                      "width":119,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9aa3effd11ce4ddcb8fad84df616d3ea",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":1,
                          "y":160},
                        "size":{
                          "width":119,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u102.png"}},
{
                  "id":"a8d66a3c0a2d48d9b359ad42493bb636",
                  "label":"",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":1,
                      "y":240},
                    "size":{
                      "width":119,
                      "height":80},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89c6cef48008474faf7d37eb49562b4d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":1,
                          "y":240},
                        "size":{
                          "width":119,
                          "height":80},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u102.png"}},
{
                  "id":"546b6cd2c5864d31a9a8382f4500dc92",
                  "label":"跑腿服务",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":80},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 足浴按摩,<br>上门维修,<br>衣物洗护,<br>隐藏 跑腿服务",
                              "objectsToFades":[{
                                  "objectPath":["546b6cd2c5864d31a9a8382f4500dc92"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["489dccc2e62645f184253dad7a0f7705"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["f72ebb3effc24e77ba7e7725f8e3ec97"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["54e2117aa686423a883fe959c9fa39c2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"258fdb7ef62e4540be683af24dd5e047",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"9aded547a2ca498a926b8e9d0b49c6d1",
                          "label":"",
                          "parentDynamicPanel":"546b6cd2c5864d31a9a8382f4500dc92",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "fontSize":"16px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2},
                            "size":{
                              "width":119,
                              "height":80},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5099896f746042e4bd4b22ab3d1607c7",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"546b6cd2c5864d31a9a8382f4500dc92",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "fontSize":"16px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF2F2F2},
                                "size":{
                                  "width":119,
                                  "height":80},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机外观效果/u111.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"489dccc2e62645f184253dad7a0f7705",
                  "label":"足浴按摩",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":160},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 跑腿服务,<br>上门维修,<br>衣物洗护,<br>隐藏 足浴按摩",
                              "objectsToFades":[{
                                  "objectPath":["489dccc2e62645f184253dad7a0f7705"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["546b6cd2c5864d31a9a8382f4500dc92"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["f72ebb3effc24e77ba7e7725f8e3ec97"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["54e2117aa686423a883fe959c9fa39c2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"d29da154aafd4a329e8c844e72550cbb",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"cd1b1705bb734553be3fccd9fe5ab290",
                          "label":"",
                          "parentDynamicPanel":"489dccc2e62645f184253dad7a0f7705",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "fontSize":"16px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2},
                            "size":{
                              "width":119,
                              "height":80},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"86ee63a723ef43d9b2a8e8b1a47394a8",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"489dccc2e62645f184253dad7a0f7705",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "fontSize":"16px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF2F2F2},
                                "size":{
                                  "width":119,
                                  "height":80},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机外观效果/u111.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"f72ebb3effc24e77ba7e7725f8e3ec97",
                  "label":"上门维修",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":240},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 衣物洗护,<br>足浴按摩,<br>跑腿服务,<br>隐藏 上门维修",
                              "objectsToFades":[{
                                  "objectPath":["f72ebb3effc24e77ba7e7725f8e3ec97"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["54e2117aa686423a883fe959c9fa39c2"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["489dccc2e62645f184253dad7a0f7705"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["546b6cd2c5864d31a9a8382f4500dc92"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"212f1c4d66ec42a5a852fed38ee9f983",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"fe0a358839cf4444add8565fe8d20214",
                          "label":"",
                          "parentDynamicPanel":"f72ebb3effc24e77ba7e7725f8e3ec97",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "fontSize":"16px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2},
                            "size":{
                              "width":119,
                              "height":80},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ef53b9c73e1c4518beb54f8471d4433b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"f72ebb3effc24e77ba7e7725f8e3ec97",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "fontSize":"16px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF2F2F2},
                                "size":{
                                  "width":119,
                                  "height":80},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机外观效果/u111.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"54e2117aa686423a883fe959c9fa39c2",
                  "label":"衣物洗护",
                  "parentDynamicPanel":"8817742c245a41acb003791a7ce95f80",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":10,
                      "height":10},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 上门维修,<br>足浴按摩,<br>跑腿服务,<br>隐藏 衣物洗护",
                              "objectsToFades":[{
                                  "objectPath":["54e2117aa686423a883fe959c9fa39c2"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["f72ebb3effc24e77ba7e7725f8e3ec97"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["489dccc2e62645f184253dad7a0f7705"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}},
{
                                  "objectPath":["546b6cd2c5864d31a9a8382f4500dc92"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"5ee853edbab9495cb94bdf8ec6362554",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"0e2e721380484082bb96681bfaaf1059",
                          "label":"",
                          "parentDynamicPanel":"54e2117aa686423a883fe959c9fa39c2",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'Applied Font Regular', 'Applied Font'",
                            "fontSize":"16px",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF2F2F2},
                            "size":{
                              "width":119,
                              "height":80},
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFCCCCCC}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5551d15a28014e1796e8833900e3c2be",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"54e2117aa686423a883fe959c9fa39c2",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'Applied Font Regular', 'Applied Font'",
                                "fontSize":"16px",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF2F2F2},
                                "size":{
                                  "width":119,
                                  "height":80},
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFCCCCCC}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/手机外观效果/u111.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f151ea1075324de181b08c623da9b95b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"f64740ffe6f24773b83af80528a68e1c",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":60}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"b219147549d246f2b2275ce51f70a364",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":230}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"67cbde7c81aa4a528a615b69aaad379d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":230}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"443154d35e4542fe9620bc4b8aa64e5d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":230}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"74b956b9a1344ad1b21a6e27039428a9",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":400}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"a5f6d92f1ffb4fc4ac48f896d24ea047",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":400}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"a57c650000ea43818f7184529fe5bed6",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":400}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"d6f67e10c57d4557a0fb13d6f3c0ac84",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":570}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"07d6369022d1416c9be40391394c5162",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":570}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"7d7fde2932c041be8f29c862ec5a5e5d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":570}},
          "adaptiveStyles":{
},
          "masterId":"60cb433a9d4d4da4b45670eee970ae7f"},
{
          "id":"6ab2fd8433514785a5a21c20d950fe4f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9894c387b500410fb457ab515ffd8ab7",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5ff8b52dad1e4d0da5dbadbe90310fa5",
                  "label":"",
                  "parentDynamicPanel":"6ab2fd8433514785a5a21c20d950fe4f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6187913b60154917be4471deb5f77552",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6ab2fd8433514785a5a21c20d950fe4f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"b603f067bbf54a8185b9bca0e6668b1e",
                  "label":"",
                  "parentDynamicPanel":"6ab2fd8433514785a5a21c20d950fe4f",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":460,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"394071e1d88e44fc9b310931387d2e75"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"cb9afc581ea14967ace829e47cf58ed6",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":740},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3decba1543294307bad8d37f555b44e5",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0624b2462041473ebb2be32ae04a6b17",
                  "label":"",
                  "parentDynamicPanel":"cb9afc581ea14967ace829e47cf58ed6",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "masterId":"bd69c12d7cdd46d7b44b52fbbf59fcbd"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "60cb433a9d4d4da4b45670eee970ae7f":{
      "packageId":"60cb433a9d4d4da4b45670eee970ae7f",
      "type":"Axure:Master",
      "name":"分类/标题",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bdc0bb971bca4a0cbf9efe362ca22e69",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "horizontalAlignment":"center",
              "location":{
                "x":0,
                "y":110},
              "size":{
                "width":100,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"9976a34985fa4b7c9394fcaeaa769bb8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "horizontalAlignment":"center",
                  "location":{
                    "x":0,
                    "y":110},
                  "size":{
                    "width":100,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品列表",
                        "target":{
                          "targetType":"page",
                          "url":"产品列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"8932d163ae024ff586ffe5281e0acb7d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFF2F2F2},
              "size":{
                "width":100,
                "height":100},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c8c254339c3d487b820376ccc0c322ea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF2F2F2},
                  "size":{
                    "width":100,
                    "height":100},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品列表",
                        "target":{
                          "targetType":"page",
                          "url":"产品列表.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png",
              "normal~":"images/手机外观效果/u97.png"}}]}},
    "394071e1d88e44fc9b310931387d2e75":{
      "packageId":"394071e1d88e44fc9b310931387d2e75",
      "type":"Axure:Master",
      "name":"搜索",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f5e075e6b0c24551a3d2f27b548547fc",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":100,
                "y":0},
              "size":{
                "width":40,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e89f87283be34826b9370e9126a4599c",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":100,
                    "y":0},
                  "size":{
                    "width":40,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u28.png"}},
{
            "id":"1b26c5d35c984f4fa388018f1868d0d3",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":110,
                "y":5},
              "size":{
                "width":20,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"38ab782b63834a108f4fb89061ef1465",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":110,
                    "y":5},
                  "size":{
                    "width":20,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 搜索",
                        "target":{
                          "targetType":"page",
                          "url":"搜索.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u30.png"}},
{
            "id":"406cc4bbea764710a287d4923294d571",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"11px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "size":{
                "width":30,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"de28fc7bce484ddcae9214751084ab26",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"11px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "size":{
                    "width":30,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u32.png"}},
{
            "id":"c731a6f6d5144c75a64db63c3a6dd892",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":40,
                "y":5},
              "size":{
                "width":50,
                "height":20}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"83c9629b25b04e7e8f45d4da6c1e1138",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":40,
                    "y":5},
                  "size":{
                    "width":50,
                    "height":20}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 定位",
                        "target":{
                          "targetType":"page",
                          "url":"定位.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"15d3b2509dbd4086bd8f71497eaa8120",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "horizontalAlignment":"left",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":140,
                "y":0},
              "size":{
                "width":320,
                "height":30},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3228d0d8a30e498abe7309865cccba46",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "horizontalAlignment":"left",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":140,
                    "y":0},
                  "size":{
                    "width":320,
                    "height":30},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 搜索",
                        "target":{
                          "targetType":"page",
                          "url":"搜索.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u36.png"}}]}},
    "bd69c12d7cdd46d7b44b52fbbf59fcbd":{
      "packageId":"bd69c12d7cdd46d7b44b52fbbf59fcbd",
      "type":"Axure:Master",
      "name":"底部菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"6b310f0e678d48b181949d89b0277be7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d28d8d8c55ed447eadfd69e7a6782e22",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"078f939cda994065a7d80d7a3f8327aa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":96,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c6c09e7e0684ef9a0f20d7159a8da17",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":96,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品服务（分类）",
                        "target":{
                          "targetType":"page",
                          "url":"产品服务（分类）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"56399286ce8943e98036cdddf0c0027f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":192,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"206a19eb311f41b2a8d8a4fa60795674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":192,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物清单",
                        "target":{
                          "targetType":"page",
                          "url":"购物清单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"122a1594a7a24844882178dd2d2a300b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":288,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ee0334c4e084108b37ffbd6009f2fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":288,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 会员中心",
                        "target":{
                          "targetType":"page",
                          "url":"会员中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"8fb898143df2461fa5f60a2d6f71065e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":384,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5b8fcdc760b548a29e70e88b8be2d8e4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":384,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"253a47ab0b284e3f98b0e6d849641899",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":364,
                "y":0},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF0000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8bd318c93aa14e188f863643487752d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":364,
                    "y":0},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u88.png"}}]}}},
  "objectPaths":{
    "8a81f8ddabeb4e188a39e1a4ffb790c2":{
      "scriptId":"u0"},
    "6cac7d3f21ac4089a21efa80a806ff7a":{
      "scriptId":"u1"},
    "dbe5358ae1674a69b737f4b3d3d6b093":{
      "scriptId":"u2",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u3"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u4"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u5"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u6"}},
    "8817742c245a41acb003791a7ce95f80":{
      "scriptId":"u7"},
    "0896d259c34d4e328fc6bb9ae4c51528":{
      "scriptId":"u8"},
    "fe0c41d595c347b5be1c137cc3daa782":{
      "scriptId":"u9"},
    "eef5e0ce510446139512022daa37deb2":{
      "scriptId":"u10"},
    "ac412246c3874e61a23d627408034c78":{
      "scriptId":"u11"},
    "f524e287f24e4fc282f34b31f5391f96":{
      "scriptId":"u12"},
    "caecef178c47480d9b40c0834af92cea":{
      "scriptId":"u13"},
    "0dd738eb87004a52a0579eb401c068bc":{
      "scriptId":"u14"},
    "9aa3effd11ce4ddcb8fad84df616d3ea":{
      "scriptId":"u15"},
    "a8d66a3c0a2d48d9b359ad42493bb636":{
      "scriptId":"u16"},
    "89c6cef48008474faf7d37eb49562b4d":{
      "scriptId":"u17"},
    "546b6cd2c5864d31a9a8382f4500dc92":{
      "scriptId":"u18"},
    "9aded547a2ca498a926b8e9d0b49c6d1":{
      "scriptId":"u19"},
    "5099896f746042e4bd4b22ab3d1607c7":{
      "scriptId":"u20"},
    "489dccc2e62645f184253dad7a0f7705":{
      "scriptId":"u21"},
    "cd1b1705bb734553be3fccd9fe5ab290":{
      "scriptId":"u22"},
    "86ee63a723ef43d9b2a8e8b1a47394a8":{
      "scriptId":"u23"},
    "f72ebb3effc24e77ba7e7725f8e3ec97":{
      "scriptId":"u24"},
    "fe0a358839cf4444add8565fe8d20214":{
      "scriptId":"u25"},
    "ef53b9c73e1c4518beb54f8471d4433b":{
      "scriptId":"u26"},
    "54e2117aa686423a883fe959c9fa39c2":{
      "scriptId":"u27"},
    "0e2e721380484082bb96681bfaaf1059":{
      "scriptId":"u28"},
    "5551d15a28014e1796e8833900e3c2be":{
      "scriptId":"u29"},
    "f151ea1075324de181b08c623da9b95b":{
      "scriptId":"u30",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u31"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u32"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u33"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u34"}},
    "f64740ffe6f24773b83af80528a68e1c":{
      "scriptId":"u35",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u36"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u37"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u38"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u39"}},
    "b219147549d246f2b2275ce51f70a364":{
      "scriptId":"u40",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u41"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u42"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u43"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u44"}},
    "67cbde7c81aa4a528a615b69aaad379d":{
      "scriptId":"u45",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u46"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u47"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u48"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u49"}},
    "443154d35e4542fe9620bc4b8aa64e5d":{
      "scriptId":"u50",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u51"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u52"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u53"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u54"}},
    "74b956b9a1344ad1b21a6e27039428a9":{
      "scriptId":"u55",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u56"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u57"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u58"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u59"}},
    "a5f6d92f1ffb4fc4ac48f896d24ea047":{
      "scriptId":"u60",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u61"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u62"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u63"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u64"}},
    "a57c650000ea43818f7184529fe5bed6":{
      "scriptId":"u65",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u66"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u67"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u68"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u69"}},
    "d6f67e10c57d4557a0fb13d6f3c0ac84":{
      "scriptId":"u70",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u71"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u72"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u73"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u74"}},
    "07d6369022d1416c9be40391394c5162":{
      "scriptId":"u75",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u76"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u77"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u78"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u79"}},
    "7d7fde2932c041be8f29c862ec5a5e5d":{
      "scriptId":"u80",
      "bdc0bb971bca4a0cbf9efe362ca22e69":{
        "scriptId":"u81"},
      "9976a34985fa4b7c9394fcaeaa769bb8":{
        "scriptId":"u82"},
      "8932d163ae024ff586ffe5281e0acb7d":{
        "scriptId":"u83"},
      "c8c254339c3d487b820376ccc0c322ea":{
        "scriptId":"u84"}},
    "6ab2fd8433514785a5a21c20d950fe4f":{
      "scriptId":"u85"},
    "5ff8b52dad1e4d0da5dbadbe90310fa5":{
      "scriptId":"u86"},
    "6187913b60154917be4471deb5f77552":{
      "scriptId":"u87"},
    "b603f067bbf54a8185b9bca0e6668b1e":{
      "scriptId":"u88",
      "f5e075e6b0c24551a3d2f27b548547fc":{
        "scriptId":"u89"},
      "e89f87283be34826b9370e9126a4599c":{
        "scriptId":"u90"},
      "1b26c5d35c984f4fa388018f1868d0d3":{
        "scriptId":"u91"},
      "38ab782b63834a108f4fb89061ef1465":{
        "scriptId":"u92"},
      "406cc4bbea764710a287d4923294d571":{
        "scriptId":"u93"},
      "de28fc7bce484ddcae9214751084ab26":{
        "scriptId":"u94"},
      "c731a6f6d5144c75a64db63c3a6dd892":{
        "scriptId":"u95"},
      "83c9629b25b04e7e8f45d4da6c1e1138":{
        "scriptId":"u96"},
      "15d3b2509dbd4086bd8f71497eaa8120":{
        "scriptId":"u97"},
      "3228d0d8a30e498abe7309865cccba46":{
        "scriptId":"u98"}},
    "cb9afc581ea14967ace829e47cf58ed6":{
      "scriptId":"u99"},
    "0624b2462041473ebb2be32ae04a6b17":{
      "scriptId":"u100",
      "6b310f0e678d48b181949d89b0277be7":{
        "scriptId":"u101"},
      "d28d8d8c55ed447eadfd69e7a6782e22":{
        "scriptId":"u102"},
      "078f939cda994065a7d80d7a3f8327aa":{
        "scriptId":"u103"},
      "7c6c09e7e0684ef9a0f20d7159a8da17":{
        "scriptId":"u104"},
      "56399286ce8943e98036cdddf0c0027f":{
        "scriptId":"u105"},
      "206a19eb311f41b2a8d8a4fa60795674":{
        "scriptId":"u106"},
      "122a1594a7a24844882178dd2d2a300b":{
        "scriptId":"u107"},
      "3ee0334c4e084108b37ffbd6009f2fea":{
        "scriptId":"u108"},
      "8fb898143df2461fa5f60a2d6f71065e":{
        "scriptId":"u109"},
      "5b8fcdc760b548a29e70e88b8be2d8e4":{
        "scriptId":"u110"},
      "253a47ab0b284e3f98b0e6d849641899":{
        "scriptId":"u111"},
      "8bd318c93aa14e188f863643487752d9":{
        "scriptId":"u112"}}}});