$axure.loadCurrentPage({
  "url":"会员中心.html",
  "generationDate":new Date(1470576992416.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5e74fb0c88ba44798afce8c002a2b600",
    "type":"Axure:Page",
    "name":"会员中心",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6fe7968e26724ba1aeea60805b3a142c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff506619b22441f9a6f55c2101cd86ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"2331219df2f34a5a883a084ebe35de5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":480,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac68f30488654503bea8fc3f6f9fcdc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":480,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/会员中心/u2.png"}},
{
          "id":"5e6f5ddf72f74f7c8300a805219aa776",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"99149dae185f44c0bdd9828b4751c84d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"9248ff5e397c4806a9cd2b1d01553526",
                  "label":"",
                  "parentDynamicPanel":"5e6f5ddf72f74f7c8300a805219aa776",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"179cd7f208164ee09d735646efb489a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e6f5ddf72f74f7c8300a805219aa776",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u50.png"}},
{
                  "id":"8e2e604b821a463eb82fd5b8d93935bf",
                  "label":"",
                  "parentDynamicPanel":"5e6f5ddf72f74f7c8300a805219aa776",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45940a5f81ab41f78cbf2e7730f90b38",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5e6f5ddf72f74f7c8300a805219aa776",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"869105b503094295aab86f52ec2fd5da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":200,
              "y":90},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0x7FFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98be91e298644a6dbb216d2a1c67c61d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":200,
                  "y":90},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员中心/u9.png"}},
{
          "id":"59bd7253e54e42bd82b63a330e253138",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":230},
            "size":{
              "width":480,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6a914460eb54810aa983a8fd5c0e10c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":230},
                "size":{
                  "width":480,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u357.png"}},
{
          "id":"edf3c4b10f954feab9d4ca06260d9b62",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15ad6bb919254879a57c6ed4dbe9c743",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53b49d8b67b84c4db5c207452ed592c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":240},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4c945171368477aa14b1999b28fa0a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":240},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"284dbb2c3b854f7cb2de92c00728fe31",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":274},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u420_line.png"}},
{
          "id":"7b7741296bcf475297ba274011067270",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":370},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"115231bce5534e5b88c21dfa9f149b59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":370},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u353.png"}},
{
          "id":"7f78d63551bb45be9c51300ca82a3456",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":380},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"700178c676af4605b66b4eb89882f476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":380},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c2f31827e94b4dd3afa8d664000f6341",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":414},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u420_line.png"}},
{
          "id":"9f287f9279fe4aa3869dea2cf7aa560e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":380},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bfb2f1051d94dde88a958345ff5e0ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":380},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 意见反馈",
                      "target":{
                        "targetType":"page",
                        "url":"意见反馈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10f363da92334e8083493a976d4c3a2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":430},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e68ca287860143a18df3b1d912351d76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":430},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a8a7aa1083194986b7933b03dc316a34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":430},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d0f91f2de6140cfa3f38c9ca093ad7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":430},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f68bc9fd3b60425ea935491a2e85ac72",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":540},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"749aee6d5bc64c52bd5f41a443d9275b",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"fc2bfc0e52ae44b7b34b35a3958d3494",
                  "label":"",
                  "parentDynamicPanel":"f68bc9fd3b60425ea935491a2e85ac72",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":480,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "masterId":"bd69c12d7cdd46d7b44b52fbbf59fcbd"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d48fff9d6c01455e94f9f1ef75680fb6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":235,
              "y":294},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae77fd5ee8a944628199cb03608d46c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":235,
                  "y":294},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员中心/u43.png"}},
{
          "id":"1fe8e1f0581d40778f57995c955c2883",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":75,
              "y":294},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc5dd3d7dd8b4256b8caf028d99a7c3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":75,
                  "y":294},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员中心/u45.png"}},
{
          "id":"30c7dc9324694e01a793461af84c6485",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":393,
              "y":294},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74f00dca140e4080a5cad8e20f6006df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":393,
                  "y":294},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/会员中心/u47.png"}},
{
          "id":"acfc2de425d0438f824475e5ecf70247",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":370,
              "y":336},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1df17e2fd5e4ee8a787a2205134d1d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":370,
                  "y":336},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd75ea2fe0da4bc488623cadcc1dba1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":50,
              "y":334},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"22f96ccb90a341faa073b07d76199b0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":50,
                  "y":334},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b3cbb05ba8694228b3690934c1921383",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":210,
              "y":334},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19415610c28342a5b15fa2145507243d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":210,
                  "y":334},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录",
                      "target":{
                        "targetType":"page",
                        "url":"登录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "bd69c12d7cdd46d7b44b52fbbf59fcbd":{
      "packageId":"bd69c12d7cdd46d7b44b52fbbf59fcbd",
      "type":"Axure:Master",
      "name":"底部菜单",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"6b310f0e678d48b181949d89b0277be7",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d28d8d8c55ed447eadfd69e7a6782e22",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 主页",
                        "target":{
                          "targetType":"page",
                          "url":"主页.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"078f939cda994065a7d80d7a3f8327aa",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":96,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7c6c09e7e0684ef9a0f20d7159a8da17",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":96,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品服务（分类）",
                        "target":{
                          "targetType":"page",
                          "url":"产品服务（分类）.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"56399286ce8943e98036cdddf0c0027f",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":192,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"206a19eb311f41b2a8d8a4fa60795674",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":192,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 购物清单",
                        "target":{
                          "targetType":"page",
                          "url":"购物清单.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"122a1594a7a24844882178dd2d2a300b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":288,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"3ee0334c4e084108b37ffbd6009f2fea",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":288,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 会员中心",
                        "target":{
                          "targetType":"page",
                          "url":"会员中心.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"8fb898143df2461fa5f60a2d6f71065e",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":384,
                "y":0},
              "size":{
                "width":96,
                "height":60},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5b8fcdc760b548a29e70e88b8be2d8e4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":384,
                    "y":0},
                  "size":{
                    "width":96,
                    "height":60},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 更多",
                        "target":{
                          "targetType":"page",
                          "url":"更多.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u78.png"}},
{
            "id":"253a47ab0b284e3f98b0e6d849641899",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF,
                "opacity":1},
              "fill":{
                "fillType":"solid",
                "color":0xFFFF0000},
              "location":{
                "x":364,
                "y":0},
              "size":{
                "width":20,
                "height":20},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFF0000}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8bd318c93aa14e188f863643487752d9",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF,
                    "opacity":1},
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFFF0000},
                  "location":{
                    "x":364,
                    "y":0},
                  "size":{
                    "width":20,
                    "height":20},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u88.png"}}]}}},
  "objectPaths":{
    "6fe7968e26724ba1aeea60805b3a142c":{
      "scriptId":"u0"},
    "ff506619b22441f9a6f55c2101cd86ce":{
      "scriptId":"u1"},
    "2331219df2f34a5a883a084ebe35de5f":{
      "scriptId":"u2"},
    "ac68f30488654503bea8fc3f6f9fcdc0":{
      "scriptId":"u3"},
    "5e6f5ddf72f74f7c8300a805219aa776":{
      "scriptId":"u4"},
    "9248ff5e397c4806a9cd2b1d01553526":{
      "scriptId":"u5"},
    "179cd7f208164ee09d735646efb489a4":{
      "scriptId":"u6"},
    "8e2e604b821a463eb82fd5b8d93935bf":{
      "scriptId":"u7"},
    "45940a5f81ab41f78cbf2e7730f90b38":{
      "scriptId":"u8"},
    "869105b503094295aab86f52ec2fd5da":{
      "scriptId":"u9"},
    "98be91e298644a6dbb216d2a1c67c61d":{
      "scriptId":"u10"},
    "59bd7253e54e42bd82b63a330e253138":{
      "scriptId":"u11"},
    "c6a914460eb54810aa983a8fd5c0e10c":{
      "scriptId":"u12"},
    "edf3c4b10f954feab9d4ca06260d9b62":{
      "scriptId":"u13"},
    "15ad6bb919254879a57c6ed4dbe9c743":{
      "scriptId":"u14"},
    "53b49d8b67b84c4db5c207452ed592c4":{
      "scriptId":"u15"},
    "e4c945171368477aa14b1999b28fa0a8":{
      "scriptId":"u16"},
    "284dbb2c3b854f7cb2de92c00728fe31":{
      "scriptId":"u17"},
    "7b7741296bcf475297ba274011067270":{
      "scriptId":"u18"},
    "115231bce5534e5b88c21dfa9f149b59":{
      "scriptId":"u19"},
    "7f78d63551bb45be9c51300ca82a3456":{
      "scriptId":"u20"},
    "700178c676af4605b66b4eb89882f476":{
      "scriptId":"u21"},
    "c2f31827e94b4dd3afa8d664000f6341":{
      "scriptId":"u22"},
    "9f287f9279fe4aa3869dea2cf7aa560e":{
      "scriptId":"u23"},
    "3bfb2f1051d94dde88a958345ff5e0ed":{
      "scriptId":"u24"},
    "10f363da92334e8083493a976d4c3a2a":{
      "scriptId":"u25"},
    "e68ca287860143a18df3b1d912351d76":{
      "scriptId":"u26"},
    "a8a7aa1083194986b7933b03dc316a34":{
      "scriptId":"u27"},
    "7d0f91f2de6140cfa3f38c9ca093ad7a":{
      "scriptId":"u28"},
    "f68bc9fd3b60425ea935491a2e85ac72":{
      "scriptId":"u29"},
    "fc2bfc0e52ae44b7b34b35a3958d3494":{
      "scriptId":"u30",
      "6b310f0e678d48b181949d89b0277be7":{
        "scriptId":"u31"},
      "d28d8d8c55ed447eadfd69e7a6782e22":{
        "scriptId":"u32"},
      "078f939cda994065a7d80d7a3f8327aa":{
        "scriptId":"u33"},
      "7c6c09e7e0684ef9a0f20d7159a8da17":{
        "scriptId":"u34"},
      "56399286ce8943e98036cdddf0c0027f":{
        "scriptId":"u35"},
      "206a19eb311f41b2a8d8a4fa60795674":{
        "scriptId":"u36"},
      "122a1594a7a24844882178dd2d2a300b":{
        "scriptId":"u37"},
      "3ee0334c4e084108b37ffbd6009f2fea":{
        "scriptId":"u38"},
      "8fb898143df2461fa5f60a2d6f71065e":{
        "scriptId":"u39"},
      "5b8fcdc760b548a29e70e88b8be2d8e4":{
        "scriptId":"u40"},
      "253a47ab0b284e3f98b0e6d849641899":{
        "scriptId":"u41"},
      "8bd318c93aa14e188f863643487752d9":{
        "scriptId":"u42"}},
    "d48fff9d6c01455e94f9f1ef75680fb6":{
      "scriptId":"u43"},
    "ae77fd5ee8a944628199cb03608d46c7":{
      "scriptId":"u44"},
    "1fe8e1f0581d40778f57995c955c2883":{
      "scriptId":"u45"},
    "fc5dd3d7dd8b4256b8caf028d99a7c3b":{
      "scriptId":"u46"},
    "30c7dc9324694e01a793461af84c6485":{
      "scriptId":"u47"},
    "74f00dca140e4080a5cad8e20f6006df":{
      "scriptId":"u48"},
    "acfc2de425d0438f824475e5ecf70247":{
      "scriptId":"u49"},
    "e1df17e2fd5e4ee8a787a2205134d1d7":{
      "scriptId":"u50"},
    "dd75ea2fe0da4bc488623cadcc1dba1d":{
      "scriptId":"u51"},
    "22f96ccb90a341faa073b07d76199b0a":{
      "scriptId":"u52"},
    "b3cbb05ba8694228b3690934c1921383":{
      "scriptId":"u53"},
    "19415610c28342a5b15fa2145507243d":{
      "scriptId":"u54"}}});