$axure.loadCurrentPage({
  "url":"新增收货地址.html",
  "generationDate":new Date(1470576992095.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e057cb1be9cf4101b76175711ea3e648",
    "type":"Axure:Page",
    "name":"新增收货地址",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3e449b8cdac14d649cae8f6773412947",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"506cf720fad64b8b8895bd6ede0130f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"87dc4a315a10427f9e5e19e3ce07c860",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0b2c5068f48a45c487985aed548b564a",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"30cac5a3c04d419dba2e8e444d188397",
                  "label":"",
                  "parentDynamicPanel":"87dc4a315a10427f9e5e19e3ce07c860",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1f4b2923ae734ad5bb5ed616ee1fad32",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"87dc4a315a10427f9e5e19e3ce07c860",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"e6f9f5b75aa14963b5193d40665a8f78",
                  "label":"",
                  "parentDynamicPanel":"87dc4a315a10427f9e5e19e3ce07c860",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"97a11efe2b144f01af62e46a10eac126",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"87dc4a315a10427f9e5e19e3ce07c860",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e3c6673003d42a7aea69ba7fee0f0de",
                  "label":"",
                  "parentDynamicPanel":"87dc4a315a10427f9e5e19e3ce07c860",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"8dd8d3985ed6495e941e51139c390105",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":480,
              "height":250},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ae5a0fcc4454ad2b62d32fa73dbad4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":480,
                  "height":250},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑收货地址/u12.png"}},
{
          "id":"f72ae79d5c46420cb5f07581e8d7bee5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":95},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u420_line.png"}},
{
          "id":"be45e7e5640749e5a717f4bce2efc257",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":370,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"cab0f219b3854d34a284d79558b42f27",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":110,
              "y":60},
            "size":{
              "width":370,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"fa43ccc943d346139003652368c4d82d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":10,
              "y":300},
            "size":{
              "width":480,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF9900}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"483f150554004caf92d4cca185cb8833",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":10,
                  "y":300},
                "size":{
                  "width":480,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF9900}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑收货地址/u17.png"}},
{
          "id":"4cfee31c529c4ab1911b3bceb0dce5bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF3300,
              "opacity":1},
            "location":{
              "x":46,
              "y":305},
            "size":{
              "width":434,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"02f1536de1ae4b2f98cc4539b7cce403",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF3300,
                  "opacity":1},
                "location":{
                  "x":46,
                  "y":305},
                "size":{
                  "width":434,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c7add462e5541eea94e7ba3cc0d15b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"50px",
            "location":{
              "x":20,
              "y":50},
            "size":{
              "width":100,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec3199eb822e4c00a310103db2bc9da9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"50px",
                "location":{
                  "x":20,
                  "y":50},
                "size":{
                  "width":100,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7a2bcb1cc6c4249b09c102c7125c255",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":145},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u420_line.png"}},
{
          "id":"f77a3329dcbd4e699df688b143796a10",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":195},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u420_line.png"}},
{
          "id":"647e102195d0482591385f732151ad20",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":245},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u420_line.png"}},
{
          "id":"d2df3e300cc14636a78d9a296baefc86",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":450,
              "y":260},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7886c23909334ba388cf3dfee200bb51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":450,
                  "y":260},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/编辑收货地址/u26.png"}},
{
          "id":"6c6c70ff2b4a49ca8f2b04c11532d396",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":110,
              "y":210},
            "size":{
              "width":370,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 保存新地址",
                      "objectsToFades":[{
                          "objectPath":["869bff4e91524190af7f9fa546bbfa69"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"ec4dd6f1cbee4629a003d0b88d72b734",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":110,
              "y":160},
            "size":{
              "width":370,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"a388c6d2002d4e25a9ad239241b36e20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":20,
              "y":340},
            "size":{
              "width":460,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81616096420246369e49ff79acb11734",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":20,
                  "y":340},
                "size":{
                  "width":460,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增收货地址/u28.png"}},
{
          "id":"869bff4e91524190af7f9fa546bbfa69",
          "label":"保存新地址",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":20,
              "y":340},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"1a8b6c431a4b449584819ad0d9b8f724",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"88d7460159e04556a3340b5661c8b373",
                  "label":"",
                  "parentDynamicPanel":"869bff4e91524190af7f9fa546bbfa69",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "size":{
                      "width":460,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0fd7e446f5014f5897ab48eead2c6c23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"869bff4e91524190af7f9fa546bbfa69",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "size":{
                          "width":460,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 填写订单",
                              "target":{
                                "targetType":"page",
                                "url":"填写订单.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录/u28.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"afa6f5d49b104fe996f4d72cb7caeabe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":160},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92269e8ed3c248fa90e5b73a5409c993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":160},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 所在区域",
                      "target":{
                        "targetType":"page",
                        "url":"所在区域.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "3e449b8cdac14d649cae8f6773412947":{
      "scriptId":"u0"},
    "506cf720fad64b8b8895bd6ede0130f4":{
      "scriptId":"u1"},
    "87dc4a315a10427f9e5e19e3ce07c860":{
      "scriptId":"u2"},
    "30cac5a3c04d419dba2e8e444d188397":{
      "scriptId":"u3"},
    "1f4b2923ae734ad5bb5ed616ee1fad32":{
      "scriptId":"u4"},
    "e6f9f5b75aa14963b5193d40665a8f78":{
      "scriptId":"u5"},
    "97a11efe2b144f01af62e46a10eac126":{
      "scriptId":"u6"},
    "1e3c6673003d42a7aea69ba7fee0f0de":{
      "scriptId":"u7",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u8"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u9"}},
    "8dd8d3985ed6495e941e51139c390105":{
      "scriptId":"u10"},
    "4ae5a0fcc4454ad2b62d32fa73dbad4d":{
      "scriptId":"u11"},
    "f72ae79d5c46420cb5f07581e8d7bee5":{
      "scriptId":"u12"},
    "be45e7e5640749e5a717f4bce2efc257":{
      "scriptId":"u13"},
    "cab0f219b3854d34a284d79558b42f27":{
      "scriptId":"u14"},
    "fa43ccc943d346139003652368c4d82d":{
      "scriptId":"u15"},
    "483f150554004caf92d4cca185cb8833":{
      "scriptId":"u16"},
    "4cfee31c529c4ab1911b3bceb0dce5bc":{
      "scriptId":"u17"},
    "02f1536de1ae4b2f98cc4539b7cce403":{
      "scriptId":"u18"},
    "2c7add462e5541eea94e7ba3cc0d15b3":{
      "scriptId":"u19"},
    "ec3199eb822e4c00a310103db2bc9da9":{
      "scriptId":"u20"},
    "b7a2bcb1cc6c4249b09c102c7125c255":{
      "scriptId":"u21"},
    "f77a3329dcbd4e699df688b143796a10":{
      "scriptId":"u22"},
    "647e102195d0482591385f732151ad20":{
      "scriptId":"u23"},
    "d2df3e300cc14636a78d9a296baefc86":{
      "scriptId":"u24"},
    "7886c23909334ba388cf3dfee200bb51":{
      "scriptId":"u25"},
    "6c6c70ff2b4a49ca8f2b04c11532d396":{
      "scriptId":"u26"},
    "ec4dd6f1cbee4629a003d0b88d72b734":{
      "scriptId":"u27"},
    "a388c6d2002d4e25a9ad239241b36e20":{
      "scriptId":"u28"},
    "81616096420246369e49ff79acb11734":{
      "scriptId":"u29"},
    "869bff4e91524190af7f9fa546bbfa69":{
      "scriptId":"u30"},
    "88d7460159e04556a3340b5661c8b373":{
      "scriptId":"u31"},
    "0fd7e446f5014f5897ab48eead2c6c23":{
      "scriptId":"u32"},
    "afa6f5d49b104fe996f4d72cb7caeabe":{
      "scriptId":"u33"},
    "92269e8ed3c248fa90e5b73a5409c993":{
      "scriptId":"u34"}}});