$axure.loadCurrentPage({
  "url":"评价.html",
  "generationDate":new Date(1470576993635.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"84d326f7df59434895641524dcbc5057",
    "type":"Axure:Page",
    "name":"评价",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2fcded345ca14188aaf5fa2d2f0e5f01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a648e58fa3a54943b518cf589ae2ee37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"7d02496f1ff44625bff27e85262326b4",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5bb154bd915f4d629e47da1a4b1d2769",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c117922efbc44c8884db0f6b437a3f46",
                  "label":"",
                  "parentDynamicPanel":"7d02496f1ff44625bff27e85262326b4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9c51464535184568a4f52b083304d3fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d02496f1ff44625bff27e85262326b4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"422075541d56411c9bc1eb60f008fcd7",
                  "label":"",
                  "parentDynamicPanel":"7d02496f1ff44625bff27e85262326b4",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
                  "id":"00673295c634488b8ca36f2c1de3cb5d",
                  "label":"",
                  "parentDynamicPanel":"7d02496f1ff44625bff27e85262326b4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fcb13fe6150e40e5a4cbd20e6393d41c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d02496f1ff44625bff27e85262326b4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3534c4728e99470491e4f816358d7f89",
                  "label":"",
                  "parentDynamicPanel":"7d02496f1ff44625bff27e85262326b4",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "location":{
                      "x":420,
                      "y":15},
                    "size":{
                      "width":50,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8db091a98108440f9d8d0810ce6b1ff9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7d02496f1ff44625bff27e85262326b4",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "location":{
                          "x":420,
                          "y":15},
                        "size":{
                          "width":50,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 评价成功",
                              "target":{
                                "targetType":"page",
                                "url":"评价成功.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"beac2dc8e8bc46b4933ebe04b9ce518a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":480,
              "height":320},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdeb165bff284ad88d2498365f9983e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":480,
                  "height":320},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u12.png"}},
{
          "id":"aac2216cbc484cf484832247ab7d9483",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85ba294c3d5c4e71b30d67cbd8108a1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购物清单/u71.png"}},
{
          "id":"7ebcc6bbda154480855448b3750bc968",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"22px",
            "location":{
              "x":110,
              "y":60},
            "size":{
              "width":370,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ff66edfc8ae484a8515755da88faa47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"22px",
                "location":{
                  "x":110,
                  "y":60},
                "size":{
                  "width":370,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7048b9ae766c482dbb67a056533c512c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u455_line.png"}},
{
          "id":"73a0b26ba7c44da28cfd012095844205",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":100},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"abae425e32d44d79b11a3089ec9e2143",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":100},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u19.png"}},
{
          "id":"00c0d8bd9ac145848dc083823016de48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":140,
              "y":100},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"410cbc576aba46569eec708706ca5a24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":140,
                  "y":100},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u19.png"}},
{
          "id":"8c4f55195123462d9dcb86f4c48eb9e4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":170,
              "y":100},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45290c7d7f884a0bbaf7f751e8b1c034",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":170,
                  "y":100},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u19.png"}},
{
          "id":"a58e3a8d075046988b09c6dd496a924f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":200,
              "y":100},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"636fd57735e2472db8e9bb8b2bd5ff0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":200,
                  "y":100},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u19.png"}},
{
          "id":"09f097b934d048ba831b45907e5b471d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":230,
              "y":100},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9917c16d896c46978b30971aa8d9a31a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":230,
                  "y":100},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u19.png"}},
{
          "id":"dd6d7a1c92424402ae497c6f675a2a37",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":180,
              "y":270},
            "size":{
              "width":120,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2e9da29a7145aca1dea9d5a5f2de74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":180,
                  "y":270},
                "size":{
                  "width":120,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u361.png"}},
{
          "id":"1bfeb51680f04fcb989fedf789eba7a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"22px",
            "location":{
              "x":20,
              "y":238},
            "size":{
              "width":460,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ab35b78afae4c0091942336922d39ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"22px",
                "location":{
                  "x":20,
                  "y":238},
                "size":{
                  "width":460,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c3636be0144436fa87b73ba90cce563",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":310},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u455_line.png"}},
{
          "id":"450eea5f09bb4f458df96f14679590ba",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":330},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c56a444f4f9441f292339e37e7751bba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":330},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"bd43c56a4b2b4c2fa2fe1ec20f7d6ac7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":380},
            "size":{
              "width":480,
              "height":220},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26a4f2bff5a649b89acb87800df156c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":380},
                "size":{
                  "width":480,
                  "height":220},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u36.png"}},
{
          "id":"1c970eff57ed4406835478e3c025187b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "verticalAlignment":"middle",
            "lineSpacing":"22px",
            "location":{
              "x":20,
              "y":390},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f104b4041f849c4af76964d343c9293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "lineSpacing":"22px",
                "location":{
                  "x":20,
                  "y":390},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c35e101bca724c4392fbcb84bbdfe5e3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":420},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u455_line.png"}},
{
          "id":"14b1d55e63a44f789d465faec8225f63",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"40px",
            "location":{
              "x":20,
              "y":440},
            "size":{
              "width":200,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b1af6cce06d4ab2818dec30b2cb34c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"40px",
                "location":{
                  "x":20,
                  "y":440},
                "size":{
                  "width":200,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e226c90023054bbaaf23b471aeeaa0d4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"22px",
            "location":{
              "x":300,
              "y":390},
            "size":{
              "width":180,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8251eb93f0ac4f378c0e0f5d4ff61e5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"22px",
                "location":{
                  "x":300,
                  "y":390},
                "size":{
                  "width":180,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1a831896a144a409f55bc5fd50af0e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":340,
              "y":445},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17f49326a4024b88a5ba3fcae5c08c9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":340,
                  "y":445},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"30c2aca2d8bd4e548b31892c031c7a73",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":370,
              "y":445},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6173348d9fe47f5bc224eed53ab64c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":370,
                  "y":445},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"143c5b1df05c4542a79c1e7b1c0576b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":400,
              "y":445},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46f4570bd4bb4a628e03455a0e38ae95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":400,
                  "y":445},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"acba019f5dce4e99ac503ca8f8c2a589",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":430,
              "y":445},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"794b46c959f545ab8ade5731b0b15f0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":430,
                  "y":445},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"763d2f1da5d3450d86910a782e3dc0e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":460,
              "y":445},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f26b2b84af184cd58a9a14ab66db322e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":460,
                  "y":445},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"397a5a92d8c6460388de6216b8d317e0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":340,
              "y":485},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45012a2ce4b74f819f2476f0ec3260ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":340,
                  "y":485},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"58f0961cc0c040f695e3a7f0da843b8e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":370,
              "y":485},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a680ede2fad74387ba7c1deb61c2fa79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":370,
                  "y":485},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"51b38a784dec42c7a333193500fa3e53",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":400,
              "y":485},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da881062fc22481dbf0e6f8bf7fdcbce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":400,
                  "y":485},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"8476a325aa314ae68b6b93f9ecfff3f1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":430,
              "y":485},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"836604c83691432fba34d3e56b441eb5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":430,
                  "y":485},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"cd2dac8784044dee8849609885144c0d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":460,
              "y":485},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82d0c320c0445b68087ed1c4e54051d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":460,
                  "y":485},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"cbf298b51f9a44fdb38d5fdd00331848",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":340,
              "y":525},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79f73a484cd749dba7dda4d14a8dbd89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":340,
                  "y":525},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"9f5f8dc6251b4ac196fec93b8f6567d4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":370,
              "y":525},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"866d7f426fec4c35b6e395ba4fb5af34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":370,
                  "y":525},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"3418491df33048beb8a0282fd6f9bad1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":400,
              "y":525},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b5516dd73a74980bae18f46b0361e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":400,
                  "y":525},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"74b4dd091049427ebd83083999224819",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":430,
              "y":525},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"735cde779248495ababe7208f8524457",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":430,
                  "y":525},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"839943ae843c40d59677dbfc99f0b7c1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":460,
              "y":525},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eef56ab199e9408bb774779df9e264c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":460,
                  "y":525},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/评价/u45.png"}},
{
          "id":"40285a6b0f83439db24ced3136c9b047",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":460,
              "height":70}},
          "adaptiveStyles":{
},
          "placeholderText":"写下购买体会和使用感受来帮助其他小伙伴~"}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "2fcded345ca14188aaf5fa2d2f0e5f01":{
      "scriptId":"u0"},
    "a648e58fa3a54943b518cf589ae2ee37":{
      "scriptId":"u1"},
    "7d02496f1ff44625bff27e85262326b4":{
      "scriptId":"u2"},
    "c117922efbc44c8884db0f6b437a3f46":{
      "scriptId":"u3"},
    "9c51464535184568a4f52b083304d3fe":{
      "scriptId":"u4"},
    "422075541d56411c9bc1eb60f008fcd7":{
      "scriptId":"u5",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u6"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u7"}},
    "00673295c634488b8ca36f2c1de3cb5d":{
      "scriptId":"u8"},
    "fcb13fe6150e40e5a4cbd20e6393d41c":{
      "scriptId":"u9"},
    "3534c4728e99470491e4f816358d7f89":{
      "scriptId":"u10"},
    "8db091a98108440f9d8d0810ce6b1ff9":{
      "scriptId":"u11"},
    "beac2dc8e8bc46b4933ebe04b9ce518a":{
      "scriptId":"u12"},
    "cdeb165bff284ad88d2498365f9983e0":{
      "scriptId":"u13"},
    "aac2216cbc484cf484832247ab7d9483":{
      "scriptId":"u14"},
    "85ba294c3d5c4e71b30d67cbd8108a1e":{
      "scriptId":"u15"},
    "7ebcc6bbda154480855448b3750bc968":{
      "scriptId":"u16"},
    "9ff66edfc8ae484a8515755da88faa47":{
      "scriptId":"u17"},
    "7048b9ae766c482dbb67a056533c512c":{
      "scriptId":"u18"},
    "73a0b26ba7c44da28cfd012095844205":{
      "scriptId":"u19"},
    "abae425e32d44d79b11a3089ec9e2143":{
      "scriptId":"u20"},
    "00c0d8bd9ac145848dc083823016de48":{
      "scriptId":"u21"},
    "410cbc576aba46569eec708706ca5a24":{
      "scriptId":"u22"},
    "8c4f55195123462d9dcb86f4c48eb9e4":{
      "scriptId":"u23"},
    "45290c7d7f884a0bbaf7f751e8b1c034":{
      "scriptId":"u24"},
    "a58e3a8d075046988b09c6dd496a924f":{
      "scriptId":"u25"},
    "636fd57735e2472db8e9bb8b2bd5ff0a":{
      "scriptId":"u26"},
    "09f097b934d048ba831b45907e5b471d":{
      "scriptId":"u27"},
    "9917c16d896c46978b30971aa8d9a31a":{
      "scriptId":"u28"},
    "dd6d7a1c92424402ae497c6f675a2a37":{
      "scriptId":"u29"},
    "8a2e9da29a7145aca1dea9d5a5f2de74":{
      "scriptId":"u30"},
    "1bfeb51680f04fcb989fedf789eba7a3":{
      "scriptId":"u31"},
    "1ab35b78afae4c0091942336922d39ca":{
      "scriptId":"u32"},
    "6c3636be0144436fa87b73ba90cce563":{
      "scriptId":"u33"},
    "450eea5f09bb4f458df96f14679590ba":{
      "scriptId":"u34"},
    "c56a444f4f9441f292339e37e7751bba":{
      "scriptId":"u35"},
    "bd43c56a4b2b4c2fa2fe1ec20f7d6ac7":{
      "scriptId":"u36"},
    "26a4f2bff5a649b89acb87800df156c1":{
      "scriptId":"u37"},
    "1c970eff57ed4406835478e3c025187b":{
      "scriptId":"u38"},
    "8f104b4041f849c4af76964d343c9293":{
      "scriptId":"u39"},
    "c35e101bca724c4392fbcb84bbdfe5e3":{
      "scriptId":"u40"},
    "14b1d55e63a44f789d465faec8225f63":{
      "scriptId":"u41"},
    "8b1af6cce06d4ab2818dec30b2cb34c1":{
      "scriptId":"u42"},
    "e226c90023054bbaaf23b471aeeaa0d4":{
      "scriptId":"u43"},
    "8251eb93f0ac4f378c0e0f5d4ff61e5d":{
      "scriptId":"u44"},
    "e1a831896a144a409f55bc5fd50af0e7":{
      "scriptId":"u45"},
    "17f49326a4024b88a5ba3fcae5c08c9d":{
      "scriptId":"u46"},
    "30c2aca2d8bd4e548b31892c031c7a73":{
      "scriptId":"u47"},
    "f6173348d9fe47f5bc224eed53ab64c1":{
      "scriptId":"u48"},
    "143c5b1df05c4542a79c1e7b1c0576b1":{
      "scriptId":"u49"},
    "46f4570bd4bb4a628e03455a0e38ae95":{
      "scriptId":"u50"},
    "acba019f5dce4e99ac503ca8f8c2a589":{
      "scriptId":"u51"},
    "794b46c959f545ab8ade5731b0b15f0c":{
      "scriptId":"u52"},
    "763d2f1da5d3450d86910a782e3dc0e0":{
      "scriptId":"u53"},
    "f26b2b84af184cd58a9a14ab66db322e":{
      "scriptId":"u54"},
    "397a5a92d8c6460388de6216b8d317e0":{
      "scriptId":"u55"},
    "45012a2ce4b74f819f2476f0ec3260ae":{
      "scriptId":"u56"},
    "58f0961cc0c040f695e3a7f0da843b8e":{
      "scriptId":"u57"},
    "a680ede2fad74387ba7c1deb61c2fa79":{
      "scriptId":"u58"},
    "51b38a784dec42c7a333193500fa3e53":{
      "scriptId":"u59"},
    "da881062fc22481dbf0e6f8bf7fdcbce":{
      "scriptId":"u60"},
    "8476a325aa314ae68b6b93f9ecfff3f1":{
      "scriptId":"u61"},
    "836604c83691432fba34d3e56b441eb5":{
      "scriptId":"u62"},
    "cd2dac8784044dee8849609885144c0d":{
      "scriptId":"u63"},
    "b82d0c320c0445b68087ed1c4e54051d":{
      "scriptId":"u64"},
    "cbf298b51f9a44fdb38d5fdd00331848":{
      "scriptId":"u65"},
    "79f73a484cd749dba7dda4d14a8dbd89":{
      "scriptId":"u66"},
    "9f5f8dc6251b4ac196fec93b8f6567d4":{
      "scriptId":"u67"},
    "866d7f426fec4c35b6e395ba4fb5af34":{
      "scriptId":"u68"},
    "3418491df33048beb8a0282fd6f9bad1":{
      "scriptId":"u69"},
    "1b5516dd73a74980bae18f46b0361e5f":{
      "scriptId":"u70"},
    "74b4dd091049427ebd83083999224819":{
      "scriptId":"u71"},
    "735cde779248495ababe7208f8524457":{
      "scriptId":"u72"},
    "839943ae843c40d59677dbfc99f0b7c1":{
      "scriptId":"u73"},
    "eef56ab199e9408bb774779df9e264c0":{
      "scriptId":"u74"},
    "40285a6b0f83439db24ced3136c9b047":{
      "scriptId":"u75"}}});