$axure.loadCurrentPage({
  "url":"选择时间.html",
  "generationDate":new Date(1470576994432.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"046c8a876663437787cbe8fb82a4e545",
    "type":"Axure:Page",
    "name":"选择时间",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"21d467f8aa954b5c99ed864adb7ee40f",
          "label":"详细板块",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0x7F000000},
            "location":{
              "x":10,
              "y":-10},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0beb009058324b97a3f1261fde38e60d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0x7F000000},
                "location":{
                  "x":10,
                  "y":-10},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/分享页/详细板块_u0.png"}},
{
          "id":"2fbc3525a8d54176a647662be52e1d67",
          "label":"详细板块",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xE5FFFFFF},
            "location":{
              "x":10,
              "y":320},
            "size":{
              "width":480,
              "height":270},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4eefe567bfd45579c02abb79511ff4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xE5FFFFFF},
                "location":{
                  "x":10,
                  "y":320},
                "size":{
                  "width":480,
                  "height":270},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择时间/详细板块_u2.png"}},
{
          "id":"359281fab3514b5d9d6f704b6f43e5d7",
          "label":"详细板块",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":270},
            "size":{
              "width":240,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5acb64a6c266418ca053e671b9c8f710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":270},
                "size":{
                  "width":240,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/所在区域/详细板块_u4.png"}},
{
          "id":"004e1545d8ee4fdc9f5d5505b0a239dc",
          "label":"详细板块",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":250,
              "y":270},
            "size":{
              "width":240,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b426f1bf7df949df94cebfa7e4b99d2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":250,
                  "y":270},
                "size":{
                  "width":240,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 返回",
                      "target":{
                        "targetType":"backUrl",
                        "includeVariables":false},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/所在区域/详细板块_u4.png"}},
{
          "id":"8145a8c5d4294b059218da7e6da00f3c",
          "label":"详细板块",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":450},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e8aa40fbc3644a48ae2d709f873b703",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":450},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"1c56f9a1b24041e0aa58d7da286b474a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "lineSpacing":"50px",
            "location":{
              "x":30,
              "y":350},
            "size":{
              "width":140,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65c67ada747144f3b0881f964db04c7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "lineSpacing":"50px",
                "location":{
                  "x":30,
                  "y":350},
                "size":{
                  "width":140,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d0506bb88ca407980f3ea6bda92c6d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "lineSpacing":"50px",
            "location":{
              "x":180,
              "y":350},
            "size":{
              "width":140,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"233f84f4d9eb4584a89b8cdaee441d69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "lineSpacing":"50px",
                "location":{
                  "x":180,
                  "y":350},
                "size":{
                  "width":140,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec85cae5d0b340e785b0ff27fe67afa1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "lineSpacing":"50px",
            "location":{
              "x":330,
              "y":350},
            "size":{
              "width":140,
              "height":250}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a2636bac26e47c2a1ce1844f7f182fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "lineSpacing":"50px",
                "location":{
                  "x":330,
                  "y":350},
                "size":{
                  "width":140,
                  "height":250}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "21d467f8aa954b5c99ed864adb7ee40f":{
      "scriptId":"u0"},
    "0beb009058324b97a3f1261fde38e60d":{
      "scriptId":"u1"},
    "2fbc3525a8d54176a647662be52e1d67":{
      "scriptId":"u2"},
    "d4eefe567bfd45579c02abb79511ff4b":{
      "scriptId":"u3"},
    "359281fab3514b5d9d6f704b6f43e5d7":{
      "scriptId":"u4"},
    "5acb64a6c266418ca053e671b9c8f710":{
      "scriptId":"u5"},
    "004e1545d8ee4fdc9f5d5505b0a239dc":{
      "scriptId":"u6"},
    "b426f1bf7df949df94cebfa7e4b99d2d":{
      "scriptId":"u7"},
    "8145a8c5d4294b059218da7e6da00f3c":{
      "scriptId":"u8"},
    "1e8aa40fbc3644a48ae2d709f873b703":{
      "scriptId":"u9"},
    "1c56f9a1b24041e0aa58d7da286b474a":{
      "scriptId":"u10"},
    "65c67ada747144f3b0881f964db04c7c":{
      "scriptId":"u11"},
    "1d0506bb88ca407980f3ea6bda92c6d3":{
      "scriptId":"u12"},
    "233f84f4d9eb4584a89b8cdaee441d69":{
      "scriptId":"u13"},
    "ec85cae5d0b340e785b0ff27fe67afa1":{
      "scriptId":"u14"},
    "8a2636bac26e47c2a1ce1844f7f182fb":{
      "scriptId":"u15"}}});