$axure.loadCurrentPage({
  "url":"服务端-更多.html",
  "generationDate":new Date(1470577061809.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"051aa23274914117842e7a7bbadd791a",
    "type":"Axure:Page",
    "name":"服务端-更多",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9c4562b2742044d3833da5791ce60bf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"321a655d3f0b458bbb3c146bd548e31e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u0.png"}},
{
          "id":"30318c9ceab845509e40164a44aaa014",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"801d6276470245218828701eac9620de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/重置密码/u6.png"}},
{
          "id":"0d786aaa94994f1da3921c40a7e8159b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":165,
              "y":12},
            "size":{
              "width":170,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"706d2028cf1340a099b572e722193305",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":165,
                  "y":12},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1232c73dcda24e37a4b1f516f2561a48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8b9feb70d73a47bdac5b096d71bb9dab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u6.png"}},
{
          "id":"071d6e8edf424e48a1ab96682df306ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"50px",
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":240,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49577b398cf94060a0b1bf881ba3230c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"50px",
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":240,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a67f7bd58274e0a93d20e8f586c8bde",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":105},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页/u10_line.png"}},
{
          "id":"8ab552a2c66f4679bc4fb0e5917f8242",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"50px",
            "location":{
              "x":400,
              "y":60},
            "size":{
              "width":80,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d428ded36fac49288b016dc5b032ee6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"50px",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":80,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aa9ed80c960c4410962490d73d5f3511",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
          "id":"bff1953d26424afd8fbd36d98f10aa71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":65},
            "size":{
              "width":460,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5078b02627a74fdc8f1adac46378feca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":65},
                "size":{
                  "width":460,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 清除缓存",
                      "objectsToFades":[{
                          "objectPath":["3b431dab13de4744a72b140377b0288e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f079aaabbd064b868697b6f42f037e3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":115},
            "size":{
              "width":460,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7d37f65a0834eed8bd2717ca08933da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":115},
                "size":{
                  "width":460,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于我们",
                      "target":{
                        "targetType":"page",
                        "url":"关于我们.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f246f9d6ef664fe1b5f423121729fd8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "location":{
              "x":20,
              "y":190},
            "size":{
              "width":460,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04cbe3e140224483b81f9b28cbfcacd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "location":{
                  "x":20,
                  "y":190},
                "size":{
                  "width":460,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录页",
                      "target":{
                        "targetType":"page",
                        "url":"登录页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/服务端-更多/u20.png"}},
{
          "id":"3b431dab13de4744a72b140377b0288e",
          "label":"清除缓存",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"b5784f2a5202422d90df97823febee38",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"568ebe32eb66494e9ef5743eb429c176",
                  "label":"",
                  "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "fill":{
                      "fillType":"solid",
                      "color":0x7F000000},
                    "size":{
                      "width":480,
                      "height":600},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x7F000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5615a68d7d6f4301a952cbea1f57c26d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "fill":{
                          "fillType":"solid",
                          "color":0x7F000000},
                        "size":{
                          "width":480,
                          "height":600},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x7F000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/服务端-更多/u23.png"}},
{
                  "id":"9cb42d453413428c9417928d7e4a0283",
                  "label":"",
                  "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":140,
                      "y":190},
                    "size":{
                      "width":200,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"de416b5d3ba346dd83ece29a05d9e28e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":140,
                          "y":190},
                        "size":{
                          "width":200,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/服务端-更多/u25.png"}},
{
                  "id":"e636e56cc1b94f35854d0627888871d0",
                  "label":"",
                  "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":240},
                    "size":{
                      "width":200,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/服务端-更多/u27_line.png"}},
{
                  "id":"983cd7e02a8346dcbfcf3291ac17b157",
                  "label":"",
                  "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":235,
                      "y":245},
                    "size":{
                      "width":10,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/服务端-更多/u28_line.png"}},
{
                  "id":"3ff957980f854b079cda0ca280ea1e61",
                  "label":"",
                  "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "lineSpacing":"50px",
                    "location":{
                      "x":140,
                      "y":195},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"96faa2a1a9e24db79af23324af7754b9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "lineSpacing":"50px",
                        "location":{
                          "x":140,
                          "y":195},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"80d98d86aa424d559dcf51064f80c018",
                  "label":"",
                  "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "lineSpacing":"50px",
                    "location":{
                      "x":140,
                      "y":245},
                    "size":{
                      "width":95,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"166a3e5df47f458898fd9c6672a7c9cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "lineSpacing":"50px",
                        "location":{
                          "x":140,
                          "y":245},
                        "size":{
                          "width":95,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 清除缓存",
                              "objectsToFades":[{
                                  "objectPath":["3b431dab13de4744a72b140377b0288e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e72156bc4c864e0fb5e8a63e2ff049ca",
                  "label":"",
                  "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF990000,
                      "opacity":1},
                    "lineSpacing":"50px",
                    "location":{
                      "x":245,
                      "y":245},
                    "size":{
                      "width":95,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72a6a8833cd94ebf88c1dc52acd9bef0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"3b431dab13de4744a72b140377b0288e",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF990000,
                          "opacity":1},
                        "lineSpacing":"50px",
                        "location":{
                          "x":245,
                          "y":245},
                        "size":{
                          "width":95,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 清除缓存",
                              "objectsToFades":[{
                                  "objectPath":["3b431dab13de4744a72b140377b0288e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "9c4562b2742044d3833da5791ce60bf9":{
      "scriptId":"u0"},
    "321a655d3f0b458bbb3c146bd548e31e":{
      "scriptId":"u1"},
    "30318c9ceab845509e40164a44aaa014":{
      "scriptId":"u2"},
    "801d6276470245218828701eac9620de":{
      "scriptId":"u3"},
    "0d786aaa94994f1da3921c40a7e8159b":{
      "scriptId":"u4"},
    "706d2028cf1340a099b572e722193305":{
      "scriptId":"u5"},
    "1232c73dcda24e37a4b1f516f2561a48":{
      "scriptId":"u6"},
    "8b9feb70d73a47bdac5b096d71bb9dab":{
      "scriptId":"u7"},
    "071d6e8edf424e48a1ab96682df306ae":{
      "scriptId":"u8"},
    "49577b398cf94060a0b1bf881ba3230c":{
      "scriptId":"u9"},
    "6a67f7bd58274e0a93d20e8f586c8bde":{
      "scriptId":"u10"},
    "8ab552a2c66f4679bc4fb0e5917f8242":{
      "scriptId":"u11"},
    "d428ded36fac49288b016dc5b032ee6f":{
      "scriptId":"u12"},
    "aa9ed80c960c4410962490d73d5f3511":{
      "scriptId":"u13",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u14"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u15"}},
    "bff1953d26424afd8fbd36d98f10aa71":{
      "scriptId":"u16"},
    "5078b02627a74fdc8f1adac46378feca":{
      "scriptId":"u17"},
    "f079aaabbd064b868697b6f42f037e3d":{
      "scriptId":"u18"},
    "d7d37f65a0834eed8bd2717ca08933da":{
      "scriptId":"u19"},
    "f246f9d6ef664fe1b5f423121729fd8c":{
      "scriptId":"u20"},
    "04cbe3e140224483b81f9b28cbfcacd9":{
      "scriptId":"u21"},
    "3b431dab13de4744a72b140377b0288e":{
      "scriptId":"u22"},
    "568ebe32eb66494e9ef5743eb429c176":{
      "scriptId":"u23"},
    "5615a68d7d6f4301a952cbea1f57c26d":{
      "scriptId":"u24"},
    "9cb42d453413428c9417928d7e4a0283":{
      "scriptId":"u25"},
    "de416b5d3ba346dd83ece29a05d9e28e":{
      "scriptId":"u26"},
    "e636e56cc1b94f35854d0627888871d0":{
      "scriptId":"u27"},
    "983cd7e02a8346dcbfcf3291ac17b157":{
      "scriptId":"u28"},
    "3ff957980f854b079cda0ca280ea1e61":{
      "scriptId":"u29"},
    "96faa2a1a9e24db79af23324af7754b9":{
      "scriptId":"u30"},
    "80d98d86aa424d559dcf51064f80c018":{
      "scriptId":"u31"},
    "166a3e5df47f458898fd9c6672a7c9cc":{
      "scriptId":"u32"},
    "e72156bc4c864e0fb5e8a63e2ff049ca":{
      "scriptId":"u33"},
    "72a6a8833cd94ebf88c1dc52acd9bef0":{
      "scriptId":"u34"}}});