$axure.loadCurrentPage({
  "url":"订单详细.html",
  "generationDate":new Date(1470577061106.15),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7f46f0ff5625485894ffab2d8a23ab4c",
    "type":"Axure:Page",
    "name":"订单详细",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3cde85be85524ae09e14ded8ad599d45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fd5b4f97c8a4729a5eceef4f9b3d9d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单详细/u0.png"}},
{
          "id":"e6b55a0e91ce4e488a091d10fc7fe7fc",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ffd5ad3a59194bea8729e6cdb33b0dcf",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"30266d4e6c9446ee948922ac23b12f82",
                  "label":"",
                  "parentDynamicPanel":"e6b55a0e91ce4e488a091d10fc7fe7fc",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6252f81472d3485ab472f8987aae8160",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6b55a0e91ce4e488a091d10fc7fe7fc",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录页/u2.png"}},
{
                  "id":"e774875ec1b84b458821104e227312ae",
                  "label":"",
                  "parentDynamicPanel":"e6b55a0e91ce4e488a091d10fc7fe7fc",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
                  "id":"179fbd89e0bd4c489e2d28b5b5d2fb53",
                  "label":"",
                  "parentDynamicPanel":"e6b55a0e91ce4e488a091d10fc7fe7fc",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc3db9d413d1403498ea54e1f8f72189",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"e6b55a0e91ce4e488a091d10fc7fe7fc",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d536f5e593614b5f977920ebf5bd8e48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":330,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c65969a5670745159b55a693898eae70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":330,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"053debf2b1ff45f3b5255eb568e1b386",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "lineSpacing":"30px",
            "location":{
              "x":320,
              "y":60},
            "size":{
              "width":160,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a7ba3dad6ec406ab2592fc208be2625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "lineSpacing":"30px",
                "location":{
                  "x":320,
                  "y":60},
                "size":{
                  "width":160,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"21af1d5cff564543adebc6ae94884c20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":100},
            "size":{
              "width":330,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5e515a149b04b6bb2ff6a467cfe678a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":100},
                "size":{
                  "width":330,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "3cde85be85524ae09e14ded8ad599d45":{
      "scriptId":"u0"},
    "5fd5b4f97c8a4729a5eceef4f9b3d9d8":{
      "scriptId":"u1"},
    "e6b55a0e91ce4e488a091d10fc7fe7fc":{
      "scriptId":"u2"},
    "30266d4e6c9446ee948922ac23b12f82":{
      "scriptId":"u3"},
    "6252f81472d3485ab472f8987aae8160":{
      "scriptId":"u4"},
    "e774875ec1b84b458821104e227312ae":{
      "scriptId":"u5",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u6"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u7"}},
    "179fbd89e0bd4c489e2d28b5b5d2fb53":{
      "scriptId":"u8"},
    "cc3db9d413d1403498ea54e1f8f72189":{
      "scriptId":"u9"},
    "d536f5e593614b5f977920ebf5bd8e48":{
      "scriptId":"u10"},
    "c65969a5670745159b55a693898eae70":{
      "scriptId":"u11"},
    "053debf2b1ff45f3b5255eb568e1b386":{
      "scriptId":"u12"},
    "8a7ba3dad6ec406ab2592fc208be2625":{
      "scriptId":"u13"},
    "21af1d5cff564543adebc6ae94884c20":{
      "scriptId":"u14"},
    "a5e515a149b04b6bb2ff6a467cfe678a":{
      "scriptId":"u15"}}});