$axure.loadCurrentPage({
  "url":"登录页.html",
  "generationDate":new Date(1470577059604.07),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b013180cf3054bbd81782f9bedebe311",
    "type":"Axure:Page",
    "name":"登录页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"add8c8c9765c42b89d11bbcb40b168b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"150d5556c4cc4df2961784d23a19787f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u0.png"}},
{
          "id":"e3605196e2b24dc9a715206c467ea447",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"206d3b6200574f1b8df348619c3853f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u2.png"}},
{
          "id":"0a0fbc22132a446c8c215db9fa40b721",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":165,
              "y":12},
            "size":{
              "width":170,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18dc4dd5269b4281b4fc6fcafbd9cd85",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":165,
                  "y":12},
                "size":{
                  "width":170,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14c71c5b7d9e45ccb8e8936bdd3fbceb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b07d03b20c6c4f7898245e49776558d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u6.png"}},
{
          "id":"19b64deb115c45a48be1e3a62c3326e7",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":46,
              "y":60},
            "size":{
              "width":434,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 键盘,<br>(Image) 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["34c6842b6418467fb89a08b38b012b07"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["60b660efc86b48b7b113c7dcc081f062"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "placeholderText":"账号"},
{
          "id":"3d188184299e4620ade0a637651b7c6c",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":46,
              "y":110},
            "size":{
              "width":434,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 登录按钮,<br>(形状)",
                      "objectsToFades":[{
                          "objectPath":["2fd897baa8114e1baae66c4a817f07ad"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["cab18322703b438fac7c643278fe57f5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "placeholderText":"密码"},
{
          "id":"5219cc80e08d416292252909a35025c1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":95},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页/u10_line.png"}},
{
          "id":"38d1cdc165284bc4a22a3203ee26abbd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":180},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e74f218e15544ea89892c84ca0e784f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":180},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 忘记密码",
                      "target":{
                        "targetType":"page",
                        "url":"忘记密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c81459e953e4d99beb76eb1eee7d101",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":20,
              "y":230},
            "size":{
              "width":460,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52b1e2d830394c24a9603c769ec542d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":20,
                  "y":230},
                "size":{
                  "width":460,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u13.png"}},
{
          "id":"4c4847554a6147d68f4eb4fc2049e73a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":115},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e07e265015f8449791095aaa2b264adf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":115},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u15.png"}},
{
          "id":"49ca088e278e4a4e937dddfa8575e5bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":65},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c817baaba024a068047c94590996fc2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":65},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u17.png"}},
{
          "id":"34c6842b6418467fb89a08b38b012b07",
          "label":"键盘",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":325},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ef5b6e7d511c4752bfed9ae26c4814ae",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"60b660efc86b48b7b113c7dcc081f062",
                  "label":"",
                  "parentDynamicPanel":"34c6842b6418467fb89a08b38b012b07",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":479,
                      "height":276}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e5fed0f59d9d4c9b9b2d4e5b105fb63d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"34c6842b6418467fb89a08b38b012b07",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":479,
                          "height":276}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录页/u20.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"2fd897baa8114e1baae66c4a817f07ad",
          "label":"登录按钮",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":20,
              "y":230},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ed6b0823fa27444b97507a191b09e17f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cab18322703b438fac7c643278fe57f5",
                  "label":"",
                  "parentDynamicPanel":"2fd897baa8114e1baae66c4a817f07ad",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "size":{
                      "width":460,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d3ce9b3819344848a5d6df1aa108e469",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2fd897baa8114e1baae66c4a817f07ad",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "size":{
                          "width":460,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的业务",
                              "target":{
                                "targetType":"page",
                                "url":"我的业务.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录页/u23.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"08c0248044ea4549b1a5af8a3daf80cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba87b78af3be44c195012f47b0ecfaac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "add8c8c9765c42b89d11bbcb40b168b4":{
      "scriptId":"u0"},
    "150d5556c4cc4df2961784d23a19787f":{
      "scriptId":"u1"},
    "e3605196e2b24dc9a715206c467ea447":{
      "scriptId":"u2"},
    "206d3b6200574f1b8df348619c3853f6":{
      "scriptId":"u3"},
    "0a0fbc22132a446c8c215db9fa40b721":{
      "scriptId":"u4"},
    "18dc4dd5269b4281b4fc6fcafbd9cd85":{
      "scriptId":"u5"},
    "14c71c5b7d9e45ccb8e8936bdd3fbceb":{
      "scriptId":"u6"},
    "b07d03b20c6c4f7898245e49776558d4":{
      "scriptId":"u7"},
    "19b64deb115c45a48be1e3a62c3326e7":{
      "scriptId":"u8"},
    "3d188184299e4620ade0a637651b7c6c":{
      "scriptId":"u9"},
    "5219cc80e08d416292252909a35025c1":{
      "scriptId":"u10"},
    "38d1cdc165284bc4a22a3203ee26abbd":{
      "scriptId":"u11"},
    "e74f218e15544ea89892c84ca0e784f3":{
      "scriptId":"u12"},
    "5c81459e953e4d99beb76eb1eee7d101":{
      "scriptId":"u13"},
    "52b1e2d830394c24a9603c769ec542d4":{
      "scriptId":"u14"},
    "4c4847554a6147d68f4eb4fc2049e73a":{
      "scriptId":"u15"},
    "e07e265015f8449791095aaa2b264adf":{
      "scriptId":"u16"},
    "49ca088e278e4a4e937dddfa8575e5bf":{
      "scriptId":"u17"},
    "1c817baaba024a068047c94590996fc2":{
      "scriptId":"u18"},
    "34c6842b6418467fb89a08b38b012b07":{
      "scriptId":"u19"},
    "60b660efc86b48b7b113c7dcc081f062":{
      "scriptId":"u20"},
    "e5fed0f59d9d4c9b9b2d4e5b105fb63d":{
      "scriptId":"u21"},
    "2fd897baa8114e1baae66c4a817f07ad":{
      "scriptId":"u22"},
    "cab18322703b438fac7c643278fe57f5":{
      "scriptId":"u23"},
    "d3ce9b3819344848a5d6df1aa108e469":{
      "scriptId":"u24"},
    "08c0248044ea4549b1a5af8a3daf80cc":{
      "scriptId":"u25"},
    "ba87b78af3be44c195012f47b0ecfaac":{
      "scriptId":"u26"}}});