$axure.loadCurrentPage({
  "url":"定位.html",
  "generationDate":new Date(1470576988179.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8d528ebb7ab448e7a601d7542c5a2790",
    "type":"Axure:Page",
    "name":"定位",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2cdcbdd0c2664bcba2d4d5d09c4fbc4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6152ca6cd794ef28747749ebca3db2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u2.png"}},
{
          "id":"bec0b4dfa3484824965d468abcb9d4c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef027e44404349faa7ac236d8cd0c5dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85be9775375946fe848b97ce2220dfc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":20,
              "y":100},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba17df784204c0a99415c77ecf8128e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":100},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"80a8d33d844a4aa49c8d8920be9931b8",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":460,
              "y":140},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":460,
          "fixedVertical":"top",
          "fixedMarginVertical":140,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"19f401c4e13e4500bfc6b4bbe255aeca",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"37bf904317634a12b51f9e29b8560a44",
                  "label":"",
                  "parentDynamicPanel":"80a8d33d844a4aa49c8d8920be9931b8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "lineSpacing":"18px",
                    "size":{
                      "width":30,
                      "height":468}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1633ad316c8d4d84baa5d43dd1371e7b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"80a8d33d844a4aa49c8d8920be9931b8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "lineSpacing":"18px",
                        "size":{
                          "width":30,
                          "height":468}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"d180780c80cb442b8bdc846d0a205033",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"552aa3222a7a4146bc09c9a35b459d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":150},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16e997be94104206adf3a98e4d71fe92",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"41164bda3d8c43668ae6e2805089254d",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2b439f0ece4c456f8fa466c02fa3d62c",
                  "label":"",
                  "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4294bf182f2b49669805f58f6cc802dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"267018f44c244ed2bb31d3783da915d2",
                  "label":"",
                  "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "location":{
                      "x":40,
                      "y":10},
                    "size":{
                      "width":40,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"796f40a09a7347bb9792e0900dbafa8c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "location":{
                          "x":40,
                          "y":10},
                        "size":{
                          "width":40,
                          "height":30},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u28.png"}},
{
                  "id":"dc5cb3845b834e49a23c6f6daa082469",
                  "label":"",
                  "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                  "panelIndex":0,
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":80,
                      "y":10},
                    "size":{
                      "width":390,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "placeholderText":"请输入城市名或首字母查询"},
{
                  "id":"3fc1f87b770a4880aad3c2a2bf659b8b",
                  "label":"",
                  "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":50,
                      "y":15},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d750ac840f43425a8d2f31c1859ce86c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":50,
                          "y":15},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u30.png"}},
{
                  "id":"135422635c274dfa890887694755d5c5",
                  "label":"",
                  "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"30px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "lineSpacing":"30px",
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40afd3026d444b52b128cc9289a7ad55",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"16e997be94104206adf3a98e4d71fe92",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"30px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "lineSpacing":"30px",
                        "location":{
                          "x":10,
                          "y":10},
                        "size":{
                          "width":30,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 主页",
                              "target":{
                                "targetType":"page",
                                "url":"主页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"1a028d3565054e879da4e173a2beeca0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":190},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc2755863cfe4d7e9adf2c9fb5ea3716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":190},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"88a2de36b3924f21a044abb1362068a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":168,
              "y":190},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7337cb6dbc52487f97f1366d9df5f394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":168,
                  "y":190},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"1a56cab344424b56b0486a76635c2a63",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":316,
              "y":190},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"387dfa14327740ad8ab448c5a153c686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":316,
                  "y":190},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"72f8127e496e49a0bcdd6792037b47a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"231ca50470a04cc39cff75fa3940b733",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"8d2898fc4c904979b0ea150914d5b22f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":168,
              "y":240},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46d10f4114c64a8eb47c148effb9bd26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":168,
                  "y":240},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"ab8a880ec94346be88da733ae70b266c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":316,
              "y":240},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fce124b3290442369fe0362c686ed26a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":316,
                  "y":240},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"782954ec0e5b446fa6cae31ca1bd3222",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":20,
              "y":290},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e246e1b2dc2409b9e21e77d07143b33",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":20,
                  "y":290},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"de2c471ecacb4b6383e6e8391fb7932c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":168,
              "y":290},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58c767fc7a96475ab5c520de9e51aa1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":168,
                  "y":290},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"95d0b295ee58430b99bc2b3c75a72302",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":316,
              "y":290},
            "size":{
              "width":140,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a32a9d069fd4ce594af4524a49624dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":316,
                  "y":290},
                "size":{
                  "width":140,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/定位/u4.png"}},
{
          "id":"efd7503de13d4bd7b5b9cbf08d408ff8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"50px",
            "location":{
              "x":20,
              "y":350},
            "size":{
              "width":200,
              "height":450}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d074e893f524849912a9aa145a0d30b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"50px",
                "location":{
                  "x":20,
                  "y":350},
                "size":{
                  "width":200,
                  "height":450}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"121c1493f3ed4788b2db0cec0888dcb9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":445},
            "size":{
              "width":436,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定位/u41_line.png"}},
{
          "id":"9d392948b67e4103b997c6daf35e77a8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":495},
            "size":{
              "width":436,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定位/u41_line.png"}},
{
          "id":"8a59bffae0f8411a9930bc314ba7aa45",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":545},
            "size":{
              "width":436,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定位/u41_line.png"}},
{
          "id":"5f836c3c4896469993491b5598342443",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":595},
            "size":{
              "width":436,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定位/u41_line.png"}},
{
          "id":"b3348d8865ba4883ba637428ca218628",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":645},
            "size":{
              "width":436,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定位/u41_line.png"}},
{
          "id":"744579461e474d52a34ebc052033f31f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":695},
            "size":{
              "width":436,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定位/u41_line.png"}},
{
          "id":"7a7a4b81760e4ade9d18b24cc07b9f94",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":745},
            "size":{
              "width":436,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/定位/u41_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2cdcbdd0c2664bcba2d4d5d09c4fbc4b":{
      "scriptId":"u0"},
    "a6152ca6cd794ef28747749ebca3db2c":{
      "scriptId":"u1"},
    "bec0b4dfa3484824965d468abcb9d4c1":{
      "scriptId":"u2"},
    "ef027e44404349faa7ac236d8cd0c5dd":{
      "scriptId":"u3"},
    "85be9775375946fe848b97ce2220dfc2":{
      "scriptId":"u4"},
    "8ba17df784204c0a99415c77ecf8128e":{
      "scriptId":"u5"},
    "80a8d33d844a4aa49c8d8920be9931b8":{
      "scriptId":"u6"},
    "37bf904317634a12b51f9e29b8560a44":{
      "scriptId":"u7"},
    "1633ad316c8d4d84baa5d43dd1371e7b":{
      "scriptId":"u8"},
    "d180780c80cb442b8bdc846d0a205033":{
      "scriptId":"u9"},
    "552aa3222a7a4146bc09c9a35b459d96":{
      "scriptId":"u10"},
    "16e997be94104206adf3a98e4d71fe92":{
      "scriptId":"u11"},
    "2b439f0ece4c456f8fa466c02fa3d62c":{
      "scriptId":"u12"},
    "4294bf182f2b49669805f58f6cc802dd":{
      "scriptId":"u13"},
    "267018f44c244ed2bb31d3783da915d2":{
      "scriptId":"u14"},
    "796f40a09a7347bb9792e0900dbafa8c":{
      "scriptId":"u15"},
    "dc5cb3845b834e49a23c6f6daa082469":{
      "scriptId":"u16"},
    "3fc1f87b770a4880aad3c2a2bf659b8b":{
      "scriptId":"u17"},
    "d750ac840f43425a8d2f31c1859ce86c":{
      "scriptId":"u18"},
    "135422635c274dfa890887694755d5c5":{
      "scriptId":"u19"},
    "40afd3026d444b52b128cc9289a7ad55":{
      "scriptId":"u20"},
    "1a028d3565054e879da4e173a2beeca0":{
      "scriptId":"u21"},
    "bc2755863cfe4d7e9adf2c9fb5ea3716":{
      "scriptId":"u22"},
    "88a2de36b3924f21a044abb1362068a0":{
      "scriptId":"u23"},
    "7337cb6dbc52487f97f1366d9df5f394":{
      "scriptId":"u24"},
    "1a56cab344424b56b0486a76635c2a63":{
      "scriptId":"u25"},
    "387dfa14327740ad8ab448c5a153c686":{
      "scriptId":"u26"},
    "72f8127e496e49a0bcdd6792037b47a7":{
      "scriptId":"u27"},
    "231ca50470a04cc39cff75fa3940b733":{
      "scriptId":"u28"},
    "8d2898fc4c904979b0ea150914d5b22f":{
      "scriptId":"u29"},
    "46d10f4114c64a8eb47c148effb9bd26":{
      "scriptId":"u30"},
    "ab8a880ec94346be88da733ae70b266c":{
      "scriptId":"u31"},
    "fce124b3290442369fe0362c686ed26a":{
      "scriptId":"u32"},
    "782954ec0e5b446fa6cae31ca1bd3222":{
      "scriptId":"u33"},
    "3e246e1b2dc2409b9e21e77d07143b33":{
      "scriptId":"u34"},
    "de2c471ecacb4b6383e6e8391fb7932c":{
      "scriptId":"u35"},
    "58c767fc7a96475ab5c520de9e51aa1e":{
      "scriptId":"u36"},
    "95d0b295ee58430b99bc2b3c75a72302":{
      "scriptId":"u37"},
    "5a32a9d069fd4ce594af4524a49624dc":{
      "scriptId":"u38"},
    "efd7503de13d4bd7b5b9cbf08d408ff8":{
      "scriptId":"u39"},
    "1d074e893f524849912a9aa145a0d30b":{
      "scriptId":"u40"},
    "121c1493f3ed4788b2db0cec0888dcb9":{
      "scriptId":"u41"},
    "9d392948b67e4103b997c6daf35e77a8":{
      "scriptId":"u42"},
    "8a59bffae0f8411a9930bc314ba7aa45":{
      "scriptId":"u43"},
    "5f836c3c4896469993491b5598342443":{
      "scriptId":"u44"},
    "b3348d8865ba4883ba637428ca218628":{
      "scriptId":"u45"},
    "744579461e474d52a34ebc052033f31f":{
      "scriptId":"u46"},
    "7a7a4b81760e4ade9d18b24cc07b9f94":{
      "scriptId":"u47"}}});