$axure.loadCurrentPage({
  "url":"默认页.html",
  "generationDate":new Date(1470576991166.9),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"29e8339115f94d5880b77f669858f344",
    "type":"Axure:Page",
    "name":"默认页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b07b79d65ad94919acd3b318a55beb45",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":1200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1812c9888cbe46109d39403d1f00f9e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":1200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u0.png"}},
{
          "id":"2a573519c1aa40ba81b891f1f10b7083",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e54a08e77e074b69a460009c1d1098dc",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aa14ba2227674993ab30bf69ae31f0d4",
                  "label":"",
                  "parentDynamicPanel":"2a573519c1aa40ba81b891f1f10b7083",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"572a1cd5611e4ea3ac61962a4391da54",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a573519c1aa40ba81b891f1f10b7083",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"27e373701dae43c781ab8fb4eeee2ead",
                  "label":"",
                  "parentDynamicPanel":"2a573519c1aa40ba81b891f1f10b7083",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9bae87c8ff6d4c6c836677230f3c80c4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2a573519c1aa40ba81b891f1f10b7083",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c0eca7a637f440e782165070440fa8aa",
                  "label":"",
                  "parentDynamicPanel":"2a573519c1aa40ba81b891f1f10b7083",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"0918178aa9594c03b81997f457d2b935",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":200,
              "y":70},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0x7FF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98b6c05716464c409633392f652f7de4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":200,
                  "y":70},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0x7FF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u10.png"}},
{
          "id":"3208e404bcd24a20bd0676caa8457c7f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":225,
              "y":95},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3dfb036bd804ffb8abe7679a3119cf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":225,
                  "y":95},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/默认页/u12.png"}},
{
          "id":"6f55b54e715a47bead8690abeb44c5b8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":180},
            "size":{
              "width":460,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"088d185640004efd86c5d2cb09aee49c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":180},
                "size":{
                  "width":460,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8271bbd5256d4a4da80dabf121ae1cbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":200,
              "y":280},
            "size":{
              "width":100,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bd3eda37cda46ccb5cc51dad1f45138",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":200,
                  "y":280},
                "size":{
                  "width":100,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/默认页/u16.png"}},
{
          "id":"9d0664c2df51475cad48786e4860c898",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":400}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"e27a1d4b8226429c895a51093fb52082",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":400}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"99fa7e0829ae4d149ea1226fbc4e5dce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":360},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u42_line.png"}},
{
          "id":"125764bd222746b0b19f09a72b0fce20",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":360},
            "size":{
              "width":170,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u42_line.png"}},
{
          "id":"660430e732d2480c80018677a808d819",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":190,
              "y":355},
            "size":{
              "width":120,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fb72d750760409ea943be5ce7a385a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":190,
                  "y":355},
                "size":{
                  "width":120,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2576ecc657494b38ae54d2ec793e9248",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":710}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"5d1bdc08a0c441549ade58eca0640054",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":255,
              "y":710}},
          "adaptiveStyles":{
},
          "masterId":"e233cf1f8b7a43da9b4130a7ee7963e4"},
{
          "id":"0b44debb02244e47bca0560d80252fd8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":1035},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u70_line.png"}},
{
          "id":"3ecb51594be74efab7eedc01d1c2e7c7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":1035},
            "size":{
              "width":100,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/默认页/u70_line.png"}},
{
          "id":"169f42e026c04102a6e8b0077c7fbee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "location":{
              "x":20,
              "y":1030},
            "size":{
              "width":460,
              "height":21}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"091e26623791420dbf9dd2adf995abfd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "location":{
                  "x":20,
                  "y":1030},
                "size":{
                  "width":460,
                  "height":21}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}},
    "e233cf1f8b7a43da9b4130a7ee7963e4":{
      "packageId":"e233cf1f8b7a43da9b4130a7ee7963e4",
      "type":"Axure:Master",
      "name":"产品模块",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"19aa459432d34ba1a480d27dff6a8b55",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "size":{
                "width":225,
                "height":300},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFFFFFFF}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"d8eb084c43534ec9ad5dd7379a6b8d21",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "size":{
                    "width":225,
                    "height":300},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFFFFFFF}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/手机外观效果/u211.png",
              "normal~":"images/手机外观效果/u211.png",
              "normal~":"images/手机外观效果/u211.png",
              "normal~":"images/手机外观效果/u211.png"}},
{
            "id":"c58403d5ffe84b3cafc0a406f2422a7e",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "location":{
                "x":10,
                "y":200},
              "size":{
                "width":205,
                "height":40}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"268120e9977b4ecba9091eee1afda6e7",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "location":{
                    "x":10,
                    "y":200},
                  "size":{
                    "width":205,
                    "height":40}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品详细",
                        "target":{
                          "targetType":"page",
                          "url":"产品详细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7f9a58d68d2345c0855a95d54de98bcf",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "location":{
                "x":30,
                "y":30},
              "size":{
                "width":160,
                "height":160}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a10cce0c0bca467eb3e1f3638b8bb751",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "location":{
                    "x":30,
                    "y":30},
                  "size":{
                    "width":160,
                    "height":160}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 产品详细",
                        "target":{
                          "targetType":"page",
                          "url":"产品详细.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/手机外观效果/u215.png",
              "normal~":"images/手机外观效果/u215.png",
              "normal~":"images/手机外观效果/u215.png",
              "normal~":"images/手机外观效果/u215.png"}},
{
            "id":"13ba846806714f0a8e7f25e6b65061bb",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "location":{
                "x":10,
                "y":240},
              "size":{
                "width":205,
                "height":10},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png",
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/手机外观效果/u217_line.png"}},
{
            "id":"bae5226a8e014bed98634919b29d554c",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Bold', 'Applied Font'",
              "fontSize":"16px",
              "fontWeight":"700",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF990000,
                "opacity":1},
              "location":{
                "x":10,
                "y":255},
              "size":{
                "width":205,
                "height":21}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ca0a7d7619c645f19eb35bf7dd9dd523",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Bold', 'Applied Font'",
                  "fontSize":"16px",
                  "fontWeight":"700",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF990000,
                    "opacity":1},
                  "location":{
                    "x":10,
                    "y":255},
                  "size":{
                    "width":205,
                    "height":21}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"9f7783e454f946e191c3fb64dff07c8a",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"12px",
              "foreGroundFill":{
                "fillType":"solid",
                "color":0xFF999999,
                "opacity":1},
              "location":{
                "x":10,
                "y":280},
              "size":{
                "width":205,
                "height":17}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"8f6e93e335bd4f91bbee592acd212a8b",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"12px",
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFF999999,
                    "opacity":1},
                  "location":{
                    "x":10,
                    "y":280},
                  "size":{
                    "width":205,
                    "height":17}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif",
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b07b79d65ad94919acd3b318a55beb45":{
      "scriptId":"u0"},
    "1812c9888cbe46109d39403d1f00f9e0":{
      "scriptId":"u1"},
    "2a573519c1aa40ba81b891f1f10b7083":{
      "scriptId":"u2"},
    "aa14ba2227674993ab30bf69ae31f0d4":{
      "scriptId":"u3"},
    "572a1cd5611e4ea3ac61962a4391da54":{
      "scriptId":"u4"},
    "27e373701dae43c781ab8fb4eeee2ead":{
      "scriptId":"u5"},
    "9bae87c8ff6d4c6c836677230f3c80c4":{
      "scriptId":"u6"},
    "c0eca7a637f440e782165070440fa8aa":{
      "scriptId":"u7",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u8"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u9"}},
    "0918178aa9594c03b81997f457d2b935":{
      "scriptId":"u10"},
    "98b6c05716464c409633392f652f7de4":{
      "scriptId":"u11"},
    "3208e404bcd24a20bd0676caa8457c7f":{
      "scriptId":"u12"},
    "b3dfb036bd804ffb8abe7679a3119cf8":{
      "scriptId":"u13"},
    "6f55b54e715a47bead8690abeb44c5b8":{
      "scriptId":"u14"},
    "088d185640004efd86c5d2cb09aee49c":{
      "scriptId":"u15"},
    "8271bbd5256d4a4da80dabf121ae1cbe":{
      "scriptId":"u16"},
    "3bd3eda37cda46ccb5cc51dad1f45138":{
      "scriptId":"u17"},
    "9d0664c2df51475cad48786e4860c898":{
      "scriptId":"u18",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u19"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u20"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u21"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u22"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u23"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u24"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u25"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u26"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u27"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u28"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u29"}},
    "e27a1d4b8226429c895a51093fb52082":{
      "scriptId":"u30",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u31"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u32"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u33"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u34"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u35"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u36"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u37"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u38"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u39"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u40"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u41"}},
    "99fa7e0829ae4d149ea1226fbc4e5dce":{
      "scriptId":"u42"},
    "125764bd222746b0b19f09a72b0fce20":{
      "scriptId":"u43"},
    "660430e732d2480c80018677a808d819":{
      "scriptId":"u44"},
    "4fb72d750760409ea943be5ce7a385a2":{
      "scriptId":"u45"},
    "2576ecc657494b38ae54d2ec793e9248":{
      "scriptId":"u46",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u47"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u48"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u49"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u50"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u51"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u52"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u53"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u54"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u55"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u56"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u57"}},
    "5d1bdc08a0c441549ade58eca0640054":{
      "scriptId":"u58",
      "19aa459432d34ba1a480d27dff6a8b55":{
        "scriptId":"u59"},
      "d8eb084c43534ec9ad5dd7379a6b8d21":{
        "scriptId":"u60"},
      "c58403d5ffe84b3cafc0a406f2422a7e":{
        "scriptId":"u61"},
      "268120e9977b4ecba9091eee1afda6e7":{
        "scriptId":"u62"},
      "7f9a58d68d2345c0855a95d54de98bcf":{
        "scriptId":"u63"},
      "a10cce0c0bca467eb3e1f3638b8bb751":{
        "scriptId":"u64"},
      "13ba846806714f0a8e7f25e6b65061bb":{
        "scriptId":"u65"},
      "bae5226a8e014bed98634919b29d554c":{
        "scriptId":"u66"},
      "ca0a7d7619c645f19eb35bf7dd9dd523":{
        "scriptId":"u67"},
      "9f7783e454f946e191c3fb64dff07c8a":{
        "scriptId":"u68"},
      "8f6e93e335bd4f91bbee592acd212a8b":{
        "scriptId":"u69"}},
    "0b44debb02244e47bca0560d80252fd8":{
      "scriptId":"u70"},
    "3ecb51594be74efab7eedc01d1c2e7c7":{
      "scriptId":"u71"},
    "169f42e026c04102a6e8b0077c7fbee3":{
      "scriptId":"u72"},
    "091e26623791420dbf9dd2adf995abfd":{
      "scriptId":"u73"}}});