$axure.loadCurrentPage({
  "url":"欢迎页.html",
  "generationDate":new Date(1470576988024.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bf7d3c90722f4dd080bf1f66860ffa9d",
    "type":"Axure:Page",
    "name":"欢迎页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48d40004e3764b7ab4f510013985aaa4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f53cf4486f545ca928e51ba48b19d32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u2.png"}},
{
          "id":"a58290a2e27a4670866ca7e38df72c30",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":150,
              "y":90},
            "size":{
              "width":200,
              "height":200},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f82c3c44087941ad876286c7c32b91e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":150,
                  "y":90},
                "size":{
                  "width":200,
                  "height":200},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u4.png"}},
{
          "id":"17cf9f49b23c4e1aa4cc8985102a03c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":100,
              "y":366},
            "size":{
              "width":300,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fbe4e2a7d8f46e3b9a9d56cbce42a67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":366},
                "size":{
                  "width":300,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0ddd93bacfa644879f0d3b24f3980c01",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":120,
              "y":440},
            "size":{
              "width":260,
              "height":60},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f28ce97368ad4f59a005fe2f61d27489",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":440},
                "size":{
                  "width":260,
                  "height":60},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 第一次登陆主页",
                      "target":{
                        "targetType":"page",
                        "url":"第一次登陆主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手机外观效果/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "48d40004e3764b7ab4f510013985aaa4":{
      "scriptId":"u0"},
    "6f53cf4486f545ca928e51ba48b19d32":{
      "scriptId":"u1"},
    "a58290a2e27a4670866ca7e38df72c30":{
      "scriptId":"u2"},
    "f82c3c44087941ad876286c7c32b91e1":{
      "scriptId":"u3"},
    "17cf9f49b23c4e1aa4cc8985102a03c5":{
      "scriptId":"u4"},
    "0fbe4e2a7d8f46e3b9a9d56cbce42a67":{
      "scriptId":"u5"},
    "0ddd93bacfa644879f0d3b24f3980c01":{
      "scriptId":"u6"},
    "f28ce97368ad4f59a005fe2f61d27489":{
      "scriptId":"u7"}}});