$axure.loadCurrentPage({
  "url":"设置密码.html",
  "generationDate":new Date(1470576990956.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7a15453760cd41f0a32aa8025d3b561b",
    "type":"Axure:Page",
    "name":"设置密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3bc0b5a71c241ab962fa0888b15d6e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64896d8bbd574541a1ba2151abff449b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"6540d405a995465fa2257580d276f0ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"724d61dc409146f189c3fc66ed75ef58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u25.png"}},
{
          "id":"e28a8951cba24bb58b16bfced7ae7c06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "location":{
              "x":165,
              "y":12},
            "size":{
              "width":170,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"613b61ef85ee4930b1994df8ec827768",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "location":{
                  "x":165,
                  "y":12},
                "size":{
                  "width":170,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11d97a60f56e4cd28ece4d3f5eaf59bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2d30ca0c5444fcb493cd1b7e0e1545",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"92fa2bd97a1c4d9fbb3f93348dc079a1",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":46,
              "y":60},
            "size":{
              "width":434,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 注册完成按钮,<br>(形状)",
                      "objectsToFades":[{
                          "objectPath":["b50132ab6a95424a8512076747a198b1"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["60c411f86ffa469ca76f4c98efc8d705"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onFocus":{
              "description":"OnFocus",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 键盘,<br>(Image) 向上滑动 500 毫秒",
                      "objectsToFades":[{
                          "objectPath":["f3e73a6c167e4781bd222efb0c346c67"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["aacab13a8b024184a61fcfa168395201"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "placeholderText":"6-20数字/字母/符号至少包含两种"},
{
          "id":"8993ec0ae7c84b9886444de227619608",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":20,
              "y":140},
            "size":{
              "width":460,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0832c7f16c6343b1b191dbb84cbbf394",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":20,
                  "y":140},
                "size":{
                  "width":460,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u15.png"}},
{
          "id":"0d34a96468c442eaa0c6d8e33bda136a",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
          "id":"22026b51e6b6444cb9f67356ba0db460",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":65},
            "size":{
              "width":16,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e525faf24034730b164d2e4586ae42c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":65},
                "size":{
                  "width":16,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u17.png"}},
{
          "id":"f3e73a6c167e4781bd222efb0c346c67",
          "label":"键盘",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":325},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d8b7dc81c00e4a1784ca26c6f9771a18",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"aacab13a8b024184a61fcfa168395201",
                  "label":"",
                  "parentDynamicPanel":"f3e73a6c167e4781bd222efb0c346c67",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "size":{
                      "width":479,
                      "height":276}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b7d346c59a494b549f7224f2209c8239",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f3e73a6c167e4781bd222efb0c346c67",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "size":{
                          "width":479,
                          "height":276}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录/u25.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"b50132ab6a95424a8512076747a198b1",
          "label":"注册完成按钮",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":20,
              "y":140},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"8dc9dc7b6fd34867b693464410ee8228",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"60c411f86ffa469ca76f4c98efc8d705",
                  "label":"",
                  "parentDynamicPanel":"b50132ab6a95424a8512076747a198b1",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "size":{
                      "width":460,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF990000},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cebedf6a000a45f78a61234d3d69eb0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b50132ab6a95424a8512076747a198b1",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "size":{
                          "width":460,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF990000},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 登录后会员中心",
                              "target":{
                                "targetType":"page",
                                "url":"登录后会员中心.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录/u28.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "b3bc0b5a71c241ab962fa0888b15d6e6":{
      "scriptId":"u0"},
    "64896d8bbd574541a1ba2151abff449b":{
      "scriptId":"u1"},
    "6540d405a995465fa2257580d276f0ba":{
      "scriptId":"u2"},
    "724d61dc409146f189c3fc66ed75ef58":{
      "scriptId":"u3"},
    "e28a8951cba24bb58b16bfced7ae7c06":{
      "scriptId":"u4"},
    "613b61ef85ee4930b1994df8ec827768":{
      "scriptId":"u5"},
    "11d97a60f56e4cd28ece4d3f5eaf59bc":{
      "scriptId":"u6"},
    "3b2d30ca0c5444fcb493cd1b7e0e1545":{
      "scriptId":"u7"},
    "92fa2bd97a1c4d9fbb3f93348dc079a1":{
      "scriptId":"u8"},
    "8993ec0ae7c84b9886444de227619608":{
      "scriptId":"u9"},
    "0832c7f16c6343b1b191dbb84cbbf394":{
      "scriptId":"u10"},
    "0d34a96468c442eaa0c6d8e33bda136a":{
      "scriptId":"u11",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u12"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u13"}},
    "22026b51e6b6444cb9f67356ba0db460":{
      "scriptId":"u14"},
    "8e525faf24034730b164d2e4586ae42c":{
      "scriptId":"u15"},
    "f3e73a6c167e4781bd222efb0c346c67":{
      "scriptId":"u16"},
    "aacab13a8b024184a61fcfa168395201":{
      "scriptId":"u17"},
    "b7d346c59a494b549f7224f2209c8239":{
      "scriptId":"u18"},
    "b50132ab6a95424a8512076747a198b1":{
      "scriptId":"u19"},
    "60c411f86ffa469ca76f4c98efc8d705":{
      "scriptId":"u20"},
    "cebedf6a000a45f78a61234d3d69eb0a":{
      "scriptId":"u21"}}});