$axure.loadCurrentPage({
  "url":"我的业务.html",
  "generationDate":new Date(1470577060124.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ab69947e9aff4388a5b961d3013a648e",
    "type":"Axure:Page",
    "name":"我的业务",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dfbfc904359d4518815fc8464babadfa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":800},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"760555625876467593378174877e5fe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":800},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的业务/u0.png"}},
{
          "id":"5ce6fc19fecb41ddad1a0d1101d46c29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"656f67b8e41040ce9ecdff2f8848ea09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u2.png"}},
{
          "id":"a2b2fb8f196246acbeffe54268343dd9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b955c650118d44f89befc1c1f3bfdec6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u25.png"}},
{
          "id":"41820be0aacf4315b2d0aefc3a8d5771",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":155,
              "y":12},
            "size":{
              "width":170,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7867d7f870dd42e498c04033ed4b32dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":155,
                  "y":12},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af1439b68e934699a1be5ac5cc6e72e0",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":740},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"bottom",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d192a18515d34d10b5b0d4f58482fc21",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"71e6bd9de14c458bb23a3bb0be4d0c8e",
                  "label":"",
                  "parentDynamicPanel":"af1439b68e934699a1be5ac5cc6e72e0",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "size":{
                      "width":160,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3db3edcf4eda43d2826ca32d2bda1301",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af1439b68e934699a1be5ac5cc6e72e0",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "size":{
                          "width":160,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的业务",
                              "target":{
                                "targetType":"page",
                                "url":"我的业务.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/我的业务/u9.png"}},
{
                  "id":"68a5a099e9b6405c81026ab6162b5638",
                  "label":"",
                  "parentDynamicPanel":"af1439b68e934699a1be5ac5cc6e72e0",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "location":{
                      "x":160,
                      "y":0},
                    "size":{
                      "width":160,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4574729ada94d51b8d861b5cb71df3c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af1439b68e934699a1be5ac5cc6e72e0",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "location":{
                          "x":160,
                          "y":0},
                        "size":{
                          "width":160,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的工作",
                              "target":{
                                "targetType":"page",
                                "url":"我的工作.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/我的业务/u9.png"}},
{
                  "id":"769c8592f2d5487a8d82dff37fc75296",
                  "label":"",
                  "parentDynamicPanel":"af1439b68e934699a1be5ac5cc6e72e0",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "location":{
                      "x":320,
                      "y":0},
                    "size":{
                      "width":160,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b41dd28c87b46e3baf65a007aca1e60",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"af1439b68e934699a1be5ac5cc6e72e0",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "location":{
                          "x":320,
                          "y":0},
                        "size":{
                          "width":160,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 服务端-更多",
                              "target":{
                                "targetType":"page",
                                "url":"服务端-更多.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/我的业务/u9.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"bdd2ca7e48ef442d9d35804dc75f56ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":50},
            "size":{
              "width":480,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"561bb797317043f99a25c984b917936f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":50},
                "size":{
                  "width":480,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的业务/u15.png"}},
{
          "id":"d5f20ef811a649c4bb84211ccb300ac5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":40,
              "y":90},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0x7FFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4eae46173f94d318938488764c5ec4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":40,
                  "y":90},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"3",
                "borderFill":{
                  "fillType":"solid",
                  "color":0x7FFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务端-我的信息",
                      "target":{
                        "targetType":"page",
                        "url":"服务端-我的信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的业务/u17.png"}},
{
          "id":"a71d64c8ac574d698968f227719974e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":165,
              "y":100},
            "size":{
              "width":200,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4fe8550414ce4e47abccccb64f1876b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":165,
                  "y":100},
                "size":{
                  "width":200,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务端-我的信息",
                      "target":{
                        "targetType":"page",
                        "url":"服务端-我的信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b945733bc5974680a0299d7c77765210",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":340,
              "y":100},
            "size":{
              "width":130,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f60d952062a845008af58c296d49c340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":340,
                  "y":100},
                "size":{
                  "width":130,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务端-我的信息",
                      "target":{
                        "targetType":"page",
                        "url":"服务端-我的信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4692dc39992043249cd10280332f2a96",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":460,
              "y":15},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6972452bbe544ac796c76c70f9f1ea64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":460,
                  "y":15},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 服务端-我的信息",
                      "target":{
                        "targetType":"page",
                        "url":"服务端-我的信息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的业务/u23.png"}},
{
          "id":"6b75cd22ebb44611907fcb5e848cf627",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":480,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d9523618cf847708a6dc5bf3f2523a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":240},
                "size":{
                  "width":480,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的业务/u25.png"}},
{
          "id":"dc3e18bff1254808a031665c20d50ca6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "verticalAlignment":"middle",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":250},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4966306a651c4b1f971b7cc2c7d61452",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":250},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69c40bf7b4604dcf86167a140a22778b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":250},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69b979ed267f4323933c47ec2886115b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":250},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的工作",
                      "target":{
                        "targetType":"page",
                        "url":"我的工作.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"356b4c35a7e24317912da65a3dc7d1a6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":284},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页/u10_line.png"}},
{
          "id":"f11c09684ff94b5dbcffcc82aff41e5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":380},
            "size":{
              "width":480,
              "height":130},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"29c9c0f6ecea4944b3496f9595333c38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":380},
                "size":{
                  "width":480,
                  "height":130},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的业务/u25.png"}},
{
          "id":"95db422fd48748489fbd89fa3322e5ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "verticalAlignment":"middle",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":390},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70aba27cae56420c95622f84c8d5cb9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "verticalAlignment":"middle",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":390},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0fdd2b780dad4d0cbf38d0ba37a05025",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":424},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页/u10_line.png"}},
{
          "id":"2f09381aa7aa49d1a9db8abdd88d284a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":390},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b7532e2615c45c6b48cc40a7700d685",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":390},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的钱包",
                      "target":{
                        "targetType":"page",
                        "url":"我的钱包.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"802ba7a2dbef4e2a81735e8715dfbb5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":520},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3508713d0a64a7888c9f048d01316e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":520},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u6.png"}},
{
          "id":"1d83b5e774c44da7b4436cb43eaf82a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":530},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"075e468b09ef4a88aabbad7d491e94cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":530},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c75c444a88f84557b23a3ffc2186156f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":564},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/登录页/u10_line.png"}},
{
          "id":"c4bd0c73a16f4965882286476a552e3c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":530},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65bf015fd0ee40248e0ed8f32f8ca7d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":530},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"146d6e374d3540189e6c743199a7b774",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":580},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"698beb20a38245489cf6ef7cc61b22c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":580},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4f7bb1760e264dbf8a109ad10d54b718",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "lineSpacing":"30px",
            "location":{
              "x":280,
              "y":580},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c37693098f354ee2a8803d5e6403634c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "lineSpacing":"30px",
                "location":{
                  "x":280,
                  "y":580},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac364064e0a4486ea912d990436a0734",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":440}},
          "adaptiveStyles":{
},
          "masterId":"7c3a32499ed04e9eb1d72d6c245bd91d"},
{
          "id":"2a69dcba40304244939a500475f38947",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":225,
              "y":300},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52355be7ae574a1ea28403b7667a9620",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":225,
                  "y":300},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的工作-已完成",
                      "target":{
                        "targetType":"page",
                        "url":"我的工作-已完成.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的业务/u57.png"}},
{
          "id":"06eff787423d4510a6aae58ce40c33f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":388,
              "y":298},
            "size":{
              "width":34,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c7aabbddcc14ce8a5b958bb74a53eee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":388,
                  "y":298},
                "size":{
                  "width":34,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收到评价",
                      "target":{
                        "targetType":"page",
                        "url":"收到评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的业务/u59.png"}},
{
          "id":"9aaaa9796fb041fbaedcaf7969f37ed6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":65,
              "y":300},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb8c244d7b0641c281a5deb4c42cd619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":65,
                  "y":300},
                "size":{
                  "width":30,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的工作-待完成",
                      "target":{
                        "targetType":"page",
                        "url":"我的工作-待完成.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的业务/u61.png"}},
{
          "id":"cf3cb64449a947a7ac37367b9c5f3a40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":40,
              "y":340},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c78eb7b1e0e4714a4f37e6d941235f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":40,
                  "y":340},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的工作-待完成",
                      "target":{
                        "targetType":"page",
                        "url":"我的工作-待完成.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"eb0f6edc36c94201a1bf70ba18317085",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":200,
              "y":340},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a38452724b74ce69fc11ccb1672049f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":200,
                  "y":340},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的工作-已完成",
                      "target":{
                        "targetType":"page",
                        "url":"我的工作-已完成.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24e2bd7d78404dbc86cc3b6f8fe52468",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "location":{
              "x":365,
              "y":340},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35d6e935150d414598f109ff329ec46c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "location":{
                  "x":365,
                  "y":340},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收到评价",
                      "target":{
                        "targetType":"page",
                        "url":"收到评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"13f86c09d641403a95ed3863a86597cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":80,
              "y":294},
            "size":{
              "width":20,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4aa0115597f4df4b6cde283058e3130",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":80,
                  "y":294},
                "size":{
                  "width":20,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的业务/u69.png"}}]}},
  "masters":{
    "7c3a32499ed04e9eb1d72d6c245bd91d":{
      "packageId":"7c3a32499ed04e9eb1d72d6c245bd91d",
      "type":"Axure:Master",
      "name":"我的钱包",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"83178dd26ac64847bd6c02e764aa0756",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "horizontalAlignment":"center",
              "lineSpacing":"25px",
              "size":{
                "width":60,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"98a0e10a65c44c3283dc8aa0d90d6cbd",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "horizontalAlignment":"center",
                  "lineSpacing":"25px",
                  "size":{
                    "width":60,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户余额",
                        "target":{
                          "targetType":"page",
                          "url":"账户余额.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"cb18315264444b56acbde2bbad2cd353",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "horizontalAlignment":"center",
              "lineSpacing":"25px",
              "location":{
                "x":165,
                "y":0},
              "size":{
                "width":60,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa6d46f5142c46af9089c40671b184b4",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "horizontalAlignment":"center",
                  "lineSpacing":"25px",
                  "location":{
                    "x":165,
                    "y":0},
                  "size":{
                    "width":60,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 已领取",
                        "target":{
                          "targetType":"page",
                          "url":"已领取.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"00f793cbd4f04c86addbdca71e23bfb7",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"14px",
              "horizontalAlignment":"center",
              "lineSpacing":"25px",
              "location":{
                "x":325,
                "y":0},
              "size":{
                "width":60,
                "height":50}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"49e9eb336f2342cda637f15fef676c48",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"14px",
                  "horizontalAlignment":"center",
                  "lineSpacing":"25px",
                  "location":{
                    "x":325,
                    "y":0},
                  "size":{
                    "width":60,
                    "height":50}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的钱包",
                        "target":{
                          "targetType":"page",
                          "url":"我的钱包.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "dfbfc904359d4518815fc8464babadfa":{
      "scriptId":"u0"},
    "760555625876467593378174877e5fe5":{
      "scriptId":"u1"},
    "5ce6fc19fecb41ddad1a0d1101d46c29":{
      "scriptId":"u2"},
    "656f67b8e41040ce9ecdff2f8848ea09":{
      "scriptId":"u3"},
    "a2b2fb8f196246acbeffe54268343dd9":{
      "scriptId":"u4"},
    "b955c650118d44f89befc1c1f3bfdec6":{
      "scriptId":"u5"},
    "41820be0aacf4315b2d0aefc3a8d5771":{
      "scriptId":"u6"},
    "7867d7f870dd42e498c04033ed4b32dc":{
      "scriptId":"u7"},
    "af1439b68e934699a1be5ac5cc6e72e0":{
      "scriptId":"u8"},
    "71e6bd9de14c458bb23a3bb0be4d0c8e":{
      "scriptId":"u9"},
    "3db3edcf4eda43d2826ca32d2bda1301":{
      "scriptId":"u10"},
    "68a5a099e9b6405c81026ab6162b5638":{
      "scriptId":"u11"},
    "e4574729ada94d51b8d861b5cb71df3c":{
      "scriptId":"u12"},
    "769c8592f2d5487a8d82dff37fc75296":{
      "scriptId":"u13"},
    "1b41dd28c87b46e3baf65a007aca1e60":{
      "scriptId":"u14"},
    "bdd2ca7e48ef442d9d35804dc75f56ef":{
      "scriptId":"u15"},
    "561bb797317043f99a25c984b917936f":{
      "scriptId":"u16"},
    "d5f20ef811a649c4bb84211ccb300ac5":{
      "scriptId":"u17"},
    "f4eae46173f94d318938488764c5ec4b":{
      "scriptId":"u18"},
    "a71d64c8ac574d698968f227719974e8":{
      "scriptId":"u19"},
    "4fe8550414ce4e47abccccb64f1876b7":{
      "scriptId":"u20"},
    "b945733bc5974680a0299d7c77765210":{
      "scriptId":"u21"},
    "f60d952062a845008af58c296d49c340":{
      "scriptId":"u22"},
    "4692dc39992043249cd10280332f2a96":{
      "scriptId":"u23"},
    "6972452bbe544ac796c76c70f9f1ea64":{
      "scriptId":"u24"},
    "6b75cd22ebb44611907fcb5e848cf627":{
      "scriptId":"u25"},
    "9d9523618cf847708a6dc5bf3f2523a7":{
      "scriptId":"u26"},
    "dc3e18bff1254808a031665c20d50ca6":{
      "scriptId":"u27"},
    "4966306a651c4b1f971b7cc2c7d61452":{
      "scriptId":"u28"},
    "69c40bf7b4604dcf86167a140a22778b":{
      "scriptId":"u29"},
    "69b979ed267f4323933c47ec2886115b":{
      "scriptId":"u30"},
    "356b4c35a7e24317912da65a3dc7d1a6":{
      "scriptId":"u31"},
    "f11c09684ff94b5dbcffcc82aff41e5e":{
      "scriptId":"u32"},
    "29c9c0f6ecea4944b3496f9595333c38":{
      "scriptId":"u33"},
    "95db422fd48748489fbd89fa3322e5ad":{
      "scriptId":"u34"},
    "70aba27cae56420c95622f84c8d5cb9c":{
      "scriptId":"u35"},
    "0fdd2b780dad4d0cbf38d0ba37a05025":{
      "scriptId":"u36"},
    "2f09381aa7aa49d1a9db8abdd88d284a":{
      "scriptId":"u37"},
    "0b7532e2615c45c6b48cc40a7700d685":{
      "scriptId":"u38"},
    "802ba7a2dbef4e2a81735e8715dfbb5a":{
      "scriptId":"u39"},
    "a3508713d0a64a7888c9f048d01316e5":{
      "scriptId":"u40"},
    "1d83b5e774c44da7b4436cb43eaf82a5":{
      "scriptId":"u41"},
    "075e468b09ef4a88aabbad7d491e94cc":{
      "scriptId":"u42"},
    "c75c444a88f84557b23a3ffc2186156f":{
      "scriptId":"u43"},
    "c4bd0c73a16f4965882286476a552e3c":{
      "scriptId":"u44"},
    "65bf015fd0ee40248e0ed8f32f8ca7d5":{
      "scriptId":"u45"},
    "146d6e374d3540189e6c743199a7b774":{
      "scriptId":"u46"},
    "698beb20a38245489cf6ef7cc61b22c4":{
      "scriptId":"u47"},
    "4f7bb1760e264dbf8a109ad10d54b718":{
      "scriptId":"u48"},
    "c37693098f354ee2a8803d5e6403634c":{
      "scriptId":"u49"},
    "ac364064e0a4486ea912d990436a0734":{
      "scriptId":"u50",
      "83178dd26ac64847bd6c02e764aa0756":{
        "scriptId":"u51"},
      "98a0e10a65c44c3283dc8aa0d90d6cbd":{
        "scriptId":"u52"},
      "cb18315264444b56acbde2bbad2cd353":{
        "scriptId":"u53"},
      "aa6d46f5142c46af9089c40671b184b4":{
        "scriptId":"u54"},
      "00f793cbd4f04c86addbdca71e23bfb7":{
        "scriptId":"u55"},
      "49e9eb336f2342cda637f15fef676c48":{
        "scriptId":"u56"}},
    "2a69dcba40304244939a500475f38947":{
      "scriptId":"u57"},
    "52355be7ae574a1ea28403b7667a9620":{
      "scriptId":"u58"},
    "06eff787423d4510a6aae58ce40c33f5":{
      "scriptId":"u59"},
    "5c7aabbddcc14ce8a5b958bb74a53eee":{
      "scriptId":"u60"},
    "9aaaa9796fb041fbaedcaf7969f37ed6":{
      "scriptId":"u61"},
    "cb8c244d7b0641c281a5deb4c42cd619":{
      "scriptId":"u62"},
    "cf3cb64449a947a7ac37367b9c5f3a40":{
      "scriptId":"u63"},
    "5c78eb7b1e0e4714a4f37e6d941235f8":{
      "scriptId":"u64"},
    "eb0f6edc36c94201a1bf70ba18317085":{
      "scriptId":"u65"},
    "3a38452724b74ce69fc11ccb1672049f":{
      "scriptId":"u66"},
    "24e2bd7d78404dbc86cc3b6f8fe52468":{
      "scriptId":"u67"},
    "35d6e935150d414598f109ff329ec46c":{
      "scriptId":"u68"},
    "13f86c09d641403a95ed3863a86597cd":{
      "scriptId":"u69"},
    "c4aa0115597f4df4b6cde283058e3130":{
      "scriptId":"u70"}}});