$axure.loadCurrentPage({
  "url":"提交成功.html",
  "generationDate":new Date(1470576992271.96),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4329dc95a2224dfdbcc24feb5e743028",
    "type":"Axure:Page",
    "name":"提交成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2f91507a1fcd433585f6992b434731af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da469315be424456b73070de87eacad9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"7cc65e51286c431d95e4f25d96531e68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":160},
            "size":{
              "width":460,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53023af92f9045889d43309e92e96fad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":160},
                "size":{
                  "width":460,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dc04cbcd0c974c2094e3240c11373c74",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":480,
              "height":150},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96959686f8a64574bc4a07ea6a8e9fe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":240},
                "size":{
                  "width":480,
                  "height":150},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u58.png"}},
{
          "id":"39471e89a6b44de7a221a8507a75bf7c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"50px",
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":260,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"302f10818e074c11821af2f8473bc1fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"50px",
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":260,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92da4c6aac1f4c3792391dbbfce696ef",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":285},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u455_line.png"}},
{
          "id":"2c0e975b71f54b3eb1d39276acbc681d",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":335},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u455_line.png"}},
{
          "id":"80db578663604741af77391f0187c44b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":400},
            "size":{
              "width":460,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8881f865b0fd41c6bfbe6d2215445dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":400},
                "size":{
                  "width":460,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"211192ff0f454598a639cb2a82ac7e8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":25,
              "y":510},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac480c304e0c4ae2b0ff49382d343825",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":25,
                  "y":510},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部订单",
                      "target":{
                        "targetType":"page",
                        "url":"全部订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/提交成功/u12.png"}},
{
          "id":"39cfa53d0d9543dfb91648540ca79223",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "location":{
              "x":256,
              "y":510},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8f8f25350d741d3a7c99900c4d21c29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "location":{
                  "x":256,
                  "y":510},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 主页",
                      "target":{
                        "targetType":"page",
                        "url":"主页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/提交成功/u14.png"}},
{
          "id":"2fa9a3d0568c43bf88d327671f347a3c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":212,
              "y":71},
            "size":{
              "width":76,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ca41828376f4c969c167b4086cd23f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":212,
                  "y":71},
                "size":{
                  "width":76,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交成功/u16.png"}},
{
          "id":"4388f554686b401da930b9f640d8e7a8",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"2d5f002615bc4a688f0a397c702cc139",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"40079d530d1a4697bc171967171f7ad5",
                  "label":"",
                  "parentDynamicPanel":"4388f554686b401da930b9f640d8e7a8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4533e58a1153496e8d833b6ac7da5dd6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4388f554686b401da930b9f640d8e7a8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"d820a6d4acea4f5b9623ed69433bbc2d",
                  "label":"",
                  "parentDynamicPanel":"4388f554686b401da930b9f640d8e7a8",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"73278d16a3ae44ee863cb31115e1583d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4388f554686b401da930b9f640d8e7a8",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "2f91507a1fcd433585f6992b434731af":{
      "scriptId":"u0"},
    "da469315be424456b73070de87eacad9":{
      "scriptId":"u1"},
    "7cc65e51286c431d95e4f25d96531e68":{
      "scriptId":"u2"},
    "53023af92f9045889d43309e92e96fad":{
      "scriptId":"u3"},
    "dc04cbcd0c974c2094e3240c11373c74":{
      "scriptId":"u4"},
    "96959686f8a64574bc4a07ea6a8e9fe9":{
      "scriptId":"u5"},
    "39471e89a6b44de7a221a8507a75bf7c":{
      "scriptId":"u6"},
    "302f10818e074c11821af2f8473bc1fc":{
      "scriptId":"u7"},
    "92da4c6aac1f4c3792391dbbfce696ef":{
      "scriptId":"u8"},
    "2c0e975b71f54b3eb1d39276acbc681d":{
      "scriptId":"u9"},
    "80db578663604741af77391f0187c44b":{
      "scriptId":"u10"},
    "8881f865b0fd41c6bfbe6d2215445dc9":{
      "scriptId":"u11"},
    "211192ff0f454598a639cb2a82ac7e8c":{
      "scriptId":"u12"},
    "ac480c304e0c4ae2b0ff49382d343825":{
      "scriptId":"u13"},
    "39cfa53d0d9543dfb91648540ca79223":{
      "scriptId":"u14"},
    "e8f8f25350d741d3a7c99900c4d21c29":{
      "scriptId":"u15"},
    "2fa9a3d0568c43bf88d327671f347a3c":{
      "scriptId":"u16"},
    "9ca41828376f4c969c167b4086cd23f0":{
      "scriptId":"u17"},
    "4388f554686b401da930b9f640d8e7a8":{
      "scriptId":"u18"},
    "40079d530d1a4697bc171967171f7ad5":{
      "scriptId":"u19"},
    "4533e58a1153496e8d833b6ac7da5dd6":{
      "scriptId":"u20"},
    "d820a6d4acea4f5b9623ed69433bbc2d":{
      "scriptId":"u21"},
    "73278d16a3ae44ee863cb31115e1583d":{
      "scriptId":"u22"}}});