$axure.loadCurrentPage({
  "url":"支付成功.html",
  "generationDate":new Date(1470576993156.02),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e3ca154468654169a4599b73c68dd7cb",
    "type":"Axure:Page",
    "name":"支付成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6b94a1fce8134904bfe93706c0f29df3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5a63d3437f64611a64ea5753ee51e29",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"f5d9137c20ad4571bd130fd6f0661913",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":160},
            "size":{
              "width":460,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b57a1284a414526a3edb760a78e58cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":160},
                "size":{
                  "width":460,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4986d4040956422ab22c48642af6db48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a6443a4bcf5479081b7f6f5f64d847d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":240},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u353.png"}},
{
          "id":"41332a4a5e00401b9d2ad0e3516e499d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "lineSpacing":"50px",
            "location":{
              "x":20,
              "y":240},
            "size":{
              "width":260,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"911a51f8370c44dea5a58f7d40b11b8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "lineSpacing":"50px",
                "location":{
                  "x":20,
                  "y":240},
                "size":{
                  "width":260,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e58b71450cf6488298f8dca154acab19",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":285},
            "size":{
              "width":460,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u455_line.png"}},
{
          "id":"777af3638dda4f578d625b3969a9fff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "lineSpacing":"30px",
            "location":{
              "x":20,
              "y":360},
            "size":{
              "width":460,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c93ebaa387e640b18c90fee077c8f844",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "lineSpacing":"30px",
                "location":{
                  "x":20,
                  "y":360},
                "size":{
                  "width":460,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"59fbd71538c240b6b35037c80d797708",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "location":{
              "x":25,
              "y":470},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da7164c68ee7437e8b66b69a2d424fce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "location":{
                  "x":25,
                  "y":470},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 评价",
                      "target":{
                        "targetType":"page",
                        "url":"评价.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/提交成功/u14.png"}},
{
          "id":"10f700f0ca714f1d8a0a7bcb54b52ce8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":256,
              "y":470},
            "size":{
              "width":220,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6ce65e28470463494c3ecac2eea0123",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":256,
                  "y":470},
                "size":{
                  "width":220,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 全部订单",
                      "target":{
                        "targetType":"page",
                        "url":"全部订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/支付成功/u13.png"}},
{
          "id":"92cd5a2acfbb4306b5bd88b171f89161",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":212,
              "y":71},
            "size":{
              "width":76,
              "height":79}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e3752f723324b79846833f37d03983f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":212,
                  "y":71},
                "size":{
                  "width":76,
                  "height":79}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/提交成功/u16.png"}},
{
          "id":"b660d79dabef4503a91bfc23674c576f",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"d03a4c6b859a41ecad2decc7fe4df421",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"493914a8ee3044c18579b510f8a9397d",
                  "label":"",
                  "parentDynamicPanel":"b660d79dabef4503a91bfc23674c576f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5a29be36768e44e59d2090e31a47d78a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b660d79dabef4503a91bfc23674c576f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/手机外观效果/u25.png"}},
{
                  "id":"fefd70937d304a37bc5c79170135df98",
                  "label":"",
                  "parentDynamicPanel":"b660d79dabef4503a91bfc23674c576f",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":27}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40ece239a5604c6bb2b6f48399cb9afe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b660d79dabef4503a91bfc23674c576f",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":27}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "6b94a1fce8134904bfe93706c0f29df3":{
      "scriptId":"u0"},
    "f5a63d3437f64611a64ea5753ee51e29":{
      "scriptId":"u1"},
    "f5d9137c20ad4571bd130fd6f0661913":{
      "scriptId":"u2"},
    "5b57a1284a414526a3edb760a78e58cc":{
      "scriptId":"u3"},
    "4986d4040956422ab22c48642af6db48":{
      "scriptId":"u4"},
    "9a6443a4bcf5479081b7f6f5f64d847d":{
      "scriptId":"u5"},
    "41332a4a5e00401b9d2ad0e3516e499d":{
      "scriptId":"u6"},
    "911a51f8370c44dea5a58f7d40b11b8f":{
      "scriptId":"u7"},
    "e58b71450cf6488298f8dca154acab19":{
      "scriptId":"u8"},
    "777af3638dda4f578d625b3969a9fff7":{
      "scriptId":"u9"},
    "c93ebaa387e640b18c90fee077c8f844":{
      "scriptId":"u10"},
    "59fbd71538c240b6b35037c80d797708":{
      "scriptId":"u11"},
    "da7164c68ee7437e8b66b69a2d424fce":{
      "scriptId":"u12"},
    "10f700f0ca714f1d8a0a7bcb54b52ce8":{
      "scriptId":"u13"},
    "d6ce65e28470463494c3ecac2eea0123":{
      "scriptId":"u14"},
    "92cd5a2acfbb4306b5bd88b171f89161":{
      "scriptId":"u15"},
    "1e3752f723324b79846833f37d03983f":{
      "scriptId":"u16"},
    "b660d79dabef4503a91bfc23674c576f":{
      "scriptId":"u17"},
    "493914a8ee3044c18579b510f8a9397d":{
      "scriptId":"u18"},
    "5a29be36768e44e59d2090e31a47d78a":{
      "scriptId":"u19"},
    "fefd70937d304a37bc5c79170135df98":{
      "scriptId":"u20"},
    "40ece239a5604c6bb2b6f48399cb9afe":{
      "scriptId":"u21"}}});