$axure.loadCurrentPage({
  "url":"我的钱包.html",
  "generationDate":new Date(1470577061449.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e68b2c53d7b145cfb67e0cbfcae80b27",
    "type":"Axure:Page",
    "name":"我的钱包",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8861b69eda324158bf4ca036289908af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bd79054c7c148dbaede8afad10558f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u0.png"}},
{
          "id":"2ff5677bdaef4c3796abf32e0d3f46d4",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":50}},
          "adaptiveStyles":{
},
          "masterId":"9a9ffb95bba64a6299de35130c9ea228"},
{
          "id":"4afb3f18093946789f1a04947dcd8746",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "fixedHorizontal":"left",
          "fixedMarginHorizontal":10,
          "fixedVertical":"top",
          "fixedMarginVertical":0,
          "fixedKeepInFront":true,
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"5c177d2d1f45448d89014c84d95e8bf5",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"01400d3b37394b5f808b6dd94fd0493e",
                  "label":"",
                  "parentDynamicPanel":"4afb3f18093946789f1a04947dcd8746",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":480,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a0fa4dd67ac4c4f97e6a7a41c0d28c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4afb3f18093946789f1a04947dcd8746",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":480,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录页/u2.png"}},
{
                  "id":"b941387cce344d0a80d51a303eba653e",
                  "label":"",
                  "parentDynamicPanel":"4afb3f18093946789f1a04947dcd8746",
                  "panelIndex":0,
                  "type":"referenceDiagramObject",
                  "styleType":"referenceDiagramObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":10},
                    "size":{
                      "width":30,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
                  "id":"bad20eed010e4892999be663bcb869ce",
                  "label":"",
                  "parentDynamicPanel":"4afb3f18093946789f1a04947dcd8746",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"20px",
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":155,
                      "y":12},
                    "size":{
                      "width":170,
                      "height":30}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4292f45480814f04b29be3874e6038a3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4afb3f18093946789f1a04947dcd8746",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"20px",
                        "horizontalAlignment":"center",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":155,
                          "y":12},
                        "size":{
                          "width":170,
                          "height":30}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"ae04d7e6d6d641458974f77a7808dc0c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":220},
            "size":{
              "width":480,
              "height":280},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da8b5f81ffcb459b94d56e7ba7b1d3d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":220},
                "size":{
                  "width":480,
                  "height":280},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的钱包/u17.png"}},
{
          "id":"9d52cacbeb3c4d38a920a05f295c4890",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"12px",
            "lineSpacing":"40px",
            "location":{
              "x":20,
              "y":230},
            "size":{
              "width":160,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a7b46ad55b247f0952662cbbf533bd8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"12px",
                "lineSpacing":"40px",
                "location":{
                  "x":20,
                  "y":230},
                "size":{
                  "width":160,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"157cf5054e8a4f75b9d142a47dd41bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "lineSpacing":"40px",
            "location":{
              "x":180,
              "y":230},
            "size":{
              "width":120,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"735f2e66b9fe412b9e62fcf8a3e55694",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "lineSpacing":"40px",
                "location":{
                  "x":180,
                  "y":230},
                "size":{
                  "width":120,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6644741fb40745bba47078764ec35dd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"12px",
            "lineSpacing":"40px",
            "location":{
              "x":300,
              "y":230},
            "size":{
              "width":80,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"044a216521a241bc80a654fa8680b396",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"12px",
                "lineSpacing":"40px",
                "location":{
                  "x":300,
                  "y":230},
                "size":{
                  "width":80,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0a58e9f157374e99a61b27b620927de0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"12px",
            "horizontalAlignment":"center",
            "lineSpacing":"40px",
            "location":{
              "x":380,
              "y":230},
            "size":{
              "width":100,
              "height":160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a9d98d1f02b49b3a983cfaccb320ac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"12px",
                "horizontalAlignment":"center",
                "lineSpacing":"40px",
                "location":{
                  "x":380,
                  "y":230},
                "size":{
                  "width":100,
                  "height":160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"27b0f8244eeb440fa55cf531ac18003a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"center",
            "lineSpacing":"40px",
            "location":{
              "x":100,
              "y":520},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4db74a61bd37463d87c508be529f537b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"center",
                "lineSpacing":"40px",
                "location":{
                  "x":100,
                  "y":520},
                "size":{
                  "width":300,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7237dae57eec47a5a2a0c33076ca5097",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":110},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23257c73493d43a9ba985db4f7a2b9cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":110},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录页/u6.png"}},
{
          "id":"8d742bcab9b24535a852260e1497263f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":60,
              "y":154},
            "size":{
              "width":110,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a7691d8db447d3990fb6c2bba08378",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":60,
                  "y":154},
                "size":{
                  "width":110,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"242c543709194fcd95296ab74772d381",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "location":{
              "x":170,
              "y":140},
            "size":{
              "width":160,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441870cfa0944bd48d058a794c7127d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "location":{
                  "x":170,
                  "y":140},
                "size":{
                  "width":160,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "9a9ffb95bba64a6299de35130c9ea228":{
      "packageId":"9a9ffb95bba64a6299de35130c9ea228",
      "type":"Axure:Master",
      "name":"我的钱包导航",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"1e611853861a4ce09edf94541fe70375",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "size":{
                "width":160,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6e11fb4c95884f6f8f3373556d5719d2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "size":{
                    "width":160,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 我的钱包",
                        "target":{
                          "targetType":"page",
                          "url":"我的钱包.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的钱包/u3.png"}},
{
            "id":"e533c37965754275b8f448c1ec3d152b",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "location":{
                "x":160,
                "y":0},
              "size":{
                "width":160,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"ae571f76310941138c34a1b9a54f5ff2",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "location":{
                    "x":160,
                    "y":0},
                  "size":{
                    "width":160,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 账户余额",
                        "target":{
                          "targetType":"page",
                          "url":"账户余额.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的钱包/u3.png"}},
{
            "id":"cc502480c7ac4a1883c013756da6d12d",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"16px",
              "location":{
                "x":320,
                "y":0},
              "size":{
                "width":160,
                "height":50},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"dac608d722d342f793859a2e5763cab1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"16px",
                  "location":{
                    "x":320,
                    "y":0},
                  "size":{
                    "width":160,
                    "height":50},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 已领取",
                        "target":{
                          "targetType":"page",
                          "url":"已领取.html",
                          "includeVariables":true},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"images/我的钱包/u3.png"}}]}},
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "8861b69eda324158bf4ca036289908af":{
      "scriptId":"u0"},
    "4bd79054c7c148dbaede8afad10558f9":{
      "scriptId":"u1"},
    "2ff5677bdaef4c3796abf32e0d3f46d4":{
      "scriptId":"u2",
      "1e611853861a4ce09edf94541fe70375":{
        "scriptId":"u3"},
      "6e11fb4c95884f6f8f3373556d5719d2":{
        "scriptId":"u4"},
      "e533c37965754275b8f448c1ec3d152b":{
        "scriptId":"u5"},
      "ae571f76310941138c34a1b9a54f5ff2":{
        "scriptId":"u6"},
      "cc502480c7ac4a1883c013756da6d12d":{
        "scriptId":"u7"},
      "dac608d722d342f793859a2e5763cab1":{
        "scriptId":"u8"}},
    "4afb3f18093946789f1a04947dcd8746":{
      "scriptId":"u9"},
    "01400d3b37394b5f808b6dd94fd0493e":{
      "scriptId":"u10"},
    "0a0fa4dd67ac4c4f97e6a7a41c0d28c7":{
      "scriptId":"u11"},
    "b941387cce344d0a80d51a303eba653e":{
      "scriptId":"u12",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u13"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u14"}},
    "bad20eed010e4892999be663bcb869ce":{
      "scriptId":"u15"},
    "4292f45480814f04b29be3874e6038a3":{
      "scriptId":"u16"},
    "ae04d7e6d6d641458974f77a7808dc0c":{
      "scriptId":"u17"},
    "da8b5f81ffcb459b94d56e7ba7b1d3d1":{
      "scriptId":"u18"},
    "9d52cacbeb3c4d38a920a05f295c4890":{
      "scriptId":"u19"},
    "4a7b46ad55b247f0952662cbbf533bd8":{
      "scriptId":"u20"},
    "157cf5054e8a4f75b9d142a47dd41bf1":{
      "scriptId":"u21"},
    "735f2e66b9fe412b9e62fcf8a3e55694":{
      "scriptId":"u22"},
    "6644741fb40745bba47078764ec35dd8":{
      "scriptId":"u23"},
    "044a216521a241bc80a654fa8680b396":{
      "scriptId":"u24"},
    "0a58e9f157374e99a61b27b620927de0":{
      "scriptId":"u25"},
    "7a9d98d1f02b49b3a983cfaccb320ac6":{
      "scriptId":"u26"},
    "27b0f8244eeb440fa55cf531ac18003a":{
      "scriptId":"u27"},
    "4db74a61bd37463d87c508be529f537b":{
      "scriptId":"u28"},
    "7237dae57eec47a5a2a0c33076ca5097":{
      "scriptId":"u29"},
    "23257c73493d43a9ba985db4f7a2b9cb":{
      "scriptId":"u30"},
    "8d742bcab9b24535a852260e1497263f":{
      "scriptId":"u31"},
    "56a7691d8db447d3990fb6c2bba08378":{
      "scriptId":"u32"},
    "242c543709194fcd95296ab74772d381":{
      "scriptId":"u33"},
    "441870cfa0944bd48d058a794c7127d6":{
      "scriptId":"u34"}}});