$axure.loadCurrentPage({
  "url":"更多.html",
  "generationDate":new Date(1470576994637.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0cd35361d1bf4af89efdf65fb3c72d14",
    "type":"Axure:Page",
    "name":"更多",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"067f5d08e1474e69a2e03d6bc2791310",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":600},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef7afcb26774434a9266ff65fd45a20c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":600},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"f03df0f00af6433c995323edd2275182",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":480,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c77547f5c4c4480d8c1018d07057600c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":480,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u50.png"}},
{
          "id":"150fe8e50dac4c82894d8e8da91893c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "location":{
              "x":165,
              "y":12},
            "size":{
              "width":170,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef753877d6564b83905f667a37b3552c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":165,
                  "y":12},
                "size":{
                  "width":170,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d93b76d91bf45919b20e769e2be5d3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":10,
              "y":60},
            "size":{
              "width":480,
              "height":100},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fc03689d5de44069c4673f614679fd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":10,
                  "y":60},
                "size":{
                  "width":480,
                  "height":100},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机外观效果/u353.png"}},
{
          "id":"aa6d97a78638426c8456dc3762e37e37",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"50px",
            "location":{
              "x":20,
              "y":60},
            "size":{
              "width":240,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee8906ac350f4e3b828108ccb89034b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"50px",
                "location":{
                  "x":20,
                  "y":60},
                "size":{
                  "width":240,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"612dbad120f94283b164243a3e48a60f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":105},
            "size":{
              "width":480,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/手机外观效果/u420_line.png"}},
{
          "id":"2157e43e605b4e2f9907e763623c199c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "horizontalAlignment":"right",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "lineSpacing":"50px",
            "location":{
              "x":400,
              "y":60},
            "size":{
              "width":80,
              "height":110}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"714b5bdc0780430c83f7655cdd191aee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "horizontalAlignment":"right",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "lineSpacing":"50px",
                "location":{
                  "x":400,
                  "y":60},
                "size":{
                  "width":80,
                  "height":110}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ac91a6cff1ad4c379c3d1d046507c3bc",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10}},
          "adaptiveStyles":{
},
          "masterId":"a1500df9f84846cdaef13ceca4c1e4e8"},
{
          "id":"443bc87d20b641889f8986c40917e07b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":65},
            "size":{
              "width":460,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea534823d4d4be0be7f4c1daa93d202",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":65},
                "size":{
                  "width":460,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 清除缓存",
                      "objectsToFades":[{
                          "objectPath":["d6944394d644482aaa1c710d1e2bfd2b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37a222f656b54ca69fe26e440567ffec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":20,
              "y":115},
            "size":{
              "width":460,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0x797979}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d862adfebc2040d5acc6cee74559a92d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":20,
                  "y":115},
                "size":{
                  "width":460,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0x797979}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 关于我们",
                      "target":{
                        "targetType":"page",
                        "url":"关于我们.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be7dfbee212445ce81cd2fc12742e2c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "location":{
              "x":20,
              "y":190},
            "size":{
              "width":460,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCC0000},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7f51de1da984b6a8a3c6bc90c57cc9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "location":{
                  "x":20,
                  "y":190},
                "size":{
                  "width":460,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCC0000},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 会员中心",
                      "target":{
                        "targetType":"page",
                        "url":"会员中心.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/更多/u20.png"}},
{
          "id":"d6944394d644482aaa1c710d1e2bfd2b",
          "label":"清除缓存",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"25e9f6dd5f3f4edf9a978ee8cc5ec79f",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c36fc56946044ec695db199af4e52491",
                  "label":"",
                  "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "fill":{
                      "fillType":"solid",
                      "color":0x7F000000},
                    "size":{
                      "width":480,
                      "height":600},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0x7F000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ffa0123c6a984f22870730f81f45fb55",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "fill":{
                          "fillType":"solid",
                          "color":0x7F000000},
                        "size":{
                          "width":480,
                          "height":600},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0x7F000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/更多/u23.png"}},
{
                  "id":"2212d7da38884fe7911f36bd836b5ccc",
                  "label":"",
                  "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "location":{
                      "x":140,
                      "y":190},
                    "size":{
                      "width":200,
                      "height":100},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15cf681d59d04826a500b2b1e1d9ce6f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "location":{
                          "x":140,
                          "y":190},
                        "size":{
                          "width":200,
                          "height":100},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/更多/u25.png"}},
{
                  "id":"c58bc8ad07874b7394c2b1efbf423177",
                  "label":"",
                  "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                  "panelIndex":0,
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":140,
                      "y":240},
                    "size":{
                      "width":200,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/更多/u27_line.png"}},
{
                  "id":"e7569350a73d461e8589ced5b2af9fc6",
                  "label":"",
                  "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                  "panelIndex":0,
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":235,
                      "y":245},
                    "size":{
                      "width":10,
                      "height":45},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/更多/u28_line.png"}},
{
                  "id":"24119c1994954a4183b64e9df6fbb561",
                  "label":"",
                  "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "lineSpacing":"50px",
                    "location":{
                      "x":140,
                      "y":195},
                    "size":{
                      "width":200,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69e29af1222a496da685faa1aaf87a1b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "lineSpacing":"50px",
                        "location":{
                          "x":140,
                          "y":195},
                        "size":{
                          "width":200,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e99efbbc24f74ebba7d8fa787623ab5b",
                  "label":"",
                  "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "lineSpacing":"50px",
                    "location":{
                      "x":140,
                      "y":245},
                    "size":{
                      "width":95,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"acc3a18174ce40418833fba1c985d8ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "lineSpacing":"50px",
                        "location":{
                          "x":140,
                          "y":245},
                        "size":{
                          "width":95,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 清除缓存",
                              "objectsToFades":[{
                                  "objectPath":["d6944394d644482aaa1c710d1e2bfd2b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f885feabbaf9429890da799c5f339786",
                  "label":"",
                  "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "fontSize":"14px",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF990000,
                      "opacity":1},
                    "lineSpacing":"50px",
                    "location":{
                      "x":245,
                      "y":245},
                    "size":{
                      "width":95,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3b51ca3f5074bff880a468b0be0e945",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d6944394d644482aaa1c710d1e2bfd2b",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Applied Font Regular', 'Applied Font'",
                        "fontSize":"14px",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF990000,
                          "opacity":1},
                        "lineSpacing":"50px",
                        "location":{
                          "x":245,
                          "y":245},
                        "size":{
                          "width":95,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 清除缓存",
                              "objectsToFades":[{
                                  "objectPath":["d6944394d644482aaa1c710d1e2bfd2b"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
    "a1500df9f84846cdaef13ceca4c1e4e8":{
      "packageId":"a1500df9f84846cdaef13ceca4c1e4e8",
      "type":"Axure:Master",
      "name":"返回上一页",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"c2631126cfbe43f3ba4fde7bf8b4bf9d",
            "label":"",
            "type":"buttonShape",
            "styleType":"paragraph",
            "visible":true,
            "style":{
              "fontName":"'Applied Font Regular', 'Applied Font'",
              "fontSize":"24px",
              "verticalAlignment":"middle",
              "size":{
                "width":30,
                "height":30}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"45340990f29040afbb189a2bcc0517d0",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Applied Font Regular', 'Applied Font'",
                  "fontSize":"24px",
                  "verticalAlignment":"middle",
                  "size":{
                    "width":30,
                    "height":30}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"Case 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkWindow",
                        "description":"在 当前窗口 打开 返回",
                        "target":{
                          "targetType":"backUrl",
                          "includeVariables":false},
                        "linkType":"current"}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif"}}]}}},
  "objectPaths":{
    "067f5d08e1474e69a2e03d6bc2791310":{
      "scriptId":"u0"},
    "ef7afcb26774434a9266ff65fd45a20c":{
      "scriptId":"u1"},
    "f03df0f00af6433c995323edd2275182":{
      "scriptId":"u2"},
    "c77547f5c4c4480d8c1018d07057600c":{
      "scriptId":"u3"},
    "150fe8e50dac4c82894d8e8da91893c8":{
      "scriptId":"u4"},
    "ef753877d6564b83905f667a37b3552c":{
      "scriptId":"u5"},
    "0d93b76d91bf45919b20e769e2be5d3e":{
      "scriptId":"u6"},
    "7fc03689d5de44069c4673f614679fd4":{
      "scriptId":"u7"},
    "aa6d97a78638426c8456dc3762e37e37":{
      "scriptId":"u8"},
    "ee8906ac350f4e3b828108ccb89034b8":{
      "scriptId":"u9"},
    "612dbad120f94283b164243a3e48a60f":{
      "scriptId":"u10"},
    "2157e43e605b4e2f9907e763623c199c":{
      "scriptId":"u11"},
    "714b5bdc0780430c83f7655cdd191aee":{
      "scriptId":"u12"},
    "ac91a6cff1ad4c379c3d1d046507c3bc":{
      "scriptId":"u13",
      "c2631126cfbe43f3ba4fde7bf8b4bf9d":{
        "scriptId":"u14"},
      "45340990f29040afbb189a2bcc0517d0":{
        "scriptId":"u15"}},
    "443bc87d20b641889f8986c40917e07b":{
      "scriptId":"u16"},
    "7ea534823d4d4be0be7f4c1daa93d202":{
      "scriptId":"u17"},
    "37a222f656b54ca69fe26e440567ffec":{
      "scriptId":"u18"},
    "d862adfebc2040d5acc6cee74559a92d":{
      "scriptId":"u19"},
    "be7dfbee212445ce81cd2fc12742e2c6":{
      "scriptId":"u20"},
    "b7f51de1da984b6a8a3c6bc90c57cc9d":{
      "scriptId":"u21"},
    "d6944394d644482aaa1c710d1e2bfd2b":{
      "scriptId":"u22"},
    "c36fc56946044ec695db199af4e52491":{
      "scriptId":"u23"},
    "ffa0123c6a984f22870730f81f45fb55":{
      "scriptId":"u24"},
    "2212d7da38884fe7911f36bd836b5ccc":{
      "scriptId":"u25"},
    "15cf681d59d04826a500b2b1e1d9ce6f":{
      "scriptId":"u26"},
    "c58bc8ad07874b7394c2b1efbf423177":{
      "scriptId":"u27"},
    "e7569350a73d461e8589ced5b2af9fc6":{
      "scriptId":"u28"},
    "24119c1994954a4183b64e9df6fbb561":{
      "scriptId":"u29"},
    "69e29af1222a496da685faa1aaf87a1b":{
      "scriptId":"u30"},
    "e99efbbc24f74ebba7d8fa787623ab5b":{
      "scriptId":"u31"},
    "acc3a18174ce40418833fba1c985d8ce":{
      "scriptId":"u32"},
    "f885feabbaf9429890da799c5f339786":{
      "scriptId":"u33"},
    "e3b51ca3f5074bff880a468b0be0e945":{
      "scriptId":"u34"}}});